function results = analyze_recurrent_class_local_stability_dense()
%ANALYZE_RECURRENT_CLASS_LOCAL_STABILITY_DENSE Remove phase-sampling floor.
%   Rebuilds each tight representative orbit with 1440 phase samples using
%   shape-preserving temporal interpolation, then re-evaluates the saved
%   perturbation trajectories. No PDE trajectory is rerun or overwritten.

study_id = 'recurrent_class_local_stability_dense_v1';
parent_file = fullfile('experiment_outputs', ...
    'recurrent_class_local_stability_v1', ...
    'recurrent_class_local_stability.mat');
validation_file = fullfile('experiment_outputs', ...
    'recurrent_class_validation_v1', 'recurrent_class_validation.mat');
long_file = fullfile('experiment_outputs', ...
    'unresolved_forcing_long_extension_v1', ...
    'unresolved_forcing_long_extensions.mat');
outdir = fullfile('experiment_outputs', study_id);
if ~isfile(parent_file) || ~isfile(validation_file) || ~isfile(long_file)
    error('analyze_recurrent_class_local_stability_dense:MissingParent', ...
        'Local-stability, validation, and long-extension results are required.');
end
if isfolder(outdir)
    error('analyze_recurrent_class_local_stability_dense:OutputExists', ...
        'Refusing to overwrite existing analysis directory: %s', outdir);
end

loaded = load(parent_file, 'results');
parent = loaded.results;
loaded = load(validation_file, 'results');
validation = loaded.results;
loaded = load(long_file, 'results');
long_parent = loaded.results;
cfg = parent.configuration;
cfg.experiment_name = study_id;
cfg.dense_phase_reanalysis = struct('parent_file', parent_file, ...
    'phase_samples', 1440, 'temporal_interpolation', 'pchip', ...
    'reason', ['remove the nearest-phase floor visible as amplitude-independent ', ...
        'late maxima in the original 360-phase analysis'], ...
    'interpretation', ['metric-only reanalysis of saved trajectories; ', ...
        'no new local directions or PDE integrations']);
mkdir(outdir);
brusselator_write_metadata(outdir, cfg, ...
    brusselator_run_metadata(cfg, mfilename, NaN));
timer = tic;

templates = build_dense_references(validation, ...
    cfg.dense_phase_reanalysis.phase_samples);
records = repmat(empty_record(), numel(parent.records), 1);
histories = cell(numel(records),1);
for k = 1:numel(records)
    loaded = load(parent.raw_files{k}, 'case_result');
    item = loaded.case_result;
    template = templates.(parent.records(k).class_id);
    indices = nearest_indices(item.S, item.sample_times);
    [distances, phases, reflections] = ...
        brusselator_states_to_orbit_distances( ...
        item.U(indices,:), item.V(indices,:), template);
    late = item.sample_times >= cfg.recurrent_class_local_stability.duration - ...
        cfg.recurrent_class_local_stability.late_window;
    records(k) = summarize(parent.records(k), distances, phases, ...
        reflections, late, cfg);
    histories{k} = struct('sample_times', item.sample_times, ...
        'orbit_distances', distances, 'best_phase_fraction', phases, ...
        'best_reflection', reflections);
end

summary_table = struct2table(records, 'AsArray', true);
writetable(summary_table, fullfile(outdir, 'dense_local_stability_summary.csv'));
gates = aggregate_gates(records, validation.gates, long_parent.records);
writetable(struct2table(gates, 'AsArray', true), ...
    fullfile(outdir, 'dense_recurrent_class_final_evidence_gates.csv'));
make_figure(outdir, records, histories, cfg);
results = struct('configuration', cfg, 'parent_file', parent_file, ...
    'templates', templates, 'records', records, 'histories', {histories}, ...
    'gates', gates);
save(fullfile(outdir, 'recurrent_class_local_stability_dense.mat'), ...
    'results', '-v7.3');
brusselator_write_metadata(outdir, cfg, ...
    brusselator_run_metadata(cfg, mfilename, toc(timer)));
disp(summary_table);
disp(struct2table(gates, 'AsArray', true));
fprintf('Dense local-stability reanalysis saved in: %s\n', outdir);
end

function templates = build_dense_references(validation, phase_samples)
templates = struct();
classes = {'period_5p0585','period_6p5837'};
for k = 1:2
    index = find(strcmp({validation.validation_records.class_id}, classes{k}) & ...
        [validation.validation_records.N] == 400 & ...
        strcmp({validation.validation_records.factor}, 'tolerance'), 1);
    loaded = load(validation.validation_raw_files{index}, 'case_result');
    item = loaded.case_result;
    period = item.direct.direct_period;
    start_time = item.S(end) - period;
    phase = (0:phase_samples-1)' / phase_samples;
    query = start_time + phase * period;
    templates.(classes{k}) = struct('phase_fraction', phase, ...
        'phase_times', phase * period, 'period', period, ...
        'start_time', start_time, ...
        'U', interp1(item.S, item.U, query, 'pchip'), ...
        'V', interp1(item.S, item.V, query, 'pchip'));
end
end

function indices = nearest_indices(S, query)
indices = zeros(numel(query),1);
for k = 1:numel(query)
    [~, indices(k)] = min(abs(S - query(k)));
end
end

function record = empty_record()
record = struct('case_id', '', 'class_id', '', 'direction', '', ...
    'amplitude_relative_full_state', NaN, 'initial_orbit_distance', NaN, ...
    'final_orbit_distance', NaN, 'late_median_orbit_distance', NaN, ...
    'late_maximum_orbit_distance', NaN, 'late_to_initial_ratio', NaN, ...
    'best_final_phase_fraction', NaN, 'best_final_reflection', false, ...
    'classification', 'unclassified');
end

function record = summarize(original, distances, phases, reflections, late, cfg)
record = empty_record();
record.case_id = original.case_id;
record.class_id = original.class_id;
record.direction = original.direction;
record.amplitude_relative_full_state = original.amplitude_relative_full_state;
record.initial_orbit_distance = distances(1);
record.final_orbit_distance = distances(end);
record.late_median_orbit_distance = median(distances(late));
record.late_maximum_orbit_distance = max(distances(late));
record.late_to_initial_ratio = record.late_median_orbit_distance / ...
    max(record.initial_orbit_distance, eps);
record.best_final_phase_fraction = phases(end);
record.best_final_reflection = reflections(end);
if record.late_median_orbit_distance < ...
        cfg.recurrent_class_local_stability.late_median_threshold && ...
        record.late_maximum_orbit_distance < ...
        cfg.recurrent_class_local_stability.late_maximum_threshold
    record.classification = 'returns_to_representative_orbit_neighborhood';
elseif record.final_orbit_distance > cfg.classification.transition_threshold
    record.classification = 'does_not_return_within_test_window';
else
    record.classification = 'intermediate_or_inconclusive';
end
end

function gates = aggregate_gates(records, numerical_gates, long_records)
classes = {'period_5p0585','period_6p5837'};
representatives = {'amplitude_bmax_12.50','symmetric_ramp_012'};
gates = repmat(struct('class_id', '', 'periodic_orbit_supported', false, ...
    'number_local_cases', NaN, 'number_local_returns', NaN, ...
    'local_attraction_supported', false, ...
    'cross_preparation_orbit_supported', false, ...
    'separated_from_other_period_class', false, ...
    'separated_from_A_B_C', false, ...
    'finite_time_distinct_attractor_supported', false, ...
    'interpretation', ['finite-time numerical evidence restricted to Lx=40; ', ...
        'not a Floquet proof or continuum theorem']), 2, 1);
for k = 1:2
    local = strcmp({records.class_id}, classes{k});
    returned = strcmp({records(local).classification}, ...
        'returns_to_representative_orbit_neighborhood');
    numerical = numerical_gates(strcmp({numerical_gates.class_id}, classes{k}));
    representative = long_records(strcmp({long_records.protocol_id}, ...
        representatives{k}));
    separated_ABC = min([representative.final_median_distance_A, ...
        representative.final_median_distance_B, ...
        representative.final_median_distance_C]) > 0.1;
    gates(k).class_id = classes{k};
    gates(k).periodic_orbit_supported = numerical.periodic_orbit_supported;
    gates(k).number_local_cases = sum(local);
    gates(k).number_local_returns = sum(returned);
    gates(k).local_attraction_supported = all(returned);
    gates(k).cross_preparation_orbit_supported = ...
        numerical.cross_preparation_orbit_supported;
    gates(k).separated_from_other_period_class = ...
        numerical.separated_from_other_period_class;
    gates(k).separated_from_A_B_C = separated_ABC;
    gates(k).finite_time_distinct_attractor_supported = ...
        gates(k).periodic_orbit_supported && ...
        gates(k).local_attraction_supported && ...
        gates(k).cross_preparation_orbit_supported && ...
        gates(k).separated_from_other_period_class && separated_ABC;
end
end

function make_figure(outdir, records, histories, cfg)
fig = figure('Color', 'w', 'Position', [100 100 1000 560]);
hold on;
for k = 1:numel(records)
    semilogy(histories{k}.sample_times, ...
        max(histories{k}.orbit_distances, eps), 'LineWidth', 1.1, ...
        'DisplayName', sprintf('%s, %s, %.0e', records(k).class_id, ...
        records(k).direction, records(k).amplitude_relative_full_state));
end
yline(cfg.recurrent_class_local_stability.late_median_threshold, '--', ...
    'median gate', 'HandleVisibility','off');
yline(cfg.recurrent_class_local_stability.late_maximum_threshold, ':', ...
    'maximum gate', 'HandleVisibility','off');
xlabel('Frozen b=10 integration time');
ylabel('Dense-template orbit distance modulo phase/reflection');
title('Dense-phase reanalysis of recurrent-class local perturbations');
legend('Location','eastoutside','FontSize',7); grid on; box on;
exportgraphics(fig, fullfile(outdir, 'dense_local_orbit_distance_by_case.png'), ...
    'Resolution', 300);
close(fig);
end
