function results = analyze_dynamic_edge_BC_candidate()
%ANALYZE_DYNAMIC_EDGE_BC_CANDIDATE Diagnose recurrent boundary dynamics.
%   Uses both exact post-rebracketing trajectories. Period/recurrence and
%   phase-consistent separation growth are reported as candidate-edge
%   evidence, not as a verified periodic orbit or Floquet calculation.

source_file=fullfile('experiment_outputs','dynamic_edge_tracking_BC_v1', ...
    'dynamic_edge_tracking_BC.mat');
segment_file=fullfile('experiment_outputs','dynamic_edge_tracking_BC_v1', ...
    'segments','segment_01_post_rebracketing.mat');
library_file=fullfile('experiment_outputs','edge_tracking_BA_landing_v1', ...
    'edge_tracking_results.mat');
study_id='dynamic_edge_BC_candidate_analysis_v1';outdir=fullfile( ...
    'experiment_outputs',study_id);
if isfolder(outdir)
    error('analyze_dynamic_edge_BC_candidate:OutputExists', ...
        'Refusing to overwrite existing output: %s',outdir);
end
if ~isfile(source_file)||~isfile(segment_file)||~isfile(library_file)
    error('analyze_dynamic_edge_BC_candidate:MissingSource', ...
        'A required dynamic-edge source file is missing.');
end
source=load(source_file,'results');source=source.results;
loaded=load(segment_file,'segment_data');segment=loaded.segment_data;
loaded=load(library_file,'results');library=loaded.results.library;
cfg=source.configuration;cfg.experiment_name=study_id;
cfg.candidate_analysis=struct('window_starts',[0,20,40], ...
    'recurrence_threshold',2e-2,'growth_section_start',20, ...
    'growth_maximum_separations',[5e-3,1e-2,1.5e-2], ...
    'interpretation',['finite-time evidence for a recurrent edge-state ', ...
        'candidate; no Newton solve, Floquet spectrum, grid refinement, or ', ...
        'multi-cycle convergence has yet verified an invariant periodic orbit']);
mkdir(outdir);timer=tic;

recurrence_records=recurrence_analysis(segment,cfg);
growth_records=growth_analysis(segment,cfg);
distance_records=distance_analysis(segment,library,cfg);
periods=[recurrence_records([recurrence_records.window_start]==20).period];
preferred_growth=growth_records(abs([growth_records.maximum_separation]-1e-2)<eps);
summary=struct('candidate_period_mean',mean(periods), ...
    'candidate_period_spread',max(periods)-min(periods), ...
    'B_period_cv',recurrence_records(3).period_cv, ...
    'C_period_cv',recurrence_records(4).period_cv, ...
    'transverse_growth_rate',preferred_growth.growth_rate, ...
    'per_period_separation_multiplier',preferred_growth.per_period_multiplier, ...
    'growth_fit_R_squared',preferred_growth.R_squared, ...
    'number_stroboscopic_samples',preferred_growth.sample_count, ...
    'minimum_known_orbit_distance',min([distance_records.minimum_distance]), ...
    'status','unstable_periodic_edge_state_candidate', ...
    'interpretation',cfg.candidate_analysis.interpretation);

writetable(struct2table(recurrence_records,'AsArray',true), ...
    fullfile(outdir,'recurrence_window_summary.csv'));
writetable(struct2table(growth_records,'AsArray',true), ...
    fullfile(outdir,'transverse_growth_fits.csv'));
writetable(struct2table(distance_records,'AsArray',true), ...
    fullfile(outdir,'known_orbit_distance_summary.csv'));
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'candidate_edge_summary.csv'));
make_figures(outdir,segment,library,preferred_growth,cfg);
results=struct('configuration',cfg,'source_file',source_file, ...
    'segment_file',segment_file,'recurrence_records',recurrence_records, ...
    'growth_records',growth_records,'distance_records',distance_records, ...
    'summary',summary);
save(fullfile(outdir,'dynamic_edge_BC_candidate_analysis.mat'),'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,toc(timer)));
disp(struct2table(recurrence_records,'AsArray',true));
disp(struct2table(growth_records,'AsArray',true));disp(struct2table(summary,'AsArray',true));
fprintf('Dynamic B--C candidate analysis saved in: %s\n',outdir);
end

function records=recurrence_analysis(segment,cfg)
template=struct('side','','window_start',NaN,'window_end',segment.S(end), ...
    'crossing_count',NaN,'period',NaN,'period_cv',NaN, ...
    'one_cycle_median_return_distance',NaN, ...
    'one_cycle_maximum_return_distance',NaN, ...
    'one_cycle_uses_reflection',false);
records=repmat(template,2*numel(cfg.candidate_analysis.window_starts),1);index=0;
for w=cfg.candidate_analysis.window_starts
    for side={'B','C'}
        index=index+1;analysis=brusselator_periodic_recurrence(segment.S, ...
            segment.(['U_',side{1}]),segment.(['V_',side{1}]),w, ...
            cfg.candidate_analysis.recurrence_threshold);
        one=analysis.recurrence.records(1);records(index).side=side{1};
        records(index).window_start=w;
        records(index).crossing_count=analysis.section.crossing_count;
        records(index).period=analysis.section.period;
        records(index).period_cv=analysis.section.period_cv;
        records(index).one_cycle_median_return_distance= ...
            one.best_median_rel_diff_full_state;
        records(index).one_cycle_maximum_return_distance=min( ...
            one.direct_max_rel_diff_full_state,one.reflection_max_rel_diff_full_state);
        records(index).one_cycle_uses_reflection=one.best_uses_reflection;
    end
end
end

function records=growth_analysis(segment,cfg)
analysis=brusselator_periodic_recurrence(segment.S,segment.U_B,segment.V_B, ...
    cfg.candidate_analysis.growth_section_start, ...
    cfg.candidate_analysis.recurrence_threshold);
times=analysis.section.times;
separations=interp1(segment.S,segment.separation,times,'pchip');
template=struct('section_side','B','section_start', ...
    cfg.candidate_analysis.growth_section_start,'period',analysis.section.period, ...
    'maximum_separation',NaN,'sample_count',NaN,'first_time',NaN,'last_time',NaN, ...
    'growth_rate',NaN,'per_period_multiplier',NaN,'R_squared',NaN);
limits=cfg.candidate_analysis.growth_maximum_separations;
records=repmat(template,numel(limits),1);
for k=1:numel(limits)
    use=separations<=limits(k);x=times(use);y=log(separations(use));
    if numel(x)<3,error('analyze_dynamic_edge_BC_candidate:GrowthSamples', ...
            'Too few stroboscopic samples for growth fit.');end
    design=[ones(numel(x),1),x];coefficients=design\y;prediction=design*coefficients;
    residual=sum((y-prediction).^2);total=sum((y-mean(y)).^2);
    records(k).maximum_separation=limits(k);records(k).sample_count=numel(x);
    records(k).first_time=x(1);records(k).last_time=x(end);
    records(k).growth_rate=coefficients(2);
    records(k).per_period_multiplier=exp(coefficients(2)*analysis.section.period);
    records(k).R_squared=1-residual/max(total,eps);
end
end

function records=distance_analysis(segment,library,cfg)
template=struct('trajectory_side','','outcome','','minimum_distance',NaN, ...
    'late_median_distance',NaN,'late_maximum_distance',NaN);
records=repmat(template,2*numel(library),1);index=0;
for side={'B','C'}
    [~,history]=brusselator_classify_five_way_trajectory(segment.S, ...
        segment.(['U_',side{1}]),segment.(['V_',side{1}]),library, ...
        'late_window',cfg.edge_tracking.late_window, ...
        'sample_interval',cfg.edge_tracking.distance_sample_interval, ...
        'median_threshold',cfg.edge_tracking.median_distance_threshold, ...
        'maximum_threshold',cfg.edge_tracking.maximum_distance_threshold, ...
        'Lx',cfg.grid.Lx);
    late=history.sample_times>=history.sample_times(end)-cfg.edge_tracking.late_window;
    for k=1:numel(library)
        index=index+1;values=history.distances(:,k);
        records(index).trajectory_side=side{1};records(index).outcome=library(k).label;
        records(index).minimum_distance=min(values);
        records(index).late_median_distance=median(values(late));
        records(index).late_maximum_distance=max(values(late));
    end
end
end

function make_figures(outdir,segment,library,growth,cfg)
analysis=brusselator_periodic_recurrence(segment.S,segment.U_B,segment.V_B, ...
    cfg.candidate_analysis.growth_section_start, ...
    cfg.candidate_analysis.recurrence_threshold);
times=analysis.section.times;separations=interp1(segment.S,segment.separation,times,'pchip');
use=separations<=growth.maximum_separation;x=times(use);y=log(separations(use));
coefficients=[ones(numel(x),1),x]\y;fit_values=exp([ones(numel(x),1),x]*coefficients);
fig=figure('Color','w','Position',[100 100 950 550]);ax=axes(fig);hold(ax,'on');
semilogy(ax,times,separations,'o','MarkerFaceColor',[0.15 0.45 0.80], ...
    'DisplayName','Poincare-sampled separation');
semilogy(ax,x,fit_values,'-k','LineWidth',1.5, ...
    'DisplayName',sprintf('exponential fit, gamma = %.4f',growth.growth_rate));
xlabel(ax,'post-rebracketing time');ylabel(ax,'B/C state separation');
title(ax,'Phase-consistent transverse growth near the edge candidate');
style_axes(ax);legend(ax,'Location','northwest');
exportgraphics(fig,fullfile(outdir,'candidate_transverse_growth.png'),'Resolution',300);
close(fig);

fig=figure('Color','w','Position',[100 100 1100 780]);layout=tiledlayout(fig,2,1);
for q=1:2
    ax=nexttile(layout);hold(ax,'on');side={'B','C'};side=side{q};
    [~,history]=brusselator_classify_five_way_trajectory(segment.S, ...
        segment.(['U_',side]),segment.(['V_',side]),library, ...
        'late_window',cfg.edge_tracking.late_window, ...
        'sample_interval',cfg.edge_tracking.distance_sample_interval, ...
        'median_threshold',cfg.edge_tracking.median_distance_threshold, ...
        'maximum_threshold',cfg.edge_tracking.maximum_distance_threshold, ...
        'Lx',cfg.grid.Lx);
    colors=lines(numel(library));
    for k=1:numel(library)
        plot(ax,history.sample_times,history.distances(:,k),'LineWidth',1.1, ...
            'Color',colors(k,:),'DisplayName',library(k).label);
    end
    ylabel(ax,'physical orbit distance');title(ax,[side,'-side exact trajectory']);
    style_axes(ax);if q==1,legend(ax,'Location','eastoutside');end
end
xlabel(nexttile(layout,2),'post-rebracketing time');
title(layout,'Separation of the edge candidate from known invariant outcomes');
exportgraphics(fig,fullfile(outdir,'candidate_known_orbit_distances.png'), ...
    'Resolution',300);close(fig);
end

function style_axes(ax)
set(ax,'Color','w','XColor','k','YColor','k','GridColor',[0.75 0.75 0.75]);
grid(ax,'on');box(ax,'on');ax.Title.Color='k';ax.XLabel.Color='k';ax.YLabel.Color='k';
end
