function cfg = brusselator_edge_tracking_config()
%BRUSSELATOR_EDGE_TRACKING_CONFIG Configuration for the first B--A edge pilot.
%   The experiment interpolates complete forcing-return states, evolves them
%   under the frozen b=10 PDE, and updates a bracket only after an explicit
%   physical five-outcome classification. POD coordinates never determine a
%   bracket update.

tight_moderate = struct('name','ode15s','output_dt',0.2, ...
    'RelTol',1e-6,'AbsTol',1e-8,'MaxStep',0.2);
cfg = brusselator_default_config(struct( ...
    'experiment_name','edge_tracking_BA_landing_v1', ...
    'solver',tight_moderate));
cfg.edge_tracking = struct( ...
    'stage2_file',fullfile('experiment_outputs','stage2_landing_geometry_v2', ...
        'stage2_landing_geometry.mat'), ...
    'left_protocol','amplitude_bmax_11.14', ...
    'left_expected_outcome','B', ...
    'right_protocol','symmetric_ramp_045', ...
    'right_expected_outcome','A', ...
    'frozen_b',10, ...
    'endpoint_orientation',['retain the raw B endpoint and choose raw or exact ', ...
        'reflection of the A endpoint by minimum physical full-state distance'], ...
    'interpolation','X(lambda)=(1-lambda) X_B + lambda X_A', ...
    'maximum_bisection_steps',7, ...
    'classification_duration',80, ...
    'unresolved_extension_duration',240, ...
    'candidate_duration',400, ...
    'late_window',20, ...
    'distance_sample_interval',1, ...
    'median_distance_threshold',1e-2, ...
    'maximum_distance_threshold',2e-2, ...
    'decision_sustain_duration',5, ...
    'recurrence_analysis_window',80, ...
    'recurrence_threshold',2e-2, ...
    'binary_update_rule',['update the bracket only for a unique A or B ', ...
        'classification; stop and report C, R5, R6, ambiguous, or unresolved'], ...
    'interpretation',['finite-time initial-condition edge tracking on one ', ...
        'reflection-aligned line segment; not yet a computed invariant edge state']);
end
