function result = brusselator_execute_forcing_protocol(initial_state, protocol, ...
        base_cfg, solver, refs, initial_post, unresolved_post)
%BRUSSELATOR_EXECUTE_FORCING_PROTOCOL Run and classify one full-state protocol.
%   The trajectory is first followed to INITIAL_POST after b returns to b0.
%   If its A/B/C classification is unresolved, the frozen-b0 trajectory is
%   extended to UNRESOLVED_POST. Both fields are retained throughout.

forcing_end = protocol.Tup + protocol.Thold + protocol.Tdown;
case_cfg = brusselator_default_config(struct( ...
    'experiment_name', [base_cfg.experiment_name, '_', protocol.id], ...
    'model', base_cfg.model, 'grid', base_cfg.grid, 'initial', base_cfg.initial, ...
    'forcing', struct('b0', base_cfg.forcing.b0, 'bmax', protocol.bmax, ...
        'Tup', protocol.Tup, 'Thold', protocol.Thold, 'Tdown', protocol.Tdown), ...
    'time', struct('post_forcing', initial_post), 'solver', solver));
forced_par = brusselator_make_parameters(case_cfg, @(t) overshoot_B(t, ...
    case_cfg.forcing.b0, protocol.bmax, protocol.Tup, protocol.Thold, protocol.Tdown));
[final_state, S, V, U] = solve_brusselator_1d_forced( ...
    initial_state, forced_par, forcing_end + initial_post, 0);

landing_index = find(abs(S - forcing_end) <= max(1e-10, eps(forcing_end)), 1);
if isempty(landing_index)
    [~, landing_index] = min(abs(S - forcing_end));
end
landing_distances = brusselator_three_way_distances( ...
    U(landing_index,:), V(landing_index,:), refs);
[classification, history] = classify(S, U, V, refs, base_cfg);
post_duration = initial_post;
if strcmp(classification.outcome, 'unresolved_within_window') && ...
        unresolved_post > initial_post
    frozen_cfg = case_cfg;
    frozen_cfg.solver = solver;
    frozen_par = brusselator_make_parameters(frozen_cfg, @(t) case_cfg.forcing.b0);
    continuation_duration = unresolved_post - initial_post;
    [final_state, S2, V2, U2] = solve_brusselator_1d_forced( ...
        final_state, frozen_par, continuation_duration, 0);
    S = [S; S(end) + S2(2:end)];
    U = [U; U2(2:end,:)];
    V = [V; V2(2:end,:)];
    post_duration = unresolved_post;
    [classification, history] = classify(S, U, V, refs, base_cfg);
end

recurrence = struct();
if ismember(classification.outcome, ...
        {'B_periodic_reflection_neighborhood', 'C_periodic_direct_neighborhood'})
    recurrence = brusselator_periodic_recurrence(S, U, V, ...
        S(end) - min(40, post_duration), base_cfg.reachability.median_threshold);
end
result = struct('configuration', case_cfg, 'forcing_end', forcing_end, ...
    'post_forcing_duration', post_duration, 'landing_time', S(landing_index), ...
    'landing_state', [linspace(0, case_cfg.grid.Lx, case_cfg.grid.N)', ...
        U(landing_index,:)', V(landing_index,:)'], ...
    'landing_distances', landing_distances, 'S', S, 'U', U, 'V', V, ...
    'final_state', final_state, 'classification', classification, ...
    'distance_history', history, 'recurrence', recurrence);
end

function [classification, history] = classify(S, U, V, refs, cfg)
[classification, history] = brusselator_classify_three_way_trajectory( ...
    S, U, V, refs, ...
    'late_window', cfg.reachability.late_window, ...
    'sample_interval', cfg.reachability.distance_sample_interval, ...
    'median_threshold', cfg.reachability.median_threshold, ...
    'maximum_threshold', cfg.reachability.maximum_threshold);
end
