function cfg = brusselator_ml_pair_acquisition_edge_recovery_config()
%BRUSSELATOR_ML_PAIR_ACQUISITION_EDGE_RECOVERY_CONFIG Frozen pair test.

cfg=brusselator_ml_edge_recovery_config();
cfg.experiment_name='ml_BC_pair_acquisition_edge_recovery_v1';
cfg.ml_edge.model_directory=fullfile('experiment_outputs', ...
    'ml_BC_pair_acquisition_frozen_v1');
cfg.ml_edge.combined_pair_file=fullfile(cfg.ml_edge.model_directory, ...
    'frozen_pair_batch.csv');
cfg.ml_edge.endpoint_labels_file=fullfile('experiment_outputs', ...
    'ml_BC_pair_acquisition_labeling_v1', ...
    'pair_acquisition_endpoint_labels.csv');
cfg.ml_edge.model_names={'pair01','pair02','pair03','pair04'};
cfg.ml_edge.selection_rule=[ ...
    'for each prospectively frozen pair, use it iff independently labeled ', ...
    'endpoints contain exactly one B and one C; retain the original pair order'];
cfg.ml_edge.claim_scope=[ ...
    'retrospective B--C method-development test in the frozen N=400, Lx=40 ', ...
    'POD plane; invariant recovery uses the independently Newton-converged ', ...
    'E_BC orbit and is not a held-out confirmatory result'];
end
