function cfg = brusselator_ml_heldout_CBA_labeling_config(round_index)
%BRUSSELATOR_ML_HELDOUT_CBA_LABELING_CONFIG Frozen adaptive round labels.

if nargin<1,error('A round index is required.');end
cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_heldout_CBA_adaptive_v1';
cfg.ml_labeling.geometry_file=fullfile('experiment_outputs', ...
    'ml_heldout_CBA_geometry_v1','ml_heldout_CBA_geometry.mat');
cfg.ml_labeling.selected_design_role='heldout_candidate';
cfg.ml_labeling.expected_selected_count=2;
cfg.ml_labeling.reported_labels={'A','B','C','other','U'};
cfg.ml_labeling.mapping_rule=[ ...
    'retain A/B/C; unique R5/R6 maps to other while retaining raw outcome; ', ...
    'unresolved or ambiguous maps to U'];
cfg.ml_labeling.held_out_CA_region_used=true;
cfg.ml_labeling.claim_scope=[ ...
    'prospectively selected adaptive labels on the fixed N=400, Lx=40 ', ...
    'held-out C--B--A challenge family'];
cfg.heldout_round=struct( ...
    'round_index',round_index, ...
    'adaptive_directory',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_adaptive_v1'), ...
    'selection_file',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_adaptive_v1',sprintf('round_%02d',round_index), ...
        'selected_pair.csv'), ...
    'selection_manifest',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_adaptive_v1',sprintf('round_%02d',round_index), ...
        'selection_manifest.json'));
end
