function cfg = brusselator_ml_BC_transfer_edge_recovery_config()
%BRUSSELATOR_ML_BC_TRANSFER_EDGE_RECOVERY_CONFIG Conditional transfer audit.

cfg = brusselator_ml_edge_recovery_config();
cfg.experiment_name = 'ml_BC_transfer_edge_recovery_v1';
cfg.ml_labeling.geometry_file = fullfile('experiment_outputs', ...
    'ml_BC_transfer_geometry_v1','ml_BC_transfer_geometry.mat');
cfg.ml_labeling.expected_geometry_id = ...
    'ml_BC_transfer_geometry_v1_N400_Lx40_physical_chord_POD3';
evaluation_dir = fullfile('experiment_outputs','ml_BC_transfer_evaluation_v1');
proposal_dir = fullfile('experiment_outputs','ml_BC_transfer_proposals_v1');
selected_file = fullfile(evaluation_dir,'edge_recovery_pairs.csv');
if ~isfile(selected_file)
    error('brusselator_ml_BC_transfer_edge_recovery_config:MissingEvaluation', ...
        'Prospective endpoint evaluation must finish before edge recovery.');
end
selected = readtable(selected_file,'TextType','string');
if isempty(selected)
    error('brusselator_ml_BC_transfer_edge_recovery_config:NoBracket', ...
        'No prospective method produced a valid B/C bracket.');
end
cfg.ml_edge.model_directory = evaluation_dir;
cfg.ml_edge.combined_pair_file = selected_file;
cfg.ml_edge.frozen_manifest_file = fullfile(proposal_dir, ...
    'frozen_transfer_proposal_manifest.json');
cfg.ml_edge.endpoint_labels_file = fullfile('experiment_outputs', ...
    'ml_BC_transfer_endpoint_labeling_v1','endpoint_labels.csv');
cfg.ml_edge.model_names = cellstr(selected.edge_run_id);
cfg.ml_edge.selection_rule = [ ...
    'conditionally test the highest-ranked actual B/C proposal from each ', ...
    'method; deduplicate identical physical pairs before ten-step guarded ', ...
    'refinement and exact E_BC diagnostics'];
cfg.ml_edge.claim_scope = [ ...
    'prospective end-to-end transfer on one physical-chord/POD3 family; ', ...
    'success establishes recovery of the known local B/C edge mechanism, ', ...
    'not global basin or rare-class discovery'];
end
