function cfg = brusselator_ml_boundary_geometry_config()
%BRUSSELATOR_ML_BOUNDARY_GEOMETRY_CONFIG Freeze the first ML sampling plane.
%   This configuration defines only a two-dimensional family of frozen-system
%   initial states. It does not run the PDE, use the exact edge orbit, or expose
%   the held-out C--B--A challenge interval.

cfg = brusselator_default_config(struct( ...
    'experiment_name','ml_BC_boundary_geometry_v1'));

cfg.ml_boundary = struct();
cfg.ml_boundary.schema_version = '1.0';
cfg.ml_boundary.scope = struct( ...
    'Lx',40,'N',400,'frozen_b',10, ...
    'outcomes',{{'B','C','other','U'}}, ...
    'interpretation',['pre-simulation geometry for a controlled B--C ', ...
        'boundary-learning experiment at fixed Lx=40 and N=400']);
cfg.ml_boundary.sources = struct( ...
    'stage2_file',fullfile('experiment_outputs', ...
        'stage2_landing_geometry_v2','stage2_landing_geometry.mat'), ...
    'B_bracket_file',fullfile('experiment_outputs', ...
        'edge_slice_pairwise_refinement_v1','raw_cases','bc_step_01.mat'), ...
    'C_bracket_file',fullfile('experiment_outputs', ...
        'edge_slice_BC_unresolved_extension_v1','BC_unresolved_extension.mat'), ...
    'expected_B_lambda',0.1875, ...
    'expected_C_lambda',0.187890625);
cfg.ml_boundary.center = struct( ...
    'rule',['align the saved B- and C-side bracket states by exact ', ...
        'reflection, take their complete-state arithmetic midpoint, then ', ...
        'feature-canonicalize the midpoint once'], ...
    'exact_edge_orbit_used',false, ...
    'endpoint_labels_used_only_for_bracket_validation',true);
cfg.ml_boundary.basis = struct( ...
    'source','stage2 results.landing_aware_pod.model', ...
    'components',[1,2], ...
    'minimum_bracket_displacement_retained_fraction',0.9, ...
    'decode_rule',['invert the saved separate u/v scaling and trapezoidal ', ...
        'spatial weighting so phi_1 and phi_2 are stored in physical u/v units'], ...
    'distance_interpretation',['alpha is a coordinate in the scaled POD norm; ', ...
        'all scientific state distances remain in the original physical norm']);
cfg.ml_boundary.bounds = struct( ...
    'source_final_label','B', ...
    'source_label_status','validated_reference_neighborhood', ...
    'rule',['for each of the first two landing-aware POD scores, use half ', ...
        'the observed range among validated forcing-generated B landings'], ...
    'padding_factor',1, ...
    'minimum_concentration',1e-6, ...
    'common_shrink_tolerance',1e-12, ...
    'maximum_shrink_iterations',60);
cfg.ml_boundary.design = struct( ...
    'master_grid_size',17, ...
    'initial_seed_indices',[1,5,9,13,17], ...
    'fixed_test_indices',[3,7,11,15], ...
    'roles',{{'initial_seed','fixed_test','acquisition_pool'}}, ...
    'split_rule',['the 5-by-5 coarse subgrid is the common initial seed; ', ...
        'the interleaved 4-by-4 subgrid is a fixed untouched test set; all ', ...
        'remaining master-grid points form the acquisition pool'], ...
    'ordering',['rows of increasing alpha_2 with alternating alpha_1 ', ...
        'direction; used only for a reflection-continuity diagnostic']);
cfg.ml_boundary.reflection = struct( ...
    'canonicalizer','brusselator_reflection_canonicalize', ...
    'saved_orientations',{{'raw','reflected','feature_canonical', ...
        'serpentine_continuity'}}, ...
    'invariance_tolerance',1e-8, ...
    'continuity_interpretation',['the serpentine orientation is a diagnostic ', ...
        'on this finite grid, not a protocol-independent quotient coordinate']);
cfg.ml_boundary.exclusions = struct( ...
    'exact_edge_orbit',['not loaded or used in the construction; reserved ', ...
        'for later dynamical evaluation'], ...
    'held_out_CA_region',['the lambda approximately 0.276 C--B--A interval ', ...
        'is not loaded, used for bounds, or inspected by this builder']);
cfg.ml_boundary.status = struct( ...
    'simulation_status','not_run', ...
    'outcome_label','', ...
    'meaning',['the manifest freezes candidate states and data splits only; ', ...
        'no row has an inferred or inherited PDE outcome label']);
end
