function cfg = brusselator_physical_ramp_dynamic_edge_config()
%BRUSSELATOR_PHYSICAL_RAMP_DYNAMIC_EDGE_CONFIG Track the physical B--A bracket.
%   The endpoints are the actual states at which two adjacent forcing
%   protocols return to b=10. Interpolation is used only during frozen
%   dynamic rebracketing after the physical protocols have supplied the
%   initial opposite-outcome pair.

cfg = brusselator_physical_ramp_closure_config();
cfg.experiment_name = 'physical_ramp_BA_dynamic_edge_v1';
cfg.dynamic_pair = struct( ...
    'bracket_id','physical_B_A_40p6005859375_40p6015625', ...
    'bracket_file',fullfile('experiment_outputs', ...
        'physical_ramp_40_45_closure_v1','adjacent_outcome_brackets.csv'), ...
    'left_coordinate_column','left_ramp', ...
    'right_coordinate_column','right_ramp', ...
    'left_outcome','B','right_outcome','A', ...
    'separation_threshold',2e-2, ...
    'restart_separation_target',2.5e-4, ...
    'maximum_rebisection_steps',10, ...
    'segment_maximum_duration',220, ...
    'classification_initial_duration',80, ...
    'classification_chunk_duration',40, ...
    'classification_maximum_duration',500, ...
    'recurrence_sample_delay',12, ...
    'recurrence_threshold',2e-2, ...
    'exact_edge_comparison',false, ...
    'exact_edge_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_newton_v1','periodic_edge_orbit_newton.mat'), ...
    'exact_edge_neighborhood_threshold',2e-2, ...
    'exact_edge_period_tolerance',1e-2, ...
    'rule',[ ...
        'evolve the exact return states from adjacent physical B/A forcing ', ...
        'protocols until their separation reaches 0.02; reclassify every ', ...
        'full-state midpoint against A/B/C/R5/R6; stop for any third, ', ...
        'ambiguous, or unresolved outcome; otherwise renew the B/A bracket ', ...
        'to separation 2.5e-4 and evolve one additional segment'], ...
    'claim_scope',[ ...
        'one-event dynamic edge tracking initiated by adjacent physical ', ...
        'forcing protocols at fixed N=400 and Lx=40; an arithmetic midpoint ', ...
        'shadow is diagnostic only and is not an exact PDE trajectory']);
cfg.dynamic_edge.classification_initial_duration = ...
    cfg.dynamic_pair.classification_initial_duration;
cfg.dynamic_edge.classification_chunk_duration = ...
    cfg.dynamic_pair.classification_chunk_duration;
cfg.dynamic_edge.classification_maximum_duration = ...
    cfg.dynamic_pair.classification_maximum_duration;
end
