function cfg = brusselator_ml_edge_recovery_config()
%BRUSSELATOR_ML_EDGE_RECOVERY_CONFIG ML-proposed B--C edge recovery test.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_edge_recovery_v1';
cfg.solver.output_dt=0.2;
cfg.dynamic_edge.classification_maximum_duration=400;
cfg.ml_edge=struct( ...
    'model_directory',fullfile('experiment_outputs','ml_BC_budget_comparison_v1'), ...
    'endpoint_labels_file',fullfile('experiment_outputs', ...
        'ml_BC_edge_bracket_labeling_v1','edge_bracket_endpoint_labels.csv'), ...
    'exact_edge_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_newton_v1','periodic_edge_orbit_newton.mat'), ...
    'model_names',{{'active','baseline'}}, ...
    'maximum_bisection_steps',10, ...
    'candidate_duration',220, ...
    'orbit_distance_sample_interval',0.5, ...
    'edge_neighborhood_threshold',2e-2, ...
    'period_relative_tolerance',1e-2, ...
    'selection_rule',['use the first frozen proposal whose independently ', ...
        'labeled endpoints are one B and one C; do not search using edge distance'], ...
    'recovery_diagnostic',['minimum physical phase/reflection-aware distance ', ...
        'to the independently Newton-converged E_BC orbit, shadow duration, ', ...
        'and direct full-state period when a long enough near-edge segment exists'], ...
    'claim_scope',['dynamical-usefulness test in the frozen N=400, Lx=40 POD ', ...
        'plane; proximity to E_BC is evidence of recovery, not a global ', ...
        'reconstruction of its stable manifold']);
end
