function cfg = brusselator_ml_evolved_BA_scan_config()
%BRUSSELATOR_ML_EVOLVED_BA_SCAN_CONFIG Multiclass scan after BA obstruction.

cfg=brusselator_ml_CBA_edge_tracking_config('BA');
cfg.experiment_name='ml_heldout_CBA_evolved_BA_scan_v1';
coarse=(0:0.1:0.7)';
focused=(0.75:0.025:1)';
cfg.evolved_scan=struct( ...
    'parent_result_file',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_edge_tracking_BA_v1','dynamic_pair_edge_tracking.mat'), ...
    'reuse_result_file',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_edge_tracking_BA_multicycle_v1', ...
        'dynamic_pair_multicycle.mat'), ...
    'alpha_values',unique([coarse;focused]), ...
    'coarse_spacing',0.1,'focused_minimum',0.75,'focused_spacing',0.025, ...
    'left_outcome','B','right_outcome','A', ...
    'reuse_alpha',[0,0.5,0.75,0.875,1], ...
    'reuse_tolerance',1e-11, ...
    'interpretation',[ ...
        'five-way scan of the exact evolved B--A endpoint chord after the ', ...
        'first dynamic divergence; spacing is refined where C obstructed ', ...
        'binary rebracketing'], ...
    'transition_rule',[ ...
        'different outcomes at neighboring sampled alpha values define ', ...
        'candidate adjacent intervals only at the stated nonuniform ', ...
        'resolution; endpoint labels do not prove a unique boundary']);
end
