function cfg = brusselator_default_config(overrides)
%BRUSSELATOR_DEFAULT_CONFIG Central defaults for reproducible experiments.
%   CFG = BRUSSELATOR_DEFAULT_CONFIG() returns the historical main-study
%   configuration. CFG = BRUSSELATOR_DEFAULT_CONFIG(OVERRIDES) recursively
%   replaces supplied fields. Tfinal is always derived from the forcing end
%   time plus time.post_forcing, preventing a run from ending while forcing
%   is still active.

cfg.schema_version = '1.0';
cfg.experiment_name = 'unnamed_brusselator_experiment';

cfg.model = struct( ...
    'a', 2.5, ...
    'd2', 9.73, ...
    'sigma', 0.45);

cfg.grid = struct( ...
    'N', 400, ...
    'Lx', 40);

cfg.forcing = struct( ...
    'b0', 10.0, ...
    'bmax', 11.14, ...
    'Tup', 40, ...
    'Thold', 80, ...
    'Tdown', 40);

cfg.time = struct( ...
    'post_forcing', 140, ...
    'Tfinal', NaN);

% Empty tolerance fields deliberately preserve MATLAB ode45 defaults.
cfg.solver = struct( ...
    'name', 'ode45', ...
    'output_dt', 0.1, ...
    'RelTol', [], ...
    'AbsTol', [], ...
    'MaxStep', []);

cfg.initial = struct( ...
    'seed', 1, ...
    'perturbation_amplitude', 0.01);

cfg.classification = struct( ...
    'recovery_threshold', 1e-2, ...
    'transition_threshold', 1e-1, ...
    'metric_component', 'v', ...
    'metric_norm', 'relative_l2_final_time');

cfg.output = struct( ...
    'root', 'experiment_outputs', ...
    'overwrite', false);

if nargin >= 1 && ~isempty(overrides)
    if ~isstruct(overrides)
        error('brusselator_default_config:InvalidOverrides', ...
            'Overrides must be a structure.');
    end
    cfg = merge_structs(cfg, overrides);
end

cfg.time.forcing_end = cfg.forcing.Tup + cfg.forcing.Thold + cfg.forcing.Tdown;
cfg.time.Tfinal = cfg.time.forcing_end + cfg.time.post_forcing;
brusselator_validate_config(cfg);
end

function merged = merge_structs(base, overrides)
merged = base;
fields = fieldnames(overrides);
for k = 1:numel(fields)
    field_name = fields{k};
    if isfield(base, field_name) && isstruct(base.(field_name)) && ...
            isstruct(overrides.(field_name))
        merged.(field_name) = merge_structs(base.(field_name), overrides.(field_name));
    else
        merged.(field_name) = overrides.(field_name);
    end
end
end
