function cfg = brusselator_ml_heldout_CBA_postbudget_config()
%BRUSSELATOR_ML_HELDOUT_CBA_POSTBUDGET_CONFIG Guarded refinement after test.

cfg=brusselator_ml_heldout_CBA_labeling_config(4);
cfg.experiment_name='ml_heldout_CBA_postbudget_refinement_v1';
cfg.postbudget=struct( ...
    'source_selection',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_adaptive_v1','round_04','selected_pair.csv'), ...
    'source_labels',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_adaptive_v1','round_04','endpoint_labels.csv'), ...
    'parent_edge_file',fullfile('experiment_outputs', ...
        'edge_tracking_BA_landing_v1','edge_tracking_results.mat'), ...
    'maximum_midpoint_tests',6, ...
    'classification_duration',80, ...
    'rule',[ ...
        'bisect the ML-proposed C/A interval; update C or A endpoints, ', ...
        'stop immediately and emit C/B and B/A brackets if B is observed, ', ...
        'and stop without coercion for R5/R6/unresolved/ambiguity'], ...
    'claim_scope',[ ...
        'post-budget dynamical-usefulness diagnostic; these PDE runs do not ', ...
        'count toward the failed predefined eight-run B-detection endpoint']);
end
