function cfg = brusselator_ml_matched_label_bank_config()
%BRUSSELATOR_ML_MATCHED_LABEL_BANK_CONFIG Missing labels for matched benchmark.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_matched_label_bank_missing_v1';
protocol_dir=fullfile('experiment_outputs','ml_BC_matched_benchmark_protocol_v1');
cfg.ml_subset=struct( ...
    'kind','matched_benchmark_missing_label_bank', ...
    'selection_mode','state_index_manifest', ...
    'state_index_file',fullfile(protocol_dir,'missing_label_manifest.csv'), ...
    'expected_unique_count',213, ...
    'required_design_roles',{{'initial_seed','fixed_test','acquisition_pool'}}, ...
    'prerequisite_file',fullfile(protocol_dir,'frozen_protocol_manifest.json'), ...
    'require_frozen_model_manifest',false, ...
    'require_frozen_pair_manifest',false, ...
    'require_frozen_matched_protocol',true, ...
    'final_filename','ml_BC_matched_missing_labels.mat', ...
    'final_csv','matched_missing_labels.csv', ...
    'summary_csv','matched_missing_labeling_summary.csv', ...
    'figure_filename','matched_missing_labels.png', ...
    'maximum_cases_per_invocation',inf, ...
    'parallel_workers',4, ...
    'parallel_batch_size',4, ...
    'test_outcomes_allowed',true, ...
    'interpretation',['complete the fixed 17-by-17 B--C development-plane ', ...
        'label bank after the 12 matched initial designs and acquisition ', ...
        'rules have been frozen; labels remain masked during acquisition']);
end
