function cfg = brusselator_ml_CA_closure_config()
%BRUSSELATOR_ML_CA_CLOSURE_CONFIG Bounded five-way C--A refinement.

cfg=brusselator_ml_evolved_BA_scan_config();
cfg.experiment_name='ml_heldout_CBA_evolved_CA_refinement_v1';
cfg.CA_closure=struct( ...
    'source_scan_file',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_evolved_BA_scan_v1','evolved_BA_scan.mat'), ...
    'left_outcome','C','right_outcome','A', ...
    'expected_left_alpha',0.875,'expected_right_alpha',0.9, ...
    'maximum_bisection_steps',5,'target_width',0.025/2^5, ...
    'rule',[ ...
        'update the bracket only for a unique C or A midpoint outcome; ', ...
        'stop immediately for B, R5, R6, ambiguity, or a final unresolved ', ...
        'classification under the unchanged adaptive horizon'], ...
    'claim_scope',[ ...
        'finite-time five-way refinement of one evolved-state chord at ', ...
        'N=400, Lx=40; a clean label bracket does not by itself establish ', ...
        'a direct basin boundary or an invariant edge state']);
end
