function cfg = brusselator_dynamic_edge_BC_config()
%BRUSSELATOR_DYNAMIC_EDGE_BC_CONFIG First dynamic B--C edge-tracking pilot.

cfg=brusselator_edge_slice_refinement_config();
cfg.experiment_name='dynamic_edge_tracking_BC_v1';
cfg.dynamic_edge=struct( ...
    'source_B_file',fullfile('experiment_outputs', ...
        'edge_slice_pairwise_refinement_v1','raw_cases','bc_step_01.mat'), ...
    'source_C_file',fullfile('experiment_outputs', ...
        'edge_slice_BC_unresolved_extension_v1','BC_unresolved_extension.mat'), ...
    'parent_library_file',fullfile('experiment_outputs', ...
        'edge_tracking_BA_landing_v1','edge_tracking_results.mat'), ...
    'left_outcome','B','right_outcome','C', ...
    'initial_lambda_B',0.1875,'initial_lambda_C',0.187890625, ...
    'separation_threshold',2e-2, ...
    'restart_separation_target',2.5e-4, ...
    'maximum_rebisection_steps',10, ...
    'segment_maximum_duration',140, ...
    'classification_initial_duration',80, ...
    'classification_chunk_duration',40, ...
    'classification_maximum_duration',500, ...
    'number_rebracketing_events',1, ...
    'run_post_rebracketing_segment',true, ...
    'separation_norm',['symmetric quadrature-weighted relative full-state L2 ', ...
        'in original variables and the maintained spatial orientation'], ...
    'interpolation',['linear interpolation of the complete current B- and ', ...
        'C-side discretized states at a common frozen time'], ...
    'update_rule',['update only for uniquely classified B or C midpoints; ', ...
        'stop and save A, R5, R6, ambiguous, or unresolved cases'], ...
    'interpretation',['one-event dynamic edge-tracking pilot; the midpoint ', ...
        'between close bracketing trajectories is an approximate shadow, not ', ...
        'an exact PDE trajectory or a verified invariant edge state']);
end
