function cfg = brusselator_ml_BC_transfer_geometry_config()
%BRUSSELATOR_ML_BC_TRANSFER_GEOMETRY_CONFIG Frozen prospective transfer family.
% The longitudinal direction is the physical-ramp B/C chord. The transverse
% direction is landing-aware POD mode 3 after orthogonalization against that
% chord. No candidate outcome or exact edge-orbit data enter construction.

cfg = brusselator_default_config(struct( ...
    'experiment_name','ml_BC_transfer_geometry_v1'));

cfg.ml_transfer = struct();
cfg.ml_transfer.schema_version = '1.0';
cfg.ml_transfer.scope = struct('Lx',40,'N',400,'frozen_b',10, ...
    'interpretation',['prospective transfer of frozen B/C edge-bracket ', ...
    'acquisition to a physical-chord ribbon distinct from the development ', ...
    'PC1--PC2 plane']);
cfg.ml_transfer.sources = struct( ...
    'B_file',fullfile('experiment_outputs','physical_ramp_BA_dynamic_edge_v1', ...
        'raw_cases','event01_step08.mat'), ...
    'C_file',fullfile('experiment_outputs','physical_ramp_BA_dynamic_edge_v1', ...
        'raw_cases','event01_step10.mat'), ...
    'B_variable','edge_case','C_variable','edge_case', ...
    'required_B_outcome','B','required_C_outcome','C', ...
    'stage2_file',fullfile('experiment_outputs','stage2_landing_geometry_v2', ...
        'stage2_landing_geometry.mat'));
cfg.ml_transfer.basis = struct( ...
    'longitudinal_rule',['normalized complete-state B-to-C displacement in ', ...
        'the saved landing-aware scaled quadrature geometry'], ...
    'transverse_pod_component',3, ...
    'transverse_rule',['landing-aware POD mode 3, orthogonalized against ', ...
        'the physical B/C chord in the saved scaled geometry'], ...
    'minimum_transverse_residual_norm',0.25, ...
    'minimum_subspace_projector_difference_from_PC1_PC2',0.20, ...
    'exact_edge_orbit_used',false);
cfg.ml_transfer.bounds = struct( ...
    'longitudinal_halfwidth_in_chord_lengths',2/3, ...
    'transverse_halfwidth_in_chord_lengths',0.20, ...
    'minimum_concentration',1e-6, ...
    'rule',['fixed before labeling; source B and C states occur at normalized ', ...
        'coordinates (-0.75,0) and (0.75,0), respectively']);
cfg.ml_transfer.design = struct( ...
    'master_grid_size',17, ...
    'initial_row_indices',[3,9,15], ...
    'initial_column_indices',[3,6,9,12,15], ...
    'expected_initial_count',15, ...
    'B_anchor_row',9,'B_anchor_column',3, ...
    'C_anchor_row',9,'C_anchor_column',15, ...
    'initial_rule',['fixed 3-by-5 coarse design including the two physical ', ...
        'chord anchors; nonanchor outcomes are not inspected during design'], ...
    'ordering','rows of increasing transverse coordinate, then longitudinal coordinate');
cfg.ml_transfer.status = struct('simulation_status','not_run', ...
    'outcome_label','', ...
    'meaning',['geometry and initial-design roles only; candidate labels ', ...
        'remain empty until selected states are integrated']);
cfg.ml_transfer.exclusions = struct( ...
    'development_plane_labels','not loaded', ...
    'complete_label_bank','not loaded', ...
    'exact_edge_orbit','not loaded', ...
    'heldout_CBA_region','not loaded');
end
