function cfg = brusselator_periodic_edge_newton_config()
%BRUSSELATOR_PERIODIC_EDGE_NEWTON_CONFIG Single-shooting Newton--Krylov setup.

cfg = brusselator_dynamic_edge_multicycle_config();
cfg.experiment_name = 'periodic_edge_orbit_newton_v1';
cfg.solver = struct('name','ode15s','output_dt',0.05, ...
    'RelTol',1e-9,'AbsTol',1e-11,'MaxStep',0.05);
cfg.newton = struct( ...
    'seed_file',fullfile('experiment_outputs', ...
        'dynamic_edge_BC_fixed_phase_convergence_v1', ...
        'fixed_phase_newton_seed.mat'), ...
    'maximum_iterations',10, ...
    'residual_tolerance',1e-9, ...
    'phase_tolerance',1e-10, ...
    'finite_difference_relative_step',1e-6, ...
    'gmres_restart',30, ...
    'gmres_maximum_outer_iterations',2, ...
    'gmres_minimum_tolerance',1e-4, ...
    'gmres_maximum_tolerance',5e-2, ...
    'line_search_minimum_alpha',1/64, ...
    'line_search_sufficient_decrease',1e-4, ...
    'orbit_output_dt',0.01, ...
    'verification_solver',struct('name','ode45','output_dt',0.05, ...
        'RelTol',1e-10,'AbsTol',1e-12,'MaxStep',0.025), ...
    'equation',['Phi_T(X)-X=0 with <X-X_ref,F(X_ref)>_w=0; ', ...
        'no spatial-shift variable because Neumann boundaries remove ', ...
        'continuous translation symmetry'], ...
    'jacobian',['matrix-free forward finite differences of the normalized ', ...
        'shooting residual, solved by restarted GMRES'], ...
    'interpretation',['a converged result verifies a periodic orbit of the ', ...
        'configured semidiscrete frozen system; it does not yet give Floquet ', ...
        'stability or spatial/grid convergence']);
end
