function cfg = brusselator_ml_BC_transfer_initial_labeling_config()
%BRUSSELATOR_ML_BC_TRANSFER_INITIAL_LABELING_CONFIG Prospective seed labels.

cfg = brusselator_ml_boundary_labeling_config();
cfg.experiment_name = 'ml_BC_transfer_initial_labeling_v1';
cfg.ml_labeling.geometry_file = fullfile('experiment_outputs', ...
    'ml_BC_transfer_geometry_v1','ml_BC_transfer_geometry.mat');
cfg.ml_labeling.expected_geometry_id = ...
    'ml_BC_transfer_geometry_v1_N400_Lx40_physical_chord_POD3';
cfg.ml_labeling.selected_design_role = 'initial_seed';
cfg.ml_labeling.expected_selected_count = 15;
cfg.ml_labeling.state_orientation = ...
    'raw physical state on the frozen physical-chord/POD3 transfer ribbon';
cfg.ml_labeling.claim_scope = [ ...
    'prospective five-way labels for the fixed 15-state initial design on ', ...
    'one transferred physical-chord family; exact E_BC is excluded'];
protocol_dir = fullfile('experiment_outputs','ml_BC_transfer_protocol_v1');
cfg.ml_subset = struct( ...
    'kind','prospective_transfer_initial_design', ...
    'selection_mode','state_index_manifest', ...
    'state_index_file',fullfile(protocol_dir,'frozen_initial_state_manifest.csv'), ...
    'expected_unique_count',15, ...
    'required_design_roles',{{'initial_seed'}}, ...
    'prerequisite_file',fullfile(protocol_dir, ...
        'frozen_transfer_protocol_manifest.json'), ...
    'require_frozen_model_manifest',false, ...
    'require_frozen_pair_manifest',false, ...
    'require_frozen_matched_protocol',false, ...
    'final_filename','ml_BC_transfer_initial_labels.mat', ...
    'final_csv','initial_labels.csv', ...
    'summary_csv','initial_labeling_summary.csv', ...
    'figure_filename','initial_labels.png', ...
    'maximum_cases_per_invocation',inf, ...
    'parallel_workers',4,'parallel_batch_size',4, ...
    'test_outcomes_allowed',true, ...
    'interpretation',['actual frozen-PDE labels generated only after the ', ...
        'transfer geometry and 15-state design were hash-frozen']);
end
