function cfg = brusselator_stage2_geometry_config()
%BRUSSELATOR_STAGE2_GEOMETRY_CONFIG Design contract for landing-state POD.
%   Centralizes the validated outcome library, forcing sources, symmetry and
%   phase conventions, POD weighting, diagnostics, and edge-bracket markers.

cfg = brusselator_default_config(struct( ...
    'experiment_name', 'stage2_landing_geometry_v2'));
cfg.stage2 = struct();
cfg.stage2.scope = struct('Lx', 40, 'N', 400, 'frozen_b', 10, ...
    'interpretation', ['exploratory state-space geometry of validated outcomes ', ...
        'and physically generated landing states']);
cfg.stage2.sources = struct( ...
    'ABC_reference_loader', 'brusselator_three_way_references', ...
    'B_local_gate', fullfile('experiment_outputs', ...
        'periodic_orbit_local_stability_reanalysis_v1', ...
        'refined_local_stability.mat'), ...
    'C_numerical_gate', fullfile('experiment_outputs', ...
        'candidate_c_numerical_validation_v1', ...
        'candidate_c_numerical_validation.mat'), ...
    'C_local_gate', fullfile('experiment_outputs', ...
        'candidate_c_local_stability_v1', ...
        'raw_candidate_c_local_stability.mat'), ...
    'recurrent_validation', fullfile('experiment_outputs', ...
        'recurrent_class_validation_v1', 'recurrent_class_validation.mat'), ...
    'recurrent_local_gate', fullfile('experiment_outputs', ...
        'recurrent_class_local_stability_dense_v1', ...
        'recurrent_class_local_stability_dense.mat'), ...
    'forcing_pilot', fullfile('experiment_outputs', ...
        'forcing_to_c_reachability_pilot_v1', 'forcing_to_c_reachability.mat'), ...
    'ramp_refinement', fullfile('experiment_outputs', ...
        'ramp_transition_refinement_v1', 'ramp_transition_refinement.mat'), ...
    'long_extensions', fullfile('experiment_outputs', ...
        'unresolved_forcing_long_extension_v1', ...
        'unresolved_forcing_long_extensions.mat'));
cfg.stage2.outcomes = struct( ...
    'validated_labels', {{'A','B','C','R5','R6'}}, ...
    'R5_period', 5.0585, 'R6_period', 6.5837, ...
    'R5_representative', 'amplitude_bmax_12.50', ...
    'R6_representative', 'symmetric_ramp_012', ...
    'provisional_labels', {{'R6_candidate_same_period','novel_recurrent','unresolved'}}, ...
    'rule', ['never force a landing state into the nearest known class; ', ...
        'retain novelty and unresolved labels']);
cfg.stage2.phase = struct( ...
    'condition', ['upward crossing of orbit-centered spatial-mean v; ', ...
        'multiple branches resolved modulo exact reflection'], ...
    'dense_template_samples', 1440, ...
    'full_orbit_plot_samples', 80, ...
    'phase_fixed_cycles_to_retain', 8, ...
    'minimum_relative_transversality', 1e-3, ...
    'crossing_time_tolerance', 0.05, ...
    'branch_equivalence_distance', 2e-2, ...
    'required_checks', {{'transversality','crossing_count_stability', ...
        'temporal_resampling','reflection_equivalence','branch_reproducibility'}}, ...
    'fallback', ['retain all non-reflection-equivalent branches or use ', ...
        'closest-template phase minimization; never choose silently']);
cfg.stage2.reflection = struct( ...
    'symmetry', 'x_to_L_minus_x', ...
    'state_rule', ['choose orientation by the first nonzero reflection-odd ', ...
        'cosine feature; invariant ties need no orientation'], ...
    'orbit_rule', ['choose orientation once at the phase-fixed anchor and ', ...
        'apply it to the entire orbit; do not flip individual orbit phases'], ...
    'landing_objects_to_save', {{'raw','reflected','feature_canonical', ...
        'family_continuity_oriented'}}, ...
    'family_continuity_rule', ...
        'choose raw or reflected state nearest the previous oriented family member', ...
    'invariance_test_tolerance', 1e-8);
cfg.stage2.norms = struct( ...
    'physical', ['quadrature-weighted full-state L2 in original u/v units; ', ...
        'used for recurrence and orbit comparisons'], ...
    'classification', ['physical full-state norm minimized over temporal ', ...
        'phase and exact reflection'], ...
    'pod_primary', ['sqrt(dx) spatial weighting plus separate stored RMS ', ...
        'scales for u and v; visualization/reconstruction only'], ...
    'pod_sensitivity', ['sqrt(dx) spatial weighting in original u/v units, ', ...
        'without separate component normalization'], ...
    'prohibition', ['POD-coordinate proximity must not be reported as a ', ...
        'physical orbit distance']);
cfg.stage2.pod = struct( ...
    'training_set', ['balanced validated outcome library only with explicit ', ...
        'sample weights; no duplicated stationary rows'], ...
    'class_aggregate_weights', struct('A',0.2,'B',0.2,'C',0.2,'R5',0.2,'R6',0.2), ...
    'sample_weight_rule', ['A receives weight 0.2; each phase sample of a ', ...
        'periodic class receives 0.2 divided by its number of samples'], ...
    'weighted_svd_rule', ['subtract the explicitly weighted mean and multiply ', ...
        'each centered sample row by sqrt(sample_weight) before SVD'], ...
    'landing_states_are_passive', true, ...
    'maximum_components', 20, ...
    'diagnostic_component_counts', [2,3,5,10,20], ...
    'landing_aware_trigger_maximum_error_ratio', 3, ...
    'landing_aware_outcome_aggregate_weight', 0.5, ...
    'landing_aware_landing_aggregate_weight', 0.5, ...
    'landing_aware_rule', ['diagnostic only: retain half the aggregate weight ', ...
        'on the balanced outcome library and distribute half equally over ', ...
        'feature-canonical landing states'], ...
    'fallback', ['fit a second landing-aware POD only if passive landing-state ', ...
        'reconstruction errors are materially larger than orbit-library errors']);
cfg.stage2.edge_brackets = struct( ...
    'primary', struct('left_ramp',40,'left_label','B', ...
        'right_ramp',45,'right_label','A'), ...
    'secondary', struct('left_ramp',16,'left_label','R5', ...
        'right_ramp',17,'right_label','B'));
cfg.stage2.required_figures = { ...
    'phase_fixed_outcomes_and_landings_PC1_PC2', ...
    'full_orbit_loops_and_landings_PC1_PC2', ...
    'full_orbit_loops_PC1_PC2_PC3', ...
    'landing_distance_to_each_validated_orbit', ...
    'POD_explained_variance_and_reconstruction_error', ...
    'reflection_continuity_diagnostic', ...
    'pod_scaling_sensitivity', ...
    'landing_aware_POD_diagnostic'};
end
