function cfg = brusselator_periodic_edge_branch_config()
%BRUSSELATOR_PERIODIC_EDGE_BRANCH_CONFIG Unstable Floquet branch test.

cfg = brusselator_dynamic_edge_BC_config();
cfg.experiment_name = 'periodic_edge_orbit_unstable_branches_v1';
cfg.solver = struct('name','ode15s','output_dt',0.2, ...
    'RelTol',1e-7,'AbsTol',1e-9,'MaxStep',0.1);
cfg.branches = struct( ...
    'floquet_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_floquet_v2','periodic_edge_orbit_floquet.mat'), ...
    'relative_amplitudes',[1e-5,1e-4], ...
    'signs',[-1,1], ...
    'required_outcomes',{{'B','C'}}, ...
    'perturbation_rule',['delta X = sign*epsilon*||X_*||_w*v_u, where ', ...
        'v_u has unit quadrature-weighted norm'], ...
    'classification_rule',['use the established five-way physical ', ...
        'phase/reflection-aware classifier and retain any A/R5/R6/ambiguous/', ...
        'unresolved result rather than forcing a B/C label'], ...
    'interpretation',['opposite B/C outcomes from the two local unstable ', ...
        'branches support local basin-boundary organization by the periodic orbit']);
end
