function cfg = brusselator_ml_matched_label_bank_shard_config(shard)
%BRUSSELATOR_ML_MATCHED_LABEL_BANK_SHARD_CONFIG One frozen execution shard.

if nargin<1||~isscalar(shard)||shard<1||shard>4||shard~=round(shard)
    error('brusselator_ml_matched_label_bank_shard_config:Shard','Shard must be 1--4.');
end
cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name=sprintf('ml_BC_matched_label_bank_shard%02d_v1',shard);
protocol_dir=fullfile('experiment_outputs','ml_BC_matched_benchmark_protocol_v1');
shard_dir=fullfile('experiment_outputs','ml_BC_matched_label_bank_shards_v1');
manifest_file=fullfile(shard_dir,sprintf('shard_%02d_manifest.csv',shard));
if ~isfile(manifest_file)
    error('brusselator_ml_matched_label_bank_shard_config:MissingManifest', ...
        'Frozen shard manifest is missing: %s',manifest_file);
end
manifest=readtable(manifest_file);
cfg.ml_subset=struct( ...
    'kind',sprintf('matched_benchmark_label_bank_shard_%02d',shard), ...
    'selection_mode','state_index_manifest', ...
    'state_index_file',manifest_file, ...
    'expected_unique_count',height(manifest), ...
    'parent_missing_label_state_count',213, ...
    'required_design_roles',{{'initial_seed','fixed_test','acquisition_pool'}}, ...
    'prerequisite_file',fullfile(protocol_dir,'frozen_protocol_manifest.json'), ...
    'shard_plan_file',fullfile(shard_dir,'frozen_shard_plan.json'), ...
    'require_frozen_model_manifest',false, ...
    'require_frozen_pair_manifest',false, ...
    'require_frozen_matched_protocol',true, ...
    'require_frozen_shard_plan',true, ...
    'final_filename',sprintf('ml_BC_matched_missing_labels_shard%02d.mat',shard), ...
    'final_csv',sprintf('matched_missing_labels_shard%02d.csv',shard), ...
    'summary_csv',sprintf('matched_missing_labeling_summary_shard%02d.csv',shard), ...
    'figure_filename',sprintf('matched_missing_labels_shard%02d.png',shard), ...
    'maximum_cases_per_invocation',inf, ...
    'test_outcomes_allowed',true, ...
    'interpretation',['one outcome-blind execution shard of the frozen matched ', ...
        'B--C label bank; the PDE and five-way classifier are unchanged']);
end
