function cfg = brusselator_periodic_edge_resolution_config()
%BRUSSELATOR_PERIODIC_EDGE_RESOLUTION_CONFIG Exact-orbit grid continuation.

cfg = brusselator_periodic_edge_newton_config();
cfg.experiment_name = 'periodic_edge_orbit_resolution_continuation_v1';
cfg.resolution_continuation = struct( ...
    'resolutions',[200,400,600], ...
    'source_resolution',400, ...
    'source_orbit_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_newton_v1','periodic_edge_orbit_newton.mat'), ...
    'source_floquet_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_floquet_v2','periodic_edge_orbit_floquet.mat'), ...
    'regridding','shape-preserving cubic interpolation at fixed Lx=40', ...
    'target_phase_reference',['regridded N=400 phase-fixed state with the ', ...
        'target-grid frozen vector field as phase tangent'], ...
    'comparison_spatial_points',1201, ...
    'comparison_phase_points',200, ...
    'expected_spatial_order',2, ...
    'required_newton_residual',1e-8, ...
    'required_phase_multiplier_error',1e-6, ...
    'required_eigenpair_residual',1e-7, ...
    'interpretation',['persistence and numerical convergence of the periodic ', ...
        'edge orbit at fixed Lx=40; changing N tests the semidiscrete ', ...
        'representation, not domain dependence or continuum existence']);
end
