function cfg = brusselator_ml_CBA_multicycle_config(bracket_id)
%BRUSSELATOR_ML_CBA_MULTICYCLE_CONFIG Continue rapid edge rebracketing.

cfg=brusselator_ml_CBA_edge_tracking_config(bracket_id);
cfg.experiment_name=['ml_heldout_CBA_edge_tracking_', ...
    upper(char(bracket_id)),'_multicycle_v1'];
parent_dir=fullfile('experiment_outputs', ...
    ['ml_heldout_CBA_edge_tracking_',upper(char(bracket_id)),'_v1']);
cfg.multicycle_pair=struct( ...
    'parent_result_file',fullfile(parent_dir,'dynamic_pair_edge_tracking.mat'), ...
    'parent_post_segment_file',fullfile(parent_dir,'segments', ...
        'segment_01_post_rebracketing.mat'), ...
    'first_new_event_index',2, ...
    'additional_events',3, ...
    'interpretation',[ ...
        'three additional rapid dynamic rebracketing events after the ', ...
        'completed one-event pilot; trends diagnose whether the tracked ', ...
        'boundary approaches a reproducible invariant region']);
end
