function cfg = brusselator_ml_fixed_test_labeling_config()
%BRUSSELATOR_ML_FIXED_TEST_LABELING_CONFIG Blind labels after model freezing.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_fixed_test_labeling_v1';
cfg.ml_subset=struct( ...
    'kind','blind_fixed_test', ...
    'selection_mode','design_role', ...
    'selected_design_role','fixed_test', ...
    'expected_unique_count',16, ...
    'required_design_role','fixed_test', ...
    'prerequisite_file',fullfile('experiment_outputs', ...
        'ml_BC_budget_comparison_v1','frozen_model_manifest.json'), ...
    'require_frozen_model_manifest',true, ...
    'final_filename','ml_BC_fixed_test_labels.mat', ...
    'final_csv','fixed_test_labels.csv', ...
    'summary_csv','fixed_test_labeling_summary.csv', ...
    'figure_filename','fixed_test_labeling.png', ...
    'maximum_cases_per_invocation',inf, ...
    'test_outcomes_allowed',true, ...
    'interpretation',['blind fixed-test outcomes generated only after both ', ...
        'budget-matched models and their predictions are frozen']);
end
