function cfg = brusselator_ml_pair_acquisition_labeling_config()
%BRUSSELATOR_ML_PAIR_ACQUISITION_LABELING_CONFIG Frozen pair-aware endpoints.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_pair_acquisition_labeling_v1';
frozen_dir=fullfile('experiment_outputs','ml_BC_pair_acquisition_frozen_v1');
pair_file=fullfile(frozen_dir,'frozen_pair_batch.csv');
manifest_file=fullfile(frozen_dir,'frozen_pair_manifest.json');
if ~isfile(pair_file)||~isfile(manifest_file)
    error('brusselator_ml_pair_acquisition_labeling_config:MissingFrozenBatch', ...
        'The outcome-blind pair-aware batch must be frozen before labeling.');
end
cfg.ml_subset=struct( ...
    'kind','frozen_pair_aware_development_endpoints', ...
    'selection_mode','pair_batch_union', ...
    'pair_batch_file',pair_file, ...
    'expected_unique_count',8, ...
    'required_design_role','acquisition_pool', ...
    'prerequisite_file',manifest_file, ...
    'require_frozen_model_manifest',false, ...
    'require_frozen_pair_manifest',true, ...
    'final_filename','ml_BC_pair_acquisition_labels.mat', ...
    'final_csv','pair_acquisition_endpoint_labels.csv', ...
    'summary_csv','pair_acquisition_labeling_summary.csv', ...
    'figure_filename','pair_acquisition_endpoint_labels.png', ...
    'maximum_cases_per_invocation',inf, ...
    'test_outcomes_allowed',false, ...
    'interpretation',['prospective endpoint labels for four robust joint-', ...
        'posterior pair proposals on the retrospective B--C development plane']);
end
