function cfg = brusselator_physical_ramp_closure_config()
%BRUSSELATOR_PHYSICAL_RAMP_CLOSURE_CONFIG Bounded physical forcing closure.
%   This experiment refines the actual symmetric-ramp protocol coordinate;
%   it never interpolates forcing-return states when assigning protocol
%   outcomes. Every landing state is evolved under the frozen b=10 PDE and
%   classified against the validated A/B/C/R5/R6 orbit library.

cfg = brusselator_ml_boundary_labeling_config();
cfg.experiment_name = 'physical_ramp_40_45_closure_v1';
cfg.solver = struct('name','ode15s','output_dt',0.2, ...
    'RelTol',1e-6,'AbsTol',1e-8,'MaxStep',0.2);
cfg.dynamic_edge.classification_initial_duration = 80;
cfg.dynamic_edge.classification_chunk_duration = 40;
cfg.dynamic_edge.classification_maximum_duration = 500;

cfg.physical_ramp = struct( ...
    'bmax',11.14, ...
    'Thold',80, ...
    'left_ramp',40, ...
    'right_ramp',45, ...
    'seed_spacing',0.5, ...
    'maximum_protocol_runs',20, ...
    'minimum_refinement_width',5/2^14, ...
    'frozen_b',10, ...
    'initial_condition_rule',['the documented seed-1 perturbation is rebuilt ', ...
        'once and reused for every forcing protocol'], ...
    'seed_design',['uniform symmetric-ramp scan at spacing 0.5, including ', ...
        'fresh T_ramp=40 and 45 endpoint gates'], ...
    'adaptive_rule',['after the seed scan, repeatedly bisect the widest ', ...
        'adjacent sampled protocol interval whose finite-time five-way ', ...
        'labels differ; unresolved and ambiguous labels are retained and ', ...
        'also count as differences'], ...
    'adjacency_scope',['adjacent only within the sampled one-dimensional ', ...
        'protocol set; the finite scan cannot exclude a narrower unsampled ', ...
        'basin window between equal-label samples'], ...
    'edge_rule',['only adjacent intervals with two unique validated outcome ', ...
        'labels are eligible for subsequent dynamic edge tracking'], ...
    'confirmation_solver',struct('name','ode15s','output_dt',0.2, ...
        'RelTol',1e-7,'AbsTol',1e-9,'MaxStep',0.1), ...
    'confirmation_rule',['repeat any forcing-generated C outcome with the ', ...
        'tighter solver and require a unique C classification'], ...
    'claim_scope',['bounded finite-time forcing accessibility study at ', ...
        'N=400, Lx=40, bmax=11.14, Thold=80, seed=1; not a proof that ', ...
        'unsampled basin windows are absent']);
end
