function cfg = brusselator_ml_heldout_CBA_geometry_config()
%BRUSSELATOR_ML_HELDOUT_CBA_GEOMETRY_CONFIG Frozen challenge geometry.

cfg=brusselator_default_config();
cfg.experiment_name='ml_heldout_CBA_geometry_v1';
cfg.grid.N=400;cfg.grid.Lx=40;
cfg.heldout=struct( ...
    'parent_edge_file',fullfile('experiment_outputs', ...
        'edge_tracking_BA_landing_v1','edge_tracking_results.mat'), ...
    'coarse_training_csv',fullfile('experiment_outputs', ...
        'edge_slice_scan_BCA_v1','five_way_slice_scan.csv'), ...
    'lambda_minimum',0.275, ...
    'lambda_maximum',0.300, ...
    'grid_subintervals',128, ...
    'previously_simulated_interior_lambdas', ...
        [0.27578125;0.276171875;0.2765625;0.278125;0.28125;0.2875], ...
    'coordinate_tolerance',1e-12, ...
    'interpolation','X(lambda)=(1-lambda) X_B + lambda X_A', ...
    'training_rule',[ ...
        'use only the completed 0.025-spaced five-way scan labels; ', ...
        'do not read pairwise-refinement outcomes'], ...
    'exclusion_rule',[ ...
        'challenge endpoints are coarse training states; all previously ', ...
        'simulated interior refinement coordinates are excluded by lambda ', ...
        'without loading their outcomes'], ...
    'claim_scope',[ ...
        'fixed N=400, Lx=40 one-dimensional held-out state family; ', ...
        'the existence of an intervening B pilot is historically known, ', ...
        'but its fine geometry is not used for acquisition']);
end
