function cfg = brusselator_edge_slice_scan_config()
%BRUSSELATOR_EDGE_SLICE_SCAN_CONFIG Five-way scan before pairwise bisection.

cfg=brusselator_edge_tracking_config();
cfg.experiment_name='edge_slice_scan_BCA_v1';
cfg.scan=struct( ...
    'parent_edge_file',fullfile('experiment_outputs', ...
        'edge_tracking_BA_landing_v1','edge_tracking_results.mat'), ...
    'lambda_minimum',0,'lambda_maximum',0.5,'lambda_step',0.025, ...
    'lambda_values',(0:0.025:0.5)', ...
    'reuse_parent_lambdas',[0,0.25,0.5], ...
    'classification_duration',80, ...
    'unresolved_extension_duration',240, ...
    'interpretation',['moderately dense five-way scan of the reflection-aligned ', ...
        'B-landing to A-landing interpolation before any pairwise bisection'], ...
    'transition_rule',['different labels at adjacent sampled lambda values define ', ...
        'candidate transition intervals at this resolution, not proven direct ', ...
        'two-basin adjacency']);
end
