function cfg = brusselator_ml_CBA_edge_tracking_config(bracket_id)
%BRUSSELATOR_ML_CBA_EDGE_TRACKING_CONFIG Dynamic tracking of new brackets.

cfg=brusselator_ml_heldout_CBA_postbudget_config();
bracket_id=upper(char(bracket_id));
switch bracket_id
    case 'CB'
        cfg.experiment_name='ml_heldout_CBA_edge_tracking_CB_v1';
        left='C';right='B';compare_exact=true;
    case 'BA'
        cfg.experiment_name='ml_heldout_CBA_edge_tracking_BA_v1';
        left='B';right='A';compare_exact=false;
    otherwise
        error('brusselator_ml_CBA_edge_tracking_config:Bracket', ...
            'Bracket id must be CB or BA.');
end
cfg.dynamic_pair=struct( ...
    'bracket_id',bracket_id, ...
    'bracket_file',fullfile('experiment_outputs', ...
        'ml_heldout_CBA_postbudget_refinement_v1', ...
        'discovered_adjacent_brackets.csv'), ...
    'left_outcome',left,'right_outcome',right, ...
    'separation_threshold',2e-2, ...
    'restart_separation_target',2.5e-4, ...
    'maximum_rebisection_steps',10, ...
    'segment_maximum_duration',220, ...
    'classification_initial_duration',80, ...
    'classification_chunk_duration',40, ...
    'classification_maximum_duration',500, ...
    'recurrence_sample_delay',12, ...
    'recurrence_threshold',2e-2, ...
    'exact_edge_comparison',compare_exact, ...
    'exact_edge_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_newton_v1','periodic_edge_orbit_newton.mat'), ...
    'exact_edge_neighborhood_threshold',2e-2, ...
    'exact_edge_period_tolerance',1e-2, ...
    'rule',[ ...
        'evolve both exact endpoints until physical separation reaches 0.02; ', ...
        'classify full-state midpoints under the five-way frozen system until ', ...
        'the renewed separation is at most 2.5e-4; stop for any third, ', ...
        'ambiguous, or unresolved outcome; then evolve one renewed segment'], ...
    'claim_scope',[ ...
        'one-event dynamic edge tracking at fixed N=400 and Lx=40; ', ...
        'an arithmetic midpoint shadow is diagnostic only and is never ', ...
        'treated as an exact PDE trajectory']);
cfg.dynamic_edge.classification_initial_duration= ...
    cfg.dynamic_pair.classification_initial_duration;
cfg.dynamic_edge.classification_chunk_duration= ...
    cfg.dynamic_pair.classification_chunk_duration;
cfg.dynamic_edge.classification_maximum_duration= ...
    cfg.dynamic_pair.classification_maximum_duration;
end
