function cfg = brusselator_BC_edge_resolution_config()
%BRUSSELATOR_BC_EDGE_RESOLUTION_CONFIG Matched B--edge--C grid study.

cfg = brusselator_periodic_edge_resolution_config();
cfg.experiment_name = 'BC_edge_resolution_geometry_v1';
cfg.solver = struct('name','ode15s','output_dt',0.2, ...
    'RelTol',1e-7,'AbsTol',1e-9,'MaxStep',0.1);
cfg.dynamic_edge.classification_initial_duration = 80;
cfg.dynamic_edge.classification_chunk_duration = 40;
cfg.dynamic_edge.classification_maximum_duration = 400;
cfg.BC_resolution = struct( ...
    'outcomes',{{'B','C'}}, ...
    'resolutions',[200,400,600], ...
    'source_resolution',400, ...
    'stage2_file',fullfile('experiment_outputs','stage2_landing_geometry_v2', ...
        'stage2_landing_geometry.mat'), ...
    'edge_resolution_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_resolution_continuation_v1', ...
        'periodic_edge_orbit_resolution_continuation.mat'), ...
    'branch_relative_amplitude',1e-4, ...
    'branch_signs',[-1,1], ...
    'exact_library_phase_samples',720, ...
    'comparison_spatial_points',1201, ...
    'comparison_phase_points',200, ...
    'attracting_modulus_margin',1e-3, ...
    'newton_residual_gate',1e-8, ...
    'verification_residual_gate',1e-8, ...
    'phase_multiplier_error_gate',1e-6, ...
    'eigenpair_residual_gate',1e-7, ...
    'branch_rule',['orient every unstable edge eigenvector against the N=400 ', ...
        'physical direction, then classify both signs against exact ', ...
        'grid-matched B/C orbit libraries with an unresolved fallback'], ...
    'claim_scope',['fixed-Lx grid robustness of the local B--edge--C geometry; ', ...
        'the two-class exact library never forces a nonmatching trajectory ', ...
        'to B or C']);
end
