function cfg = brusselator_ml_edge_bracket_labeling_config()
%BRUSSELATOR_ML_EDGE_BRACKET_LABELING_CONFIG Label frozen ML bracket endpoints.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_edge_bracket_labeling_v1';
model_dir=fullfile('experiment_outputs','ml_BC_budget_comparison_v1');
active_file=fullfile(model_dir,'active_edge_bracket_proposals.csv');
baseline_file=fullfile(model_dir,'baseline_edge_bracket_proposals.csv');
if ~isfile(active_file) || ~isfile(baseline_file)
    error('brusselator_ml_edge_bracket_labeling_config:MissingFrozenProposals', ...
        'The label-blind bracket proposals must be frozen before labeling.');
end
A=readtable(active_file); B=readtable(baseline_file);
indices=unique([A.B_state_index;A.C_state_index;B.B_state_index;B.C_state_index]);
cfg.ml_subset=struct( ...
    'kind','frozen_ML_edge_bracket_endpoints', ...
    'selection_mode','edge_bracket_union', ...
    'active_proposals_file',active_file, ...
    'baseline_proposals_file',baseline_file, ...
    'expected_unique_count',numel(indices), ...
    'required_design_role','acquisition_pool', ...
    'prerequisite_file',fullfile(model_dir,'frozen_model_manifest.json'), ...
    'require_frozen_model_manifest',true, ...
    'final_filename','ml_BC_edge_bracket_labels.mat', ...
    'final_csv','edge_bracket_endpoint_labels.csv', ...
    'summary_csv','edge_bracket_labeling_summary.csv', ...
    'figure_filename','edge_bracket_endpoint_labels.png', ...
    'maximum_cases_per_invocation',inf, ...
    'test_outcomes_allowed',false, ...
    'interpretation',['out-of-training endpoint labels for four label-blind ', ...
        'separator brackets proposed by each frozen budget-matched model']);
end
