function cfg = brusselator_ml_boundary_labeling_config()
%BRUSSELATOR_ML_BOUNDARY_LABELING_CONFIG Adaptive labels for the frozen plane.

cfg=brusselator_BC_edge_resolution_config();
cfg.experiment_name='ml_BC_boundary_initial_labeling_v1';
cfg.dynamic_edge.classification_initial_duration=80;
cfg.dynamic_edge.classification_chunk_duration=40;
cfg.dynamic_edge.classification_maximum_duration=400;

cfg.ml_labeling=struct( ...
    'geometry_file',fullfile('experiment_outputs','ml_BC_boundary_geometry_v1', ...
        'ml_BC_boundary_geometry.mat'), ...
    'expected_geometry_id','ml_BC_boundary_geometry_v1_N400_Lx40_PC1_PC2', ...
    'stage2_file',fullfile('experiment_outputs','stage2_landing_geometry_v2', ...
        'stage2_landing_geometry.mat'), ...
    'exact_B_file',fullfile('experiment_outputs','BC_edge_resolution_geometry_v1', ...
        'B_N0400_newton','periodic_edge_orbit_newton.mat'), ...
    'exact_C_file',fullfile('experiment_outputs','BC_edge_resolution_geometry_v1', ...
        'C_N0400_newton','periodic_edge_orbit_newton.mat'), ...
    'selected_design_role','initial_seed', ...
    'expected_selected_count',25, ...
    'exact_periodic_phase_samples',720, ...
    'raw_library_order',{{'A','B','C','R5','R6'}}, ...
    'reported_labels',{{'B','C','other','U'}}, ...
    'other_raw_outcomes',{{'A','R5','R6'}}, ...
    'unresolved_raw_outcomes',{{'unresolved','ambiguous_multiple_outcomes'}}, ...
    'mapping_rule',['B and C remain primary labels; unique A/R5/R6 matches ', ...
        'map to other while retaining the raw class; unresolved or ambiguous ', ...
        'five-way cases map to U'], ...
    'state_orientation','raw physical state saved by the frozen plane builder', ...
    'maximum_cases_per_invocation',inf, ...
    'save_full_trajectories',true, ...
    'exact_edge_orbit_used',false, ...
    'held_out_CA_region_used',false, ...
    'claim_scope',['adaptive finite-time outcome labels on the fixed N=400, ', ...
        'Lx=40 two-dimensional initial-state family; U is not an attractor label']);
end
