function cfg = brusselator_periodic_edge_floquet_config()
%BRUSSELATOR_PERIODIC_EDGE_FLOQUET_CONFIG Leading monodromy spectrum setup.

cfg = brusselator_periodic_edge_newton_config();
cfg.experiment_name = 'periodic_edge_orbit_floquet_v2';
cfg.floquet = struct( ...
    'orbit_file',fullfile('experiment_outputs', ...
        'periodic_edge_orbit_newton_v1','periodic_edge_orbit_newton.mat'), ...
    'number_multipliers',10, ...
    'arnoldi_tolerance',1e-8, ...
    'arnoldi_maximum_iterations',300, ...
    'arnoldi_subspace_dimension',30, ...
    'solver',struct('name','ode15s','RelTol',1e-9,'AbsTol',1e-11, ...
        'MaxStep',0.025), ...
    'unstable_modulus_threshold',1+1e-3, ...
    'phase_multiplier_target',1, ...
    'predicted_transverse_multiplier',1.24079, ...
    'finite_difference_check_amplitude',1e-6, ...
    'coordinate_system',['Euclidean Arnoldi coordinates obtained by multiplying ', ...
        'u and v perturbations by square roots of trapezoidal spatial weights'], ...
    'interpretation',['leading Floquet multipliers of the configured semidiscrete ', ...
        'periodic orbit; one trivial unit multiplier is required by time phase']);
end
