function cfg = brusselator_edge_slice_refinement_config()
%BRUSSELATOR_EDGE_SLICE_REFINEMENT_CONFIG Guarded pairwise slice refinement.

cfg=brusselator_edge_slice_scan_config();
cfg.experiment_name='edge_slice_pairwise_refinement_v1';
pair_template=struct('pair_id','','left_outcome','','right_outcome','');
pairs=repmat(pair_template,2,1);
pairs(1)=struct('pair_id','BC','left_outcome','B','right_outcome','C');
pairs(2)=struct('pair_id','CA','left_outcome','C','right_outcome','A');
cfg.refinement=struct( ...
    'scan_file',fullfile('experiment_outputs','edge_slice_scan_BCA_v1', ...
        'edge_slice_scan_results.mat'), ...
    'pairs',pairs, ...
    'maximum_bisection_steps',6, ...
    'classification_duration',80, ...
    'target_width',0.025/2^6, ...
    'update_rule',['update a pairwise bracket only when the midpoint has one ', ...
        'of its two endpoint labels; stop and retain any third, ambiguous, ', ...
        'or unresolved outcome'], ...
    'interpretation',['finite-time refinement of candidate adjacent basin ', ...
        'transitions detected by the preceding five-way scan; a refined ', ...
        'label bracket is not yet an invariant edge state']);
end
