function cfg = brusselator_ml_acquisition_labeling_config()
%BRUSSELATOR_ML_ACQUISITION_LABELING_CONFIG Label matched active/baseline sets.

cfg=brusselator_ml_boundary_labeling_config();
cfg.experiment_name='ml_BC_acquisition_labeling_v1';
cfg.ml_subset=struct( ...
    'kind','active_and_space_filling_union', ...
    'selection_mode','proposal_union', ...
    'active_proposals_file',fullfile('experiment_outputs', ...
        'ml_BC_probabilistic_boundary_v1','active_acquisition_proposals.csv'), ...
    'baseline_proposals_file',fullfile('experiment_outputs', ...
        'ml_BC_probabilistic_boundary_v1','space_filling_baseline_proposals.csv'), ...
    'required_active_count',8,'required_baseline_count',8, ...
    'required_overlap_count',1,'expected_unique_count',15, ...
    'required_design_role','acquisition_pool', ...
    'prerequisite_file',fullfile('experiment_outputs', ...
        'ml_BC_probabilistic_boundary_v1','model_summary.json'), ...
    'require_frozen_model_manifest',false, ...
    'final_filename','ml_BC_acquisition_labels.mat', ...
    'final_csv','acquisition_labels.csv', ...
    'summary_csv','acquisition_labeling_summary.csv', ...
    'figure_filename','acquisition_labeling.png', ...
    'maximum_cases_per_invocation',inf, ...
    'test_outcomes_allowed',false, ...
    'interpretation',['matched eight-state active and eight-state ', ...
        'space-filling budgets with one shared state; fixed-test states excluded']);
end
