function cfg = brusselator_ml_matched_edge_recovery_config()
%BRUSSELATOR_ML_MATCHED_EDGE_RECOVERY_CONFIG Conditional repeated edge tests.

cfg=brusselator_ml_edge_recovery_config();
cfg.experiment_name='ml_BC_matched_edge_recovery_v1';
evaluation_dir=fullfile('experiment_outputs', ...
    'ml_BC_matched_acquisition_evaluation_v1');
proposal_dir=fullfile('experiment_outputs', ...
    'ml_BC_matched_acquisition_proposals_v1');
selected_file=fullfile(evaluation_dir,'unique_edge_recovery_pairs.csv');
if ~isfile(selected_file)
    error('brusselator_ml_matched_edge_recovery_config:MissingEvaluation', ...
        'Matched endpoint evaluation must finish before edge recovery.');
end
selected=readtable(selected_file,'TextType','string');
cfg.ml_edge.model_directory=evaluation_dir;
cfg.ml_edge.combined_pair_file=selected_file;
cfg.ml_edge.frozen_manifest_file=fullfile(proposal_dir, ...
    'frozen_proposal_manifest.json');
cfg.ml_edge.endpoint_labels_file=fullfile('experiment_outputs', ...
    'ml_BC_matched_label_bank_v1','complete_label_bank.csv');
cfg.ml_edge.model_names=cellstr(selected.edge_run_id);
cfg.ml_edge.selection_rule=[ ...
    'conditionally test the highest-ranked independently verified B--C ', ...
    'proposal for each method and matched initial-design replicate; identical ', ...
    'physical pairs are integrated once and attributed to every selecting ', ...
    'group; use unchanged ten-step multiclass-safe bisection and exact-edge diagnostics'];
cfg.ml_edge.claim_scope=[ ...
    'conditional dynamical-usefulness test on the controlled N=400, Lx=40 ', ...
    'B--C plane; replicate-level bracket yield is primary, while exact-edge ', ...
    'recovery is evaluated only when a method produced a valid bracket'];
end
