function cfg = brusselator_dynamic_edge_multicycle_config()
%BRUSSELATOR_DYNAMIC_EDGE_MULTICYCLE_CONFIG Extend B--C edge tracking.

cfg=brusselator_dynamic_edge_BC_config();
cfg.experiment_name='dynamic_edge_tracking_BC_multicycle_v1';
cfg.multicycle=struct( ...
    'parent_result_file',fullfile('experiment_outputs', ...
        'dynamic_edge_tracking_BC_v1','dynamic_edge_tracking_BC.mat'), ...
    'parent_post_segment_file',fullfile('experiment_outputs', ...
        'dynamic_edge_tracking_BC_v1','segments', ...
        'segment_01_post_rebracketing.mat'), ...
    'first_new_event_index',2, ...
    'additional_rebracketing_events',3, ...
    'phase_sample_delay',12, ...
    'phase_recurrence_threshold',2e-2, ...
    'template_norm',['symmetric quadrature-weighted full-state L2 in original ', ...
        'variables, minimized over exact reflection after Poincare phase fixing'], ...
    'flow_residual_norm',['direct quadrature-weighted relative full-state L2 ', ...
        'after integrating the phase-fixed template for its measured period'], ...
    'newton_seed_gate',['periods, consecutive phase-fixed template distances, ', ...
        'and direct one-period flow residuals must converge across later cycles']);
end
