function results = build_ml_BC_boundary_geometry()
%BUILD_ML_BC_BOUNDARY_GEOMETRY Freeze the two-dimensional B--C ML plane.
%   The center is the midpoint of a saved, independently classified B/C
%   bracket. The directions are the first two landing-aware Stage-2 POD modes,
%   decoded into physical variables. This function creates an auditable state
%   manifest but deliberately performs no PDE outcome simulations.

run_timer = tic;
cfg = brusselator_ml_boundary_geometry_config();
outdir = fullfile(cfg.output.root,cfg.experiment_name);
if isfolder(outdir)
    error('build_ml_BC_boundary_geometry:OutputExists', ...
        'Refusing to overwrite frozen sampling geometry: %s',outdir);
end
validate_sources(cfg);

stage2_loaded = load(cfg.ml_boundary.sources.stage2_file,'results');
stage2 = stage2_loaded.results;
validate_stage2(stage2,cfg);
[bracket,center] = load_bracket_and_center(cfg);
[basis,pod_model] = decode_basis(stage2,cfg);
[bounds,bound_source] = derive_bounds(stage2,center,basis,pod_model,cfg);
[states,manifest,reflection_audit] = build_master_grid( ...
    center,basis,bounds,pod_model,cfg);
bracket_projection = audit_bracket_projection( ...
    bracket,center,basis,pod_model,cfg);
if min([bracket_projection.scaled_retained_fraction]) < ...
        cfg.ml_boundary.basis.minimum_bracket_displacement_retained_fraction
    error('build_ml_BC_boundary_geometry:BracketProjectionGateFailed', ...
        ['The selected two-mode plane retains too little of the known B--C ', ...
        'bracket displacement.']);
end
source_provenance = collect_source_provenance(cfg);
summary = make_summary(stage2,bracket,center,basis,bounds,manifest, ...
    reflection_audit,bracket_projection,cfg);

mkdir(outdir);
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,NaN));
writetable(struct2table(manifest,'AsArray',true), ...
    fullfile(outdir,'sampling_state_manifest.csv'));
writetable(struct2table(bracket_projection,'AsArray',true), ...
    fullfile(outdir,'bracket_projection_audit.csv'));
writetable(struct2table(bound_source,'AsArray',true), ...
    fullfile(outdir,'bound_source_landings.csv'));
writetable(struct2table(reflection_audit,'AsArray',true), ...
    fullfile(outdir,'reflection_continuity_audit.csv'));
writetable(struct2table(source_provenance,'AsArray',true), ...
    fullfile(outdir,'source_provenance.csv'));
writetable(struct2table(basis_summary(basis,pod_model),'AsArray',true), ...
    fullfile(outdir,'basis_summary.csv'));
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'sampling_geometry_summary.csv'));
make_figure(outdir,manifest,bounds,bracket_projection,cfg);

results = struct('configuration',cfg,'source_provenance',source_provenance, ...
    'bracket',bracket,'center',center,'basis',basis,'bounds',bounds, ...
    'bound_source',bound_source,'states',states,'manifest',manifest, ...
    'reflection_audit',reflection_audit, ...
    'bracket_projection',bracket_projection,'summary',summary);
save(fullfile(outdir,'ml_BC_boundary_geometry.mat'),'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,toc(run_timer)));

disp(struct2table(summary,'AsArray',true));
fprintf('Frozen ML B--C sampling geometry saved in: %s\n',outdir);
end

function validate_sources(cfg)
sources = cfg.ml_boundary.sources;
for name = {'stage2_file','B_bracket_file','C_bracket_file'}
    if ~isfile(sources.(name{1}))
        error('build_ml_BC_boundary_geometry:MissingSource', ...
            'Missing required source %s: %s',name{1},sources.(name{1}));
    end
end
if cfg.grid.N~=cfg.ml_boundary.scope.N || cfg.grid.Lx~=cfg.ml_boundary.scope.Lx
    error('build_ml_BC_boundary_geometry:ScopeMismatch', ...
        'The configured numerical grid does not match the declared ML scope.');
end
end

function validate_stage2(stage2,cfg)
if ~isfield(stage2,'landing_aware_pod') || ...
        ~stage2.landing_aware_pod.triggered || ...
        isempty(stage2.landing_aware_pod.model)
    error('build_ml_BC_boundary_geometry:MissingLandingAwarePOD', ...
        'Stage 2 did not save the required landing-aware POD model.');
end
model = stage2.landing_aware_pod.model;
if numel(model.mean_U)~=cfg.grid.N || size(model.modes,1)~=2*cfg.grid.N
    error('build_ml_BC_boundary_geometry:PODGridMismatch', ...
        'The landing-aware POD model is not on the declared N=%d grid.',cfg.grid.N);
end
if max(cfg.ml_boundary.basis.components)>model.maximum_components
    error('build_ml_BC_boundary_geometry:MissingPODComponents', ...
        'The requested POD components were not saved.');
end
end

function [bracket,center] = load_bracket_and_center(cfg)
b_loaded = load(cfg.ml_boundary.sources.B_bracket_file,'refinement_case');
c_loaded = load(cfg.ml_boundary.sources.C_bracket_file,'results');
B = b_loaded.refinement_case;
C = c_loaded.results;
if ~strcmp(B.classification.outcome,'B') || ...
        ~strcmp(C.classification.outcome,'C')
    error('build_ml_BC_boundary_geometry:InvalidBracketLabels', ...
        'Saved center sources are not an independently classified B/C bracket.');
end
if abs(B.lambda-cfg.ml_boundary.sources.expected_B_lambda)>1e-12 || ...
        abs(C.summary.lambda-cfg.ml_boundary.sources.expected_C_lambda)>1e-12
    error('build_ml_BC_boundary_geometry:InvalidBracketLambda', ...
        'Saved bracket lambdas do not match the frozen design contract.');
end
xB=B.initial_state(:,1); xC=C.initial_state(:,1);
if numel(xB)~=cfg.grid.N || max(abs(xB-xC))>1e-12 || ...
        abs(xB(1))>1e-12 || abs(xB(end)-cfg.grid.Lx)>1e-12
    error('build_ml_BC_boundary_geometry:BracketGridMismatch', ...
        'B and C bracket states do not share the declared spatial grid.');
end

UB=B.initial_state(:,2)'; VB=B.initial_state(:,3)';
UC=C.initial_state(:,2)'; VC=C.initial_state(:,3)';
[direct_distance,reflected_distance] = distance_components( ...
    UB,VB,UC,VC,cfg.grid.Lx);
align_C_by_reflection = reflected_distance<direct_distance;
if align_C_by_reflection
    UCa=fliplr(UC); VCa=fliplr(VC);
else
    UCa=UC; VCa=VC;
end
raw_U=0.5*(UB+UCa); raw_V=0.5*(VB+VCa);
orientation=brusselator_reflection_canonicalize(raw_U,raw_V,cfg.grid.Lx);
center=struct('x',xB,'raw_U',raw_U,'raw_V',raw_V, ...
    'reflected_U',fliplr(raw_U),'reflected_V',fliplr(raw_V), ...
    'canonical_U',orientation.canonical_U, ...
    'canonical_V',orientation.canonical_V, ...
    'uses_reflection',orientation.uses_reflection, ...
    'selected_feature_index',orientation.selected_feature_index, ...
    'selected_feature_value',orientation.selected_feature_value, ...
    'rule',cfg.ml_boundary.center.rule);
bracket=struct('B',struct('lambda',B.lambda,'label','B', ...
        'initial_state',B.initial_state,'U',UB,'V',VB, ...
        'decision_time',B.decision_time), ...
    'C',struct('lambda',C.summary.lambda,'label','C', ...
        'initial_state',C.initial_state,'U',UCa,'V',VCa, ...
        'decision_time',C.summary.decision_time), ...
    'C_alignment_uses_reflection',align_C_by_reflection, ...
    'direct_distance',direct_distance, ...
    'reflected_distance',reflected_distance, ...
    'construction_note',['labels validate the two source endpoints; no ', ...
        'endpoint label is inherited by a state generated in the POD plane']);
end

function [basis,model] = decode_basis(stage2,cfg)
model=stage2.landing_aware_pod.model;
components=cfg.ml_boundary.basis.components;
N=cfg.grid.N;
sqrt_w=model.sqrt_spatial_weights(:);
modes=model.modes(:,components);
physical_U=modes(1:N,:).*model.scale_U./sqrt_w;
physical_V=modes(N+1:end,:).*model.scale_V./sqrt_w;
scaled_gram=modes'*modes;
w=model.spatial_weights(:);
physical_gram=physical_U'*(physical_U.*w)+physical_V'*(physical_V.*w);
basis=struct('components',components,'physical_U',physical_U, ...
    'physical_V',physical_V,'scaled_modes',modes, ...
    'scaled_gram',scaled_gram,'physical_gram',physical_gram, ...
    'scaled_orthonormality_error',norm(scaled_gram-eye(numel(components)),'fro'), ...
    'explained_percent',model.explained_percent(components), ...
    'decode_rule',cfg.ml_boundary.basis.decode_rule, ...
    'distance_interpretation',cfg.ml_boundary.basis.distance_interpretation);
if basis.scaled_orthonormality_error>1e-10
    error('build_ml_BC_boundary_geometry:BasisNotOrthonormal', ...
        'Selected POD modes are not orthonormal in the saved scaled geometry.');
end
end

function [bounds,records] = derive_bounds(stage2,center,basis,model,cfg)
landing=stage2.landing_records;
labels={landing.final_label}; statuses={landing.label_status};
selected=strcmp(labels,cfg.ml_boundary.bounds.source_final_label) & ...
    strcmp(statuses,cfg.ml_boundary.bounds.source_label_status);
if sum(selected)<4
    error('build_ml_BC_boundary_geometry:InsufficientBoundSources', ...
        'At least four validated B landings are required to define the bounds.');
end
scores=stage2.landing_aware_pod.landing_scores(:,basis.components);
source_scores=scores(selected,:);
unshrunk=0.5*(max(source_scores,[],1)-min(source_scores,[],1))* ...
    cfg.ml_boundary.bounds.padding_factor;
if any(unshrunk<=0)
    error('build_ml_BC_boundary_geometry:DegenerateBounds', ...
        'A selected POD coordinate has zero observed B-landing range.');
end

minimum=cfg.ml_boundary.bounds.minimum_concentration;
factor=maximum_admissible_common_factor(center.canonical_U, ...
    center.canonical_V,basis.physical_U,basis.physical_V,unshrunk, ...
    minimum,cfg.ml_boundary.bounds);
halfwidth=factor*unshrunk;
[minimum_U,minimum_V]=minimum_over_corners(center.canonical_U, ...
    center.canonical_V,basis.physical_U,basis.physical_V,halfwidth);
[center_score,~]=brusselator_project_pod(center.canonical_U, ...
    center.canonical_V,model,max(basis.components));
bounds=struct('source_count',sum(selected), ...
    'source_score_minimum',min(source_scores,[],1), ...
    'source_score_maximum',max(source_scores,[],1), ...
    'source_score_span',max(source_scores,[],1)-min(source_scores,[],1), ...
    'unshrunk_halfwidth',unshrunk,'admissibility_factor',factor, ...
    'halfwidth',halfwidth,'minimum_U_over_rectangle',minimum_U, ...
    'minimum_V_over_rectangle',minimum_V, ...
    'minimum_concentration',minimum,'center_pod_score', ...
    center_score(basis.components),'rule',cfg.ml_boundary.bounds.rule);

indices=find(selected); template=struct('state_index',NaN,'protocol_id','', ...
    'family','','final_label','','label_status','','score_1',NaN,'score_2',NaN);
records=repmat(template,numel(indices),1);
for k=1:numel(indices)
    i=indices(k);
    records(k)=struct('state_index',i,'protocol_id',landing(i).protocol_id, ...
        'family',landing(i).family,'final_label',landing(i).final_label, ...
        'label_status',landing(i).label_status,'score_1',scores(i,1), ...
        'score_2',scores(i,2));
end
end

function factor = maximum_admissible_common_factor(U0,V0,PU,PV,halfwidth,minimum,options)
[minimum_U,minimum_V]=minimum_over_corners(U0,V0,PU,PV,halfwidth);
if minimum_U>=minimum && minimum_V>=minimum
    factor=1;
    return;
end
low=0; high=1;
for k=1:options.maximum_shrink_iterations
    middle=0.5*(low+high);
    [minimum_U,minimum_V]=minimum_over_corners( ...
        U0,V0,PU,PV,middle*halfwidth);
    if minimum_U>=minimum && minimum_V>=minimum
        low=middle;
    else
        high=middle;
    end
    if high-low<options.common_shrink_tolerance
        break;
    end
end
factor=low;
if factor<=0
    error('build_ml_BC_boundary_geometry:InadmissibleCenter', ...
        'No positive sampling rectangle can be formed around the center.');
end
end

function [minimum_U,minimum_V] = minimum_over_corners(U0,V0,PU,PV,halfwidth)
minimum_U=inf; minimum_V=inf;
for sign1=[-1,1]
    for sign2=[-1,1]
        U=U0+sign1*halfwidth(1)*PU(:,1)'+sign2*halfwidth(2)*PU(:,2)';
        V=V0+sign1*halfwidth(1)*PV(:,1)'+sign2*halfwidth(2)*PV(:,2)';
        minimum_U=min(minimum_U,min(U));
        minimum_V=min(minimum_V,min(V));
    end
end
end

function [states,manifest,audit] = build_master_grid(center,basis,bounds,model,cfg)
n=cfg.ml_boundary.design.master_grid_size;
level1=linspace(-bounds.halfwidth(1),bounds.halfwidth(1),n);
level2=linspace(-bounds.halfwidth(2),bounds.halfwidth(2),n);
[alpha1_grid,alpha2_grid]=meshgrid(level1,level2);
alpha1=alpha1_grid(:); alpha2=alpha2_grid(:); count=numel(alpha1);
U=center.canonical_U+alpha1*basis.physical_U(:,1)'+ ...
    alpha2*basis.physical_U(:,2)';
V=center.canonical_V+alpha1*basis.physical_V(:,1)'+ ...
    alpha2*basis.physical_V(:,2)';
orientation=brusselator_reflection_canonicalize(U,V,cfg.grid.Lx);
reflected_orientation=brusselator_reflection_canonicalize( ...
    orientation.reflected_U,orientation.reflected_V,cfg.grid.Lx);

order=serpentine_order(n);
[continuity_U,continuity_V,continuity_flags]=continuity_orientation( ...
    U,V,order,cfg.grid.Lx);
inverse_order=zeros(count,1); inverse_order(order)=1:count;
continuity_U=continuity_U(inverse_order,:);
continuity_V=continuity_V(inverse_order,:);
continuity_flags=continuity_flags(inverse_order);

[scores,~]=brusselator_project_pod(U,V,model,max(basis.components));
[center_score,~]=brusselator_project_pod(center.canonical_U, ...
    center.canonical_V,model,max(basis.components));
coordinate_error=max(abs(scores(:,basis.components)- ...
    center_score(basis.components)-[alpha1,alpha2]),[],2);

template=empty_manifest_record(); manifest=repmat(template,count,1);
w=spatial_weights(cfg.grid.N,cfg.grid.Lx);
for k=1:count
    [row,column]=ind2sub([n,n],k);
    role=design_role(row,column,cfg);
    invariance=direct_relative_distance(orientation.canonical_U(k,:), ...
        orientation.canonical_V(k,:),reflected_orientation.canonical_U(k,:), ...
        reflected_orientation.canonical_V(k,:),w);
    manifest(k)=struct('state_index',k, ...
        'sample_id',sprintf('plane_r%02d_c%02d',row,column), ...
        'row_index',row,'column_index',column,'alpha_1',alpha1(k), ...
        'alpha_2',alpha2(k),'normalized_alpha_1',alpha1(k)/bounds.halfwidth(1), ...
        'normalized_alpha_2',alpha2(k)/bounds.halfwidth(2), ...
        'design_role',role,'simulation_status',cfg.ml_boundary.status.simulation_status, ...
        'outcome_label',cfg.ml_boundary.status.outcome_label, ...
        'minimum_U',min(U(k,:)),'minimum_V',min(V(k,:)), ...
        'physical_distance_from_center',direct_relative_distance(U(k,:),V(k,:), ...
            center.canonical_U,center.canonical_V,w), ...
        'scaled_pod_distance_from_center',hypot(alpha1(k),alpha2(k)), ...
        'coordinate_reprojection_error',coordinate_error(k), ...
        'feature_uses_reflection',orientation.uses_reflection(k), ...
        'feature_index',orientation.selected_feature_index(k), ...
        'feature_value',orientation.selected_feature_value(k), ...
        'reflection_invariance_error',invariance, ...
        'serpentine_rank',inverse_order(k), ...
        'continuity_uses_reflection',continuity_flags(k));
end
if min([manifest.minimum_U])<cfg.ml_boundary.bounds.minimum_concentration || ...
        min([manifest.minimum_V])<cfg.ml_boundary.bounds.minimum_concentration
    error('build_ml_BC_boundary_geometry:PositivityGateFailed', ...
        'At least one generated state violates the concentration gate.');
end
if max([manifest.reflection_invariance_error])> ...
        cfg.ml_boundary.reflection.invariance_tolerance
    error('build_ml_BC_boundary_geometry:ReflectionGateFailed', ...
        'Raw/reflected feature canonicalizations disagree beyond tolerance.');
end
if max(coordinate_error)>1e-10
    error('build_ml_BC_boundary_geometry:CoordinateGateFailed', ...
        'Generated states do not reproject to their declared POD coordinates.');
end

states=struct('raw_U',U,'raw_V',V, ...
    'reflected_U',orientation.reflected_U,'reflected_V',orientation.reflected_V, ...
    'feature_canonical_U',orientation.canonical_U, ...
    'feature_canonical_V',orientation.canonical_V, ...
    'serpentine_continuity_U',continuity_U, ...
    'serpentine_continuity_V',continuity_V, ...
    'alpha_1_grid',alpha1_grid,'alpha_2_grid',alpha2_grid, ...
    'serpentine_order',order);
audit=reflection_continuity_records(orientation,continuity_U,continuity_V, ...
    continuity_flags,order,cfg);
end

function role = design_role(row,column,cfg)
seed=cfg.ml_boundary.design.initial_seed_indices;
test=cfg.ml_boundary.design.fixed_test_indices;
if ismember(row,seed) && ismember(column,seed)
    role='initial_seed';
elseif ismember(row,test) && ismember(column,test)
    role='fixed_test';
else
    role='acquisition_pool';
end
end

function order = serpentine_order(n)
order=zeros(n*n,1); cursor=0;
for row=1:n
    if mod(row,2)==1, columns=1:n; else, columns=n:-1:1; end
    for column=columns
        cursor=cursor+1;
        order(cursor)=sub2ind([n,n],row,column);
    end
end
end

function [oriented_U,oriented_V,flags] = continuity_orientation(U,V,order,Lx)
count=numel(order); oriented_U=zeros(size(U)); oriented_V=zeros(size(V));
flags=false(count,1);
first=order(1);
first_orientation=brusselator_reflection_canonicalize(U(first,:),V(first,:),Lx);
oriented_U(1,:)=first_orientation.canonical_U;
oriented_V(1,:)=first_orientation.canonical_V;
flags(1)=first_orientation.uses_reflection;
w=spatial_weights(size(U,2),Lx);
for rank=2:count
    current=order(rank);
    direct=direct_relative_distance(U(current,:),V(current,:), ...
        oriented_U(rank-1,:),oriented_V(rank-1,:),w);
    reflected=direct_relative_distance(fliplr(U(current,:)),fliplr(V(current,:)), ...
        oriented_U(rank-1,:),oriented_V(rank-1,:),w);
    if reflected<direct
        oriented_U(rank,:)=fliplr(U(current,:));
        oriented_V(rank,:)=fliplr(V(current,:)); flags(rank)=true;
    else
        oriented_U(rank,:)=U(current,:);
        oriented_V(rank,:)=V(current,:);
    end
end
end

function records = reflection_continuity_records(orientation,continuity_U, ...
        continuity_V,continuity_flags,order,cfg)
count=numel(order); w=spatial_weights(cfg.grid.N,cfg.grid.Lx);
template=struct('serpentine_rank',NaN,'state_index',NaN, ...
    'feature_step_distance',NaN,'continuity_step_distance',NaN, ...
    'feature_uses_reflection',false,'continuity_uses_reflection',false, ...
    'orientation_disagreement',false);
records=repmat(template,count,1);
for rank=1:count
    current=order(rank);
    if rank==1
        feature_step=NaN; continuity_step=NaN;
    else
        previous=order(rank-1);
        feature_step=direct_relative_distance(orientation.canonical_U(current,:), ...
            orientation.canonical_V(current,:),orientation.canonical_U(previous,:), ...
            orientation.canonical_V(previous,:),w);
        continuity_step=direct_relative_distance(continuity_U(current,:), ...
            continuity_V(current,:),continuity_U(previous,:), ...
            continuity_V(previous,:),w);
    end
    records(rank)=struct('serpentine_rank',rank,'state_index',current, ...
        'feature_step_distance',feature_step, ...
        'continuity_step_distance',continuity_step, ...
        'feature_uses_reflection',orientation.uses_reflection(current), ...
        'continuity_uses_reflection',continuity_flags(current), ...
        'orientation_disagreement',direct_relative_distance( ...
            orientation.canonical_U(current,:),orientation.canonical_V(current,:), ...
            continuity_U(current,:),continuity_V(current,:),w)>1e-12);
end
end

function records = audit_bracket_projection(bracket,center,basis,model,cfg)
template=struct('label','','lambda',NaN,'alpha_1_projection',NaN, ...
    'alpha_2_projection',NaN,'scaled_delta_norm',NaN, ...
    'scaled_projection_norm',NaN,'scaled_retained_fraction',NaN, ...
    'scaled_residual_norm',NaN,'physical_distance_from_center',NaN, ...
    'physical_projection_residual',NaN,'inherited_plane_label',false);
records=repmat(template,2,1); w=spatial_weights(cfg.grid.N,cfg.grid.Lx);
[center_score,~]=brusselator_project_pod(center.canonical_U, ...
    center.canonical_V,model,max(basis.components));
items={bracket.B,bracket.C};
for k=1:2
    item=items{k};
    [score,~]=brusselator_project_pod(item.U,item.V,model,max(basis.components));
    alpha=score(basis.components)-center_score(basis.components);
    scaled_delta=[((item.U-center.canonical_U).*model.sqrt_spatial_weights)/model.scale_U, ...
        ((item.V-center.canonical_V).*model.sqrt_spatial_weights)/model.scale_V];
    scaled_projection=alpha*basis.scaled_modes';
    projected_U=center.canonical_U+alpha(1)*basis.physical_U(:,1)'+ ...
        alpha(2)*basis.physical_U(:,2)';
    projected_V=center.canonical_V+alpha(1)*basis.physical_V(:,1)'+ ...
        alpha(2)*basis.physical_V(:,2)';
    records(k)=struct('label',item.label,'lambda',item.lambda, ...
        'alpha_1_projection',alpha(1),'alpha_2_projection',alpha(2), ...
        'scaled_delta_norm',norm(scaled_delta), ...
        'scaled_projection_norm',norm(scaled_projection), ...
        'scaled_retained_fraction',norm(scaled_projection)/max(norm(scaled_delta),eps), ...
        'scaled_residual_norm',norm(scaled_delta-scaled_projection), ...
        'physical_distance_from_center',direct_relative_distance(item.U,item.V, ...
            center.canonical_U,center.canonical_V,w), ...
        'physical_projection_residual',direct_relative_distance(item.U,item.V, ...
            projected_U,projected_V,w), ...
        'inherited_plane_label',false);
end
end

function records = collect_source_provenance(cfg)
names={'stage2_file','B_bracket_file','C_bracket_file'};
template=struct('source_name','','path','','bytes',NaN,'modified','');
records=repmat(template,numel(names),1);
for k=1:numel(names)
    path=cfg.ml_boundary.sources.(names{k}); info=dir(path);
    records(k)=struct('source_name',names{k},'path',path, ...
        'bytes',info.bytes,'modified',char(datetime(info.datenum, ...
            'ConvertFrom','datenum','Format','yyyy-MM-dd HH:mm:ss')));
end
end

function summary = make_summary(stage2,bracket,center,basis,bounds,manifest, ...
        reflection_audit,bracket_projection,cfg)
roles={manifest.design_role};
feature_steps=[reflection_audit.feature_step_distance];
continuity_steps=[reflection_audit.continuity_step_distance];
valid=isfinite(feature_steps) & isfinite(continuity_steps);
summary=struct( ...
    'geometry_id',sprintf('%s_N%d_Lx%g_PC%d_PC%d',cfg.experiment_name, ...
        cfg.grid.N,cfg.grid.Lx,basis.components(1),basis.components(2)), ...
    'state_count',numel(manifest), ...
    'initial_seed_count',sum(strcmp(roles,'initial_seed')), ...
    'fixed_test_count',sum(strcmp(roles,'fixed_test')), ...
    'acquisition_pool_count',sum(strcmp(roles,'acquisition_pool')), ...
    'alpha_1_halfwidth',bounds.halfwidth(1), ...
    'alpha_2_halfwidth',bounds.halfwidth(2), ...
    'admissibility_factor',bounds.admissibility_factor, ...
    'minimum_U',min([manifest.minimum_U]), ...
    'minimum_V',min([manifest.minimum_V]), ...
    'maximum_coordinate_reprojection_error', ...
        max([manifest.coordinate_reprojection_error]), ...
    'maximum_reflection_invariance_error', ...
        max([manifest.reflection_invariance_error]), ...
    'maximum_feature_to_continuity_step_ratio', ...
        max(feature_steps(valid)./max(continuity_steps(valid),eps)), ...
    'B_C_bracket_relative_distance', ...
        min(bracket.direct_distance,bracket.reflected_distance), ...
    'minimum_bracket_displacement_retained_fraction', ...
        min([bracket_projection.scaled_retained_fraction]), ...
    'landing_aware_PC1_explained_percent',basis.explained_percent(1), ...
    'landing_aware_PC2_explained_percent',basis.explained_percent(2), ...
    'landing_aware_two_mode_total_explained_percent',sum(basis.explained_percent), ...
    'stage2_landing_aware_triggered',stage2.landing_aware_pod.triggered, ...
    'center_uses_reflection',center.uses_reflection, ...
    'exact_edge_used_for_construction',false, ...
    'held_out_CA_region_used_for_construction',false, ...
    'simulation_count',sum(~strcmp({manifest.simulation_status},'not_run')), ...
    'interpretation',['frozen two-dimensional candidate-state geometry; ', ...
        'outcomes and a learned separator remain to be computed']);
end

function records = basis_summary(basis,model)
template=struct('plane_coordinate',NaN,'source_POD_component',NaN, ...
    'explained_percent',NaN,'scaled_norm',NaN,'physical_norm',NaN, ...
    'minimum_U_component',NaN,'maximum_U_component',NaN, ...
    'minimum_V_component',NaN,'maximum_V_component',NaN, ...
    'scale_U',NaN,'scale_V',NaN);
records=repmat(template,2,1); w=model.spatial_weights(:);
for k=1:2
    U=basis.physical_U(:,k); V=basis.physical_V(:,k);
    records(k)=struct('plane_coordinate',k, ...
        'source_POD_component',basis.components(k), ...
        'explained_percent',basis.explained_percent(k), ...
        'scaled_norm',norm(basis.scaled_modes(:,k)), ...
        'physical_norm',sqrt(sum((U.^2+V.^2).*w)), ...
        'minimum_U_component',min(U),'maximum_U_component',max(U), ...
        'minimum_V_component',min(V),'maximum_V_component',max(V), ...
        'scale_U',model.scale_U,'scale_V',model.scale_V);
end
end

function make_figure(outdir,manifest,bounds,bracket_projection,cfg)
visible='off'; fig=figure('Visible',visible,'Color','w','Position',[100,100,1450,470]);
tiledlayout(1,3,'TileSpacing','compact','Padding','compact');
ax=nexttile; hold(ax,'on');
roles={'acquisition_pool','fixed_test','initial_seed'};
colors=[0.75 0.75 0.75; 0.85 0.33 0.10; 0 0.45 0.74];
sizes=[16,42,42];
for k=1:numel(roles)
    selected=strcmp({manifest.design_role},roles{k});
    scatter(ax,[manifest(selected).alpha_1],[manifest(selected).alpha_2], ...
        sizes(k),colors(k,:),'filled','DisplayName',strrep(roles{k},'_',' '));
end
xline(ax,0,':','HandleVisibility','off');
yline(ax,0,':','HandleVisibility','off'); axis(ax,'equal'); grid(ax,'on');
xlim(ax,1.08*[-bounds.halfwidth(1),bounds.halfwidth(1)]);
ylim(ax,1.08*[-bounds.halfwidth(2),bounds.halfwidth(2)]);
xlabel(ax,'\alpha_1 (scaled POD coordinate)');
ylabel(ax,'\alpha_2 (scaled POD coordinate)');
title(ax,'Frozen sampling design (labels not run)'); legend(ax,'Location','best');

ax=nexttile; hold(ax,'on');
projection_1=[bracket_projection.alpha_1_projection];
projection_2=[bracket_projection.alpha_2_projection];
projection_1_plot=projection_1/1e-5;
projection_2_plot=projection_2/1e-4;
plot(ax,projection_1_plot,projection_2_plot,'k-', ...
    'LineWidth',1.2,'HandleVisibility','off');
plot(ax,projection_1_plot(1),projection_2_plot(1),'v','MarkerSize',9, ...
    'MarkerFaceColor',[0 0.45 0.74],'MarkerEdgeColor','k','DisplayName','source B');
plot(ax,projection_1_plot(2),projection_2_plot(2),'^','MarkerSize',9, ...
    'MarkerFaceColor',[0.85 0.33 0.10],'MarkerEdgeColor','k','DisplayName','source C');
plot(ax,0,0,'ko','MarkerFaceColor','k','MarkerSize',5,'DisplayName','midpoint');
xline(ax,0,':','HandleVisibility','off');
yline(ax,0,':','HandleVisibility','off'); grid(ax,'on');
margin_1=max(abs(projection_1_plot))*1.8;
margin_2=max(abs(projection_2_plot))*1.25;
xlim(ax,[-margin_1,margin_1]); ylim(ax,[-margin_2,margin_2]);
xlabel(ax,'\alpha_1 / 10^{-5}'); ylabel(ax,'\alpha_2 / 10^{-4}');
title(ax,'Known bracket projection (independent axis scales)');
legend(ax,'Location','best');

ax=nexttile; hold(ax,'on');
scatter(ax,[manifest.alpha_1],[manifest.alpha_2],30, ...
    double([manifest.feature_uses_reflection]),'filled');
colormap(ax,[0.2 0.6 0.8; 0.8 0.3 0.2]); clim(ax,[0,1]);
colorbar(ax,'Ticks',[0.25,0.75],'TickLabels',{'raw','reflected'});
xline(ax,0,':','HandleVisibility','off');
yline(ax,0,':','HandleVisibility','off'); axis(ax,'equal'); grid(ax,'on');
xlim(ax,1.08*[-bounds.halfwidth(1),bounds.halfwidth(1)]);
ylim(ax,1.08*[-bounds.halfwidth(2),bounds.halfwidth(2)]);
xlabel(ax,'\alpha_1'); ylabel(ax,'\alpha_2');
title(ax,'Feature-canonical orientation audit');
sgtitle(fig,['ML B--C geometry at b=',num2str(cfg.ml_boundary.scope.frozen_b), ...
    ': exact edge excluded from construction']);
exportgraphics(fig,fullfile(outdir,'sampling_plane_and_reflection_audit.png'), ...
    'Resolution',300); close(fig);
end

function record = empty_manifest_record()
record=struct('state_index',NaN,'sample_id','','row_index',NaN, ...
    'column_index',NaN,'alpha_1',NaN,'alpha_2',NaN, ...
    'normalized_alpha_1',NaN,'normalized_alpha_2',NaN, ...
    'design_role','','simulation_status','','outcome_label','', ...
    'minimum_U',NaN,'minimum_V',NaN,'physical_distance_from_center',NaN, ...
    'scaled_pod_distance_from_center',NaN, ...
    'coordinate_reprojection_error',NaN,'feature_uses_reflection',false, ...
    'feature_index',NaN,'feature_value',NaN, ...
    'reflection_invariance_error',NaN,'serpentine_rank',NaN, ...
    'continuity_uses_reflection',false);
end

function w = spatial_weights(N,Lx)
w=(Lx/(N-1))*ones(1,N); w([1,end])=0.5*w(1);
end

function [direct,reflected] = distance_components(UA,VA,UB,VB,Lx)
w=spatial_weights(numel(UA),Lx);
energy_A=sum((UA.^2+VA.^2).*w); energy_B=sum((UB.^2+VB.^2).*w);
denominator=max(0.5*(energy_A+energy_B),eps);
direct=sqrt(sum(((UA-UB).^2+(VA-VB).^2).*w)/denominator);
reflected=sqrt(sum(((UA-fliplr(UB)).^2+(VA-fliplr(VB)).^2).*w)/denominator);
end

function value = direct_relative_distance(UA,VA,UB,VB,w)
energy_A=sum((UA.^2+VA.^2).*w); energy_B=sum((UB.^2+VB.^2).*w);
value=sqrt(sum(((UA-UB).^2+(VA-VB).^2).*w)/ ...
    max(0.5*(energy_A+energy_B),eps));
end
