function results = build_ml_BC_transfer_geometry()
%BUILD_ML_BC_TRANSFER_GEOMETRY Build a frozen physical-chord transfer ribbon.

timer = tic;
cfg = brusselator_ml_BC_transfer_geometry_config();
outdir = fullfile(cfg.output.root,cfg.experiment_name);
if isfolder(outdir)
    error('build_ml_BC_transfer_geometry:OutputExists', ...
        'Refusing to overwrite frozen transfer geometry: %s',outdir);
end

[B,C] = load_sources(cfg);
stage = load(cfg.ml_transfer.sources.stage2_file,'results');
model = stage.results.landing_aware_pod.model;
[center,basis,audit] = construct_basis(B,C,model,cfg);
[states,manifest,summary] = construct_grid(center,basis,audit,cfg);

mkdir(outdir);
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,NaN));
writetable(struct2table(manifest,'AsArray',true), ...
    fullfile(outdir,'transfer_state_manifest.csv'));
writetable(struct2table(audit,'AsArray',true), ...
    fullfile(outdir,'transfer_basis_audit.csv'));
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'transfer_geometry_summary.csv'));
make_figure(outdir,manifest,cfg);

results = struct('configuration',cfg,'center',center,'basis',basis, ...
    'states',states,'manifest',manifest,'audit',audit,'summary',summary);
save(fullfile(outdir,'ml_BC_transfer_geometry.mat'),'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,toc(timer)));
disp(struct2table(summary,'AsArray',true));
fprintf('Frozen prospective transfer geometry saved in: %s\n',outdir);
end

function [B,C] = load_sources(cfg)
required = {cfg.ml_transfer.sources.B_file, ...
    cfg.ml_transfer.sources.C_file,cfg.ml_transfer.sources.stage2_file};
if ~all(cellfun(@isfile,required))
    error('build_ml_BC_transfer_geometry:MissingSource', ...
        'A declared physical-chord or POD source is missing.');
end
left = load(cfg.ml_transfer.sources.B_file, ...
    cfg.ml_transfer.sources.B_variable);
right = load(cfg.ml_transfer.sources.C_file, ...
    cfg.ml_transfer.sources.C_variable);
B = left.(cfg.ml_transfer.sources.B_variable);
C = right.(cfg.ml_transfer.sources.C_variable);
if ~strcmp(B.classification.outcome,cfg.ml_transfer.sources.required_B_outcome) || ...
        ~strcmp(C.classification.outcome,cfg.ml_transfer.sources.required_C_outcome)
    error('build_ml_BC_transfer_geometry:EndpointLabels', ...
        'The physical-chord sources are not the frozen B/C endpoints.');
end
if ~isequal(size(B.initial_state),[cfg.grid.N,3]) || ...
        ~isequal(size(C.initial_state),[cfg.grid.N,3]) || ...
        max(abs(B.initial_state(:,1)-C.initial_state(:,1)))>1e-12
    error('build_ml_BC_transfer_geometry:GridMismatch', ...
        'Physical-chord sources do not share the declared grid.');
end
end

function [center,basis,audit] = construct_basis(B,C,model,cfg)
N = cfg.grid.N;
if numel(model.mean_U)~=N || size(model.modes,1)~=2*N
    error('build_ml_BC_transfer_geometry:PODGridMismatch', ...
        'Landing-aware POD model does not use N=%d.',N);
end
x = B.initial_state(:,1);
UB = B.initial_state(:,2)'; VB = B.initial_state(:,3)';
UC = C.initial_state(:,2)'; VC = C.initial_state(:,3)';
w = model.spatial_weights(:); sqrt_w = sqrt(w);
delta_scaled = [sqrt_w.*(UC-UB)'./model.scale_U; ...
    sqrt_w.*(VC-VB)'./model.scale_V];
chord_length = norm(delta_scaled);
if ~isfinite(chord_length) || chord_length<=0
    error('build_ml_BC_transfer_geometry:DegenerateChord', ...
        'The physical B/C displacement is degenerate.');
end
e1 = delta_scaled/chord_length;
component = cfg.ml_transfer.basis.transverse_pod_component;
raw_e2 = model.modes(:,component);
e2_residual = raw_e2-e1*(e1'*raw_e2);
residual_norm = norm(e2_residual);
if residual_norm<cfg.ml_transfer.basis.minimum_transverse_residual_norm
    error('build_ml_BC_transfer_geometry:TransverseDegenerate', ...
        'POD%d is too aligned with the physical chord.',component);
end
e2 = e2_residual/residual_norm;
old = model.modes(:,1:2);
new = [e1,e2];
projector_difference = norm(new*new'-old*old','fro');
if projector_difference < ...
        cfg.ml_transfer.basis.minimum_subspace_projector_difference_from_PC1_PC2
    error('build_ml_BC_transfer_geometry:NotIndependentFamily', ...
        'The transfer plane is insufficiently distinct from PC1--PC2.');
end
physical_U = [e1(1:N),e2(1:N)].*model.scale_U./sqrt_w;
physical_V = [e1(N+1:end),e2(N+1:end)].*model.scale_V./sqrt_w;
center = struct('x',x,'raw_U',0.5*(UB+UC),'raw_V',0.5*(VB+VC), ...
    'B_U',UB,'B_V',VB,'C_U',UC,'C_V',VC);
basis = struct('scaled_modes',new,'physical_U',physical_U, ...
    'physical_V',physical_V,'chord_length',chord_length, ...
    'longitudinal_halfwidth', ...
        cfg.ml_transfer.bounds.longitudinal_halfwidth_in_chord_lengths*chord_length, ...
    'transverse_halfwidth', ...
        cfg.ml_transfer.bounds.transverse_halfwidth_in_chord_lengths*chord_length, ...
    'transverse_pod_component',component);
audit = struct('chord_scaled_length',chord_length, ...
    'basis_orthogonality_error',abs(e1'*e2), ...
    'transverse_residual_norm',residual_norm, ...
    'projector_difference_from_PC1_PC2',projector_difference, ...
    'B_anchor_normalized_coordinate',-0.75, ...
    'C_anchor_normalized_coordinate',0.75, ...
    'direct_BC_physical_distance',physical_distance(UB,VB,UC,VC,w), ...
    'reflected_BC_physical_distance', ...
        physical_distance(UB,VB,fliplr(UC),fliplr(VC),w), ...
    'exact_edge_orbit_used',false,'candidate_labels_used',false);
end

function [states,manifest,summary] = construct_grid(center,basis,audit,cfg)
n = cfg.ml_transfer.design.master_grid_size;
coordinates = linspace(-1,1,n);
count = n*n; N = cfg.grid.N;
raw_U = zeros(count,N); raw_V = zeros(count,N);
template = struct('state_index',NaN,'sample_id','', ...
    'row_index',NaN,'column_index',NaN,'alpha_1',NaN,'alpha_2',NaN, ...
    'normalized_alpha_1',NaN,'normalized_alpha_2',NaN, ...
    'design_role','','is_B_source_anchor',false,'is_C_source_anchor',false, ...
    'simulation_status',cfg.ml_transfer.status.simulation_status, ...
    'outcome_label',cfg.ml_transfer.status.outcome_label, ...
    'minimum_U',NaN,'minimum_V',NaN);
manifest = repmat(template,count,1);
initial_rows = cfg.ml_transfer.design.initial_row_indices;
initial_columns = cfg.ml_transfer.design.initial_column_indices;
index = 0;
for row = 1:n
    for column = 1:n
        index = index+1;
        a1 = coordinates(column); a2 = coordinates(row);
        U = center.raw_U + a1*basis.longitudinal_halfwidth* ...
            basis.physical_U(:,1)' + a2*basis.transverse_halfwidth* ...
            basis.physical_U(:,2)';
        V = center.raw_V + a1*basis.longitudinal_halfwidth* ...
            basis.physical_V(:,1)' + a2*basis.transverse_halfwidth* ...
            basis.physical_V(:,2)';
        raw_U(index,:) = U; raw_V(index,:) = V;
        initial = ismember(row,initial_rows) && ismember(column,initial_columns);
        role = 'acquisition_pool'; if initial,role='initial_seed';end
        manifest(index) = struct('state_index',index, ...
            'sample_id',sprintf('transfer_state_%03d',index), ...
            'row_index',row,'column_index',column,'alpha_1',a1, ...
            'alpha_2',a2,'normalized_alpha_1',a1, ...
            'normalized_alpha_2',a2,'design_role',role, ...
            'is_B_source_anchor',row==cfg.ml_transfer.design.B_anchor_row && ...
                column==cfg.ml_transfer.design.B_anchor_column, ...
            'is_C_source_anchor',row==cfg.ml_transfer.design.C_anchor_row && ...
                column==cfg.ml_transfer.design.C_anchor_column, ...
            'simulation_status',cfg.ml_transfer.status.simulation_status, ...
            'outcome_label',cfg.ml_transfer.status.outcome_label, ...
            'minimum_U',min(U),'minimum_V',min(V));
    end
end
minimum_U = min(raw_U,[],'all'); minimum_V = min(raw_V,[],'all');
if min(minimum_U,minimum_V)<=cfg.ml_transfer.bounds.minimum_concentration
    error('build_ml_BC_transfer_geometry:PositivityGate', ...
        'The frozen transfer ribbon violates the concentration gate.');
end
initial_count = sum(strcmp({manifest.design_role},'initial_seed'));
if initial_count~=cfg.ml_transfer.design.expected_initial_count
    error('build_ml_BC_transfer_geometry:InitialCount', ...
        'The fixed initial design no longer contains 15 states.');
end
B_index = find([manifest.is_B_source_anchor]);
C_index = find([manifest.is_C_source_anchor]);
if max(abs(raw_U(B_index,:)-center.B_U))>1e-10 || ...
        max(abs(raw_V(B_index,:)-center.B_V))>1e-10 || ...
        max(abs(raw_U(C_index,:)-center.C_U))>1e-10 || ...
        max(abs(raw_V(C_index,:)-center.C_V))>1e-10
    error('build_ml_BC_transfer_geometry:AnchorReconstruction', ...
        'The declared grid anchors do not reproduce the physical B/C sources.');
end
states = struct('raw_U',raw_U,'raw_V',raw_V);
summary = struct('geometry_id', ...
    'ml_BC_transfer_geometry_v1_N400_Lx40_physical_chord_POD3', ...
    'state_count',count,'grid_rows',n,'grid_columns',n, ...
    'initial_seed_count',initial_count,'acquisition_pool_count',count-initial_count, ...
    'B_anchor_state_index',B_index,'C_anchor_state_index',C_index, ...
    'minimum_U',minimum_U,'minimum_V',minimum_V, ...
    'chord_scaled_length',audit.chord_scaled_length, ...
    'projector_difference_from_PC1_PC2', ...
        audit.projector_difference_from_PC1_PC2, ...
    'candidate_outcomes_used',false,'exact_edge_orbit_used',false, ...
    'claim_scope',cfg.ml_transfer.scope.interpretation);
end

function value = physical_distance(U1,V1,U2,V2,w)
value = sqrt(sum(w'.*((U1-U2).^2+(V1-V2).^2)));
end

function make_figure(outdir,manifest,cfg)
fig = figure('Visible','off','Color','w'); hold on;
pool = strcmp({manifest.design_role},'acquisition_pool');
seed = strcmp({manifest.design_role},'initial_seed');
scatter([manifest(pool).normalized_alpha_1], ...
    [manifest(pool).normalized_alpha_2],18,[.75 .75 .75],'filled');
scatter([manifest(seed).normalized_alpha_1], ...
    [manifest(seed).normalized_alpha_2],55,[0 .45 .74],'filled');
B = [manifest.is_B_source_anchor]; C = [manifest.is_C_source_anchor];
scatter([manifest(B).normalized_alpha_1],[manifest(B).normalized_alpha_2], ...
    100,[.84 .37 0],'p','filled');
scatter([manifest(C).normalized_alpha_1],[manifest(C).normalized_alpha_2], ...
    100,[.90 .62 0],'p','filled');
xlabel('normalized physical-chord coordinate');
ylabel(sprintf('normalized POD%d transverse coordinate', ...
    cfg.ml_transfer.basis.transverse_pod_component));
title('Frozen prospective transfer family and 15-state initial design');
axis equal; xlim([-1.05 1.05]); ylim([-1.05 1.05]); grid on;
exportgraphics(fig,fullfile(outdir,'transfer_geometry.png'),'Resolution',250);
close(fig);
end
