function results = build_ml_heldout_CBA_geometry()
%BUILD_ML_HELDOUT_CBA_GEOMETRY Freeze an outcome-free fine challenge grid.

cfg=brusselator_ml_heldout_CBA_geometry_config();
outdir=fullfile(cfg.output.root,cfg.experiment_name);
final_file=fullfile(outdir,'ml_heldout_CBA_geometry.mat');
if isfolder(outdir)
    error('build_ml_heldout_CBA_geometry:OutputExists', ...
        'Refusing to overwrite frozen held-out geometry: %s',outdir);
end
required={cfg.heldout.parent_edge_file,cfg.heldout.coarse_training_csv};
if ~all(cellfun(@isfile,required))
    error('build_ml_heldout_CBA_geometry:MissingSource', ...
        'Parent endpoint or coarse training source is missing.');
end

parent_loaded=load(cfg.heldout.parent_edge_file,'results');
parent=parent_loaded.results;
if parent.configuration.grid.N~=cfg.grid.N || ...
        parent.configuration.grid.Lx~=cfg.grid.Lx
    error('build_ml_heldout_CBA_geometry:GridMismatch', ...
        'Parent endpoints do not match the configured grid.');
end
coarse=readtable(cfg.heldout.coarse_training_csv,'TextType','string');
if any(~ismember(coarse.outcome,["A","B","C"]))
    error('build_ml_heldout_CBA_geometry:TrainingTaxonomy', ...
        'The allowed coarse training scan contains a non-A/B/C outcome.');
end

lambda_grid=linspace(cfg.heldout.lambda_minimum, ...
    cfg.heldout.lambda_maximum,cfg.heldout.grid_subintervals+1)';
known_coordinates=unique([cfg.heldout.lambda_minimum; ...
    cfg.heldout.lambda_maximum; ...
    cfg.heldout.previously_simulated_interior_lambdas(:)]);
is_known=false(size(lambda_grid));
for k=1:numel(known_coordinates)
    is_known=is_known | abs(lambda_grid-known_coordinates(k))< ...
        cfg.heldout.coordinate_tolerance;
end
candidate_lambda=lambda_grid(~is_known);
candidate_grid_index=find(~is_known)-1;
n=numel(candidate_lambda);N=cfg.grid.N;
raw_U=zeros(n,N);raw_V=zeros(n,N);
for k=1:n
    state=(1-candidate_lambda(k))*parent.endpoint_B + ...
        candidate_lambda(k)*parent.endpoint_A;
    raw_U(k,:)=state(:,2)';raw_V(k,:)=state(:,3)';
end
if any(raw_U(:)<=0)||any(raw_V(:)<=0)
    error('build_ml_heldout_CBA_geometry:Positivity', ...
        'At least one held-out candidate violates positivity.');
end

state_index=(1:n)';
sample_id=arrayfun(@(index)sprintf('heldout_cba_g%03d',index), ...
    candidate_grid_index,'UniformOutput',false);
normalized_coordinate=(candidate_lambda-cfg.heldout.lambda_minimum)/ ...
    (cfg.heldout.lambda_maximum-cfg.heldout.lambda_minimum);
design_role=repmat("heldout_candidate",n,1);
previously_simulated=false(n,1);outcome_available_to_acquisition=false(n,1);
candidate_manifest=table(state_index,candidate_grid_index,candidate_lambda, ...
    normalized_coordinate,sample_id,design_role,previously_simulated, ...
    outcome_available_to_acquisition,'VariableNames', ...
    {'state_index','grid_index','lambda','normalized_coordinate','sample_id', ...
    'design_role','previously_simulated','outcome_available_to_acquisition'});

training_labels=coarse(:,{'scan_index','lambda','outcome','source_type'});
training_labels.Properties.VariableNames{'outcome'}='final_label';
training_labels.normalized_coordinate=(training_labels.lambda- ...
    cfg.heldout.lambda_minimum)/(cfg.heldout.lambda_maximum- ...
    cfg.heldout.lambda_minimum);
training_labels.inside_challenge_interval=training_labels.lambda>= ...
    cfg.heldout.lambda_minimum & training_labels.lambda<= ...
    cfg.heldout.lambda_maximum;
training_labels.outcome_source=repmat("coarse_scan_only",height(training_labels),1);

exclusion_kind=["coarse_training_endpoint"; ...
    repmat("previously_simulated_interior_outcome_not_loaded", ...
    numel(known_coordinates)-2,1);"coarse_training_endpoint"];
excluded_coordinates=table(known_coordinates,exclusion_kind, ...
    'VariableNames',{'lambda','exclusion_kind'});

mkdir(outdir);
writetable(candidate_manifest,fullfile(outdir,'heldout_candidate_manifest.csv'));
writetable(training_labels,fullfile(outdir,'allowed_coarse_training_labels.csv'));
writetable(excluded_coordinates,fullfile(outdir,'excluded_known_coordinates.csv'));
states=struct('x',parent.endpoint_B(:,1),'raw_U',raw_U,'raw_V',raw_V);
summary=struct('candidate_count',n,'master_grid_count',numel(lambda_grid), ...
    'excluded_coordinate_count',sum(is_known), ...
    'coarse_training_count',height(training_labels), ...
    'coarse_class_counts',[sum(training_labels.final_label=="A"), ...
        sum(training_labels.final_label=="B"),sum(training_labels.final_label=="C")], ...
    'candidate_outcomes_loaded',false, ...
    'pairwise_refinement_file_read',false, ...
    'held_out_fine_structure_used',false, ...
    'minimum_U',min(raw_U(:)),'minimum_V',min(raw_V(:)), ...
    'interpretation',cfg.heldout.claim_scope);
results=struct('configuration',cfg,'candidate_manifest',candidate_manifest, ...
    'training_labels',training_labels,'excluded_coordinates',excluded_coordinates, ...
    'states',states,'summary',summary);
save(final_file,'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,0));
disp(summary);fprintf('Held-out CBA geometry saved in: %s\n',outdir);
end
