function results = confirm_BC_edge_resolution_borderline_branch()
%CONFIRM_BC_EDGE_RESOLUTION_BORDERLINE_BRANCH Extend the N=200 C branch.
%   The N=200 positive edge branch first satisfies the exact-C classifier at
%   global frozen time 240 with a late median close to the declared threshold.
%   This independent 80-unit continuation checks that the distance continues
%   to decay rather than merely grazing the classification neighborhood.

cfg=brusselator_BC_edge_resolution_config(); cfg.grid.N=200;
cfg.experiment_name='BC_edge_resolution_branch_confirmation_v1';
source_file=fullfile('experiment_outputs','BC_edge_resolution_geometry_v1', ...
    'branches','N0200_sign_plus.mat');
outdir=fullfile(cfg.output.root,cfg.experiment_name);
final_file=fullfile(outdir,'N0200_positive_branch_confirmation.mat');
if isfolder(outdir)
    error('confirm_BC_edge_resolution_borderline_branch:OutputExists', ...
        'Refusing to overwrite existing output: %s',outdir);
end
if ~isfile(source_file)
    error('confirm_BC_edge_resolution_borderline_branch:MissingSource', ...
        'Missing N=200 positive-branch source.');
end
loaded=load(source_file,'edge_case','library');
source=loaded.edge_case; library=loaded.library;
mkdir(outdir); timer=tic;
par=brusselator_make_parameters(cfg,@(t)cfg.edge_tracking.frozen_b);
[final_state,S,V,U]=solve_brusselator_1d_forced( ...
    source.final_state,par,80,0);
[classification,history]=brusselator_classify_five_way_trajectory( ...
    S,U,V,library,'late_window',cfg.edge_tracking.late_window, ...
    'sample_interval',cfg.edge_tracking.distance_sample_interval, ...
    'median_threshold',cfg.edge_tracking.median_distance_threshold, ...
    'maximum_threshold',cfg.edge_tracking.maximum_distance_threshold, ...
    'Lx',cfg.grid.Lx);
summary=struct('status','borderline_branch_extension_complete', ...
    'source_outcome',source.classification.outcome, ...
    'source_end_time',source.duration,'extension_duration',S(end), ...
    'global_end_time',source.duration+S(end), ...
    'extension_outcome',classification.outcome, ...
    'late_median_distance_B',classification.late_median_distances(1), ...
    'late_median_distance_C',classification.late_median_distances(2), ...
    'late_maximum_distance_B',classification.late_maximum_distances(1), ...
    'late_maximum_distance_C',classification.late_maximum_distances(2), ...
    'interpretation',['fixed-horizon confirmation of continued approach to ', ...
        'the exact N=200 C orbit after the first threshold crossing']);
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'confirmation_summary.csv'));
results=struct('configuration',cfg,'source_file',source_file, ...
    'initial_state',source.final_state,'final_state',final_state, ...
    'S',S,'U',U,'V',V,'classification',classification, ...
    'history',history,'summary',summary);
save(final_file,'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,toc(timer)));
disp(struct2table(summary,'AsArray',true));
fprintf('N=200 positive-branch confirmation saved in: %s\n',outdir);
end
