function refresh_BC_edge_resolution_summary()
%REFRESH_BC_EDGE_RESOLUTION_SUMMARY Add explicit verification gates.
%   Updates only configuration/summary fields after the completed numerical
%   run. Numerical states, trajectories, multipliers, and branch records are
%   not changed.

folder=fullfile('experiment_outputs','BC_edge_resolution_geometry_v1');
file=fullfile(folder,'BC_edge_resolution_geometry.mat');
loaded=load(file,'results'); results=loaded.results;
cfg=brusselator_BC_edge_resolution_config();
orbits=results.orbit_records; branches=results.branch_resolution_records;
pass_orbits=all([orbits.attracting_supported]) && ...
    max([orbits.newton_residual])<cfg.BC_resolution.newton_residual_gate && ...
    max([orbits.ode45_verification_residual])< ...
        cfg.BC_resolution.verification_residual_gate && ...
    max([orbits.phase_multiplier_error])< ...
        cfg.BC_resolution.phase_multiplier_error_gate && ...
    max([orbits.maximum_eigenpair_residual])< ...
        cfg.BC_resolution.eigenpair_residual_gate;
pass_branches=all([branches.opposite_BC_supported]);
if pass_orbits&&pass_branches
    status='matched_B_edge_C_geometry_persists_across_tested_resolutions';
else
    status='matched_B_edge_C_resolution_gate_not_passed';
end
results.configuration=cfg;
results.summary=struct('status',status, ...
    'exact_attractor_case_count',numel(orbits), ...
    'all_BC_orbits_attracting_supported',all([orbits.attracting_supported]), ...
    'all_edge_branch_pairs_reach_opposite_BC',pass_branches, ...
    'maximum_attractor_newton_residual',max([orbits.newton_residual]), ...
    'maximum_attractor_verification_residual', ...
        max([orbits.ode45_verification_residual]), ...
    'maximum_phase_multiplier_error',max([orbits.phase_multiplier_error]), ...
    'maximum_attractor_eigenpair_residual', ...
        max([orbits.maximum_eigenpair_residual]), ...
    'claim_scope',cfg.BC_resolution.claim_scope);
save(file,'results','-v7.3');
writetable(struct2table(results.summary,'AsArray',true), ...
    fullfile(folder,'BC_edge_geometry_summary.csv'));
metadata_file=fullfile(folder,'configuration_and_metadata.mat');
loaded=load(metadata_file,'metadata');
brusselator_write_metadata(folder,cfg,loaded.metadata);
fprintf('Refreshed B--edge--C summary with explicit verification gates.\n');
end
