function results = run_physical_ramp_dynamic_C_confirmation()
%RUN_PHYSICAL_RAMP_DYNAMIC_C_CONFIRMATION Tight confirmation of C obstruction.
%   Confirms the five-way C classification encountered while rebracketing
%   the adjacent physical B/A forcing-return states. This is a frozen-system
%   chord result, not a new forcing-generated C outcome.

study_id = 'physical_ramp_BA_dynamic_C_confirmation_v1';
source_file = fullfile('experiment_outputs','physical_ramp_BA_dynamic_edge_v1', ...
    'raw_cases','event01_step10.mat');
outdir = fullfile('experiment_outputs',study_id);
final_file = fullfile(outdir,'tight_C_confirmation.mat');
if ~isfile(source_file)
    error('run_physical_ramp_dynamic_C_confirmation:MissingSource', ...
        'Expected the obstructing C case at %s.',source_file);
end
if isfolder(outdir)
    error('run_physical_ramp_dynamic_C_confirmation:OutputExists', ...
        'Refusing to overwrite %s.',outdir);
end
cfg = brusselator_physical_ramp_dynamic_edge_config();
cfg.experiment_name = study_id;
cfg.solver = cfg.physical_ramp.confirmation_solver;
cfg.dynamic_edge.classification_initial_duration = 80;
cfg.dynamic_edge.classification_chunk_duration = 40;
cfg.dynamic_edge.classification_maximum_duration = 500;
[library,provenance] = brusselator_build_ml_outcome_library(cfg);
loaded = load(source_file,'edge_case'); source = loaded.edge_case;
if ~strcmp(source.classification.outcome,'C')
    error('run_physical_ramp_dynamic_C_confirmation:SourceGate', ...
        'The configured source is %s rather than C.',source.classification.outcome);
end
mkdir(outdir); brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,NaN));
partial_file = fullfile(outdir,'progress_tight_C_confirmation.mat');
timer = tic;
confirmation = brusselator_evolve_and_classify_state( ...
    'physical_ramp_chord_C_tight',source.initial_state,library,cfg,partial_file);
runtime = toc(timer);
if isfile(partial_file), delete(partial_file); end
summary = struct('source_outcome',source.classification.outcome, ...
    'tight_outcome',confirmation.classification.outcome, ...
    'tight_C_confirmation_pass',strcmp(confirmation.classification.outcome,'C'), ...
    'source_tested_duration',source.duration, ...
    'tight_tested_duration',confirmation.duration, ...
    'source_late_median_C',source.classification.late_median_distances(3), ...
    'tight_late_median_C',confirmation.classification.late_median_distances(3), ...
    'runtime_seconds',runtime, ...
    'interpretation',['tight-solver confirmation of C on an interpolated ', ...
        'frozen chord between adjacent physical forcing-return states; ', ...
        'not direct physical forcing access to C']);
results = struct('configuration',cfg,'source_file',source_file, ...
    'library_provenance',provenance,'source',source, ...
    'confirmation',confirmation,'summary',summary);
save(final_file,'results','-v7.3');
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'tight_C_confirmation_summary.csv'));
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,runtime));
disp(struct2table(summary,'AsArray',true));
fprintf('Physical-ramp chord C confirmation saved in: %s\n',outdir);
end
