clear; clc; close all;

%RUN_SOLVER_CROSSCHECK Compare tight ode15s with the historical ode45 run.
%   This targeted N=400, seed-1 check uses a maximum step of 0.1 so the
%   non-smooth changes in forcing slope are explicitly resolved.

study_id = 'solver_crosscheck_ode15s_N400_v1';
base_overrides = struct( ...
    'experiment_name', study_id, ...
    'grid', struct('N', 400), ...
    'initial', struct('seed', 1), ...
    'time', struct('post_forcing', 140), ...
    'solver', struct('name', 'ode15s', 'RelTol', 1e-6, 'AbsTol', 1e-9, ...
        'MaxStep', 0.1));
base_cfg = brusselator_default_config(base_overrides);

outdir = fullfile(base_cfg.output.root, study_id);
if isfolder(outdir)
    error('run_solver_crosscheck:OutputExists', ...
        'Refusing to overwrite existing experiment directory: %s', outdir);
end
mkdir(outdir);
mkdir(fullfile(outdir, 'raw_final_states'));
brusselator_write_metadata(outdir, base_cfg, ...
    brusselator_run_metadata(base_cfg, mfilename, NaN));

bmax_list = [11.12, 11.14];
records = repmat(struct( ...
    'N', [], 'seed', [], 'solver_name', '', 'RelTol', [], 'AbsTol', [], ...
    'MaxStep', [], 'bmax', [], 'Tfinal', [], 'rel_diff_u', [], ...
    'rel_diff_v', [], 'max_diff_u', [], 'max_diff_v', [], ...
    'class_label', '', 'runtime_seconds', []), numel(bmax_list), 1);

for k = 1:numel(bmax_list)
    cfg = brusselator_default_config(struct( ...
        'experiment_name', study_id, ...
        'grid', base_overrides.grid, ...
        'initial', base_overrides.initial, ...
        'time', base_overrides.time, ...
        'solver', base_overrides.solver, ...
        'forcing', struct('bmax', bmax_list(k))));
    fprintf('N=%d, solver=%s, MaxStep=%.2f, bmax=%.2f\n', ...
        cfg.grid.N, cfg.solver.name, cfg.solver.MaxStep, cfg.forcing.bmax);
    result = brusselator_run_pair(cfg);

    records(k) = struct( ...
        'N', cfg.grid.N, 'seed', cfg.initial.seed, ...
        'solver_name', cfg.solver.name, 'RelTol', cfg.solver.RelTol, ...
        'AbsTol', cfg.solver.AbsTol, 'MaxStep', cfg.solver.MaxStep, ...
        'bmax', cfg.forcing.bmax, 'Tfinal', cfg.time.Tfinal, ...
        'rel_diff_u', result.metrics.rel_diff_u, ...
        'rel_diff_v', result.metrics.rel_diff_v, ...
        'max_diff_u', result.metrics.max_diff_u, ...
        'max_diff_v', result.metrics.max_diff_v, ...
        'class_label', result.class_label, ...
        'runtime_seconds', result.runtime_seconds);

    raw = struct('config', cfg, 'ic0', result.ic0, ...
        'control_final', result.control.ic_final, ...
        'forced_final', result.forced.ic_final, 'metrics', result.metrics, ...
        'class_label', result.class_label, 'runtime_seconds', result.runtime_seconds);
    save(fullfile(outdir, 'raw_final_states', ...
        sprintf('ode15s_N400_bmax_%0.2f.mat', cfg.forcing.bmax)), 'raw');
    progress_table = struct2table(records(1:k), 'AsArray', true);
    writetable(progress_table, fullfile(outdir, 'progress_summary.csv'));
end

summary_table = struct2table(records, 'AsArray', true);
writetable(summary_table, fullfile(outdir, 'solver_crosscheck_summary.csv'));
save(fullfile(outdir, 'solver_crosscheck_summary.mat'), 'summary_table', 'records');
metadata = brusselator_run_metadata(base_cfg, mfilename, sum(summary_table.runtime_seconds));
brusselator_write_metadata(outdir, base_cfg, metadata);

disp(summary_table);
disp(['Solver cross-check complete. Results saved in: ', outdir]);
