function results = run_edge_slice_BC_unresolved_extension()
%RUN_EDGE_SLICE_BC_UNRESOLVED_EXTENSION Extend the near-boundary BC midpoint.
%   Continues the saved lambda=0.187890625 trajectory from t=240 to t=500
%   under frozen b=10, then reapplies the unchanged physical five-way
%   classifier. This distinguishes slow commitment from sustained unresolved
%   dynamics before the state is used as an edge-tracking candidate.

cfg=brusselator_edge_slice_refinement_config();
cfg.experiment_name='edge_slice_BC_unresolved_extension_v1';
cfg.extension=struct( ...
    'source_file',fullfile('experiment_outputs', ...
        'edge_slice_pairwise_refinement_v1','raw_cases','bc_step_06.mat'), ...
    'parent_file',fullfile('experiment_outputs', ...
        'edge_tracking_BA_landing_v1','edge_tracking_results.mat'), ...
    'target_duration',500, ...
    'interpretation',['longer finite-time classification of the unresolved ', ...
        'B--C midpoint; not dynamic edge tracking and not proof of an ', ...
        'invariant boundary object']);
outdir=fullfile(cfg.output.root,cfg.experiment_name);
result_file=fullfile(outdir,'BC_unresolved_extension.mat');
if isfolder(outdir)||isfile(result_file)
    error('run_edge_slice_BC_unresolved_extension:OutputExists', ...
        'Refusing to overwrite existing output: %s',outdir);
end
if ~isfile(cfg.extension.source_file)||~isfile(cfg.extension.parent_file)
    error('run_edge_slice_BC_unresolved_extension:MissingInput', ...
        'The saved unresolved case or its outcome library is missing.');
end
source=load(cfg.extension.source_file,'refinement_case');
source=source.refinement_case;
parent_loaded=load(cfg.extension.parent_file,'results');parent=parent_loaded.results;
if ~strcmp(source.classification.outcome,'unresolved') || ...
        abs(source.lambda-0.187890625)>1e-12
    error('run_edge_slice_BC_unresolved_extension:SourceMismatch', ...
        'The configured source is not the expected unresolved B--C midpoint.');
end
mkdir(outdir);brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,NaN));
additional=cfg.extension.target_duration-source.duration;
if additional<=0
    error('run_edge_slice_BC_unresolved_extension:Duration', ...
        'Target duration must exceed the source duration.');
end
par=brusselator_make_parameters(cfg,@(t)cfg.edge_tracking.frozen_b);
fprintf('Extending B--C midpoint lambda=%.9f from t=%.0f to t=%.0f.\n', ...
    source.lambda,source.duration,cfg.extension.target_duration);
timer=tic;
[final_state,S2,V2,U2]=solve_brusselator_1d_forced( ...
    source.final_state,par,additional,0);
S=[source.S;source.duration+S2(2:end)];
U=[source.U;U2(2:end,:)];V=[source.V;V2(2:end,:)];
[classification,history]=brusselator_classify_five_way_trajectory( ...
    S,U,V,parent.library,'late_window',cfg.edge_tracking.late_window, ...
    'sample_interval',cfg.edge_tracking.distance_sample_interval, ...
    'median_threshold',cfg.edge_tracking.median_distance_threshold, ...
    'maximum_threshold',cfg.edge_tracking.maximum_distance_threshold, ...
    'Lx',cfg.grid.Lx);
decision_time=first_commitment_time(history,classification.outcome,cfg);
runtime=toc(timer);
summary=struct('lambda',source.lambda,'source_duration',source.duration, ...
    'target_duration',cfg.extension.target_duration, ...
    'source_outcome',source.classification.outcome, ...
    'extended_outcome',classification.outcome,'decision_time',decision_time, ...
    'runtime_seconds',runtime,'late_median_distance_A', ...
    classification.late_median_distances(1),'late_median_distance_B', ...
    classification.late_median_distances(2),'late_median_distance_C', ...
    classification.late_median_distances(3),'late_median_distance_R5', ...
    classification.late_median_distances(4),'late_median_distance_R6', ...
    classification.late_median_distances(5),'late_maximum_distance_C', ...
    classification.late_maximum_distances(3),'final_distance_C', ...
    classification.final_distances(3),'interpretation',cfg.extension.interpretation);
results=struct('configuration',cfg,'source_file',cfg.extension.source_file, ...
    'initial_state',source.initial_state,'final_state',final_state, ...
    'S',S,'U',U,'V',V,'classification',classification,'history',history, ...
    'summary',summary);
save(result_file,'results','-v7.3');
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'BC_unresolved_extension_summary.csv'));
make_figure(outdir,history,cfg);
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,runtime));
disp(struct2table(summary,'AsArray',true));
fprintf('B--C unresolved extension saved in: %s\n',outdir);
end

function time=first_commitment_time(history,outcome,cfg)
time=NaN;index=find(strcmp(history.labels,outcome),1);if isempty(index),return;end
count=max(1,ceil(cfg.edge_tracking.decision_sustain_duration/ ...
    cfg.edge_tracking.distance_sample_interval));
for k=1:(numel(history.sample_times)-count+1)
    values=history.distances(k:k+count-1,index);
    if median(values)<cfg.edge_tracking.median_distance_threshold && ...
            max(values)<cfg.edge_tracking.maximum_distance_threshold
        time=history.sample_times(k);return;
    end
end
end

function make_figure(outdir,history,cfg)
fig=figure('Color','w','Position',[100 100 1050 620]);ax=axes(fig);hold(ax,'on');
colors=lines(numel(history.labels));
for k=1:numel(history.labels)
    semilogy(ax,history.sample_times,history.distances(:,k),'LineWidth',1.2, ...
        'Color',colors(k,:),'DisplayName',history.labels{k});
end
yline(ax,cfg.edge_tracking.median_distance_threshold,'--k', ...
    'median threshold','HandleVisibility','off');
yline(ax,cfg.edge_tracking.maximum_distance_threshold,':k', ...
    'maximum threshold','HandleVisibility','off');
xline(ax,240,':','saved t=240 endpoint','Color',[0.3 0.3 0.3], ...
    'HandleVisibility','off');
xlabel(ax,'frozen time');ylabel(ax,'physical phase/reflection-aware distance');
title(ax,'Long extension of the unresolved B--C midpoint');
set(ax,'Color','w','XColor','k','YColor','k','GridColor',[0.75 0.75 0.75]);
grid(ax,'on');box(ax,'on');legend(ax,'Location','eastoutside');
exportgraphics(fig,fullfile(outdir,'BC_unresolved_distance_history.png'), ...
    'Resolution',300);close(fig);
end
