function results = run_BA_edge_C_confirmation()
%RUN_BA_EDGE_C_CONFIRMATION Confirm the unexpected lambda=0.25 C outcome.
%   Repeats the third-outcome midpoint from the B--A landing segment with the
%   tight N=400 ode15s configuration. Confirmation is based on the physical
%   five-way phase/reflection-aware classifier, not the POD projection.

study_id='edge_tracking_BA_landing_C_confirmation_v1';
parent_file=fullfile('experiment_outputs','edge_tracking_BA_landing_v1', ...
    'edge_tracking_results.mat');
outdir=fullfile('experiment_outputs',study_id);
if ~isfile(parent_file)
    error('run_BA_edge_C_confirmation:MissingParent', ...
        'Expected edge result at %s.',parent_file);
end
if isfolder(outdir)
    error('run_BA_edge_C_confirmation:OutputExists', ...
        'Refusing to overwrite %s.',outdir);
end
parent=load(parent_file,'results');parent=parent.results;
candidate_id=parent.candidate_case_id;
index=find(strcmp({parent.records.case_id},candidate_id),1);
if isempty(index)||~strcmp(parent.records(index).outcome,'C')
    error('run_BA_edge_C_confirmation:Candidate', ...
        'The parent candidate is not a saved C midpoint.');
end
lambda=parent.records(index).lambda;
tight=struct('name','ode15s','output_dt',0.1, ...
    'RelTol',1e-8,'AbsTol',1e-10,'MaxStep',0.1);
cfg=brusselator_default_config(struct('experiment_name',study_id, ...
    'model',parent.configuration.model,'grid',parent.configuration.grid, ...
    'forcing',parent.configuration.forcing,'initial',parent.configuration.initial, ...
    'solver',tight));
cfg.confirmation=struct('parent_file',parent_file,'candidate_case_id',candidate_id, ...
    'lambda',lambda,'duration',240,'frozen_b',10,'expected_outcome','C', ...
    'late_window',parent.configuration.edge_tracking.late_window, ...
    'distance_sample_interval',1, ...
    'median_threshold',parent.configuration.edge_tracking.median_distance_threshold, ...
    'maximum_threshold',parent.configuration.edge_tracking.maximum_distance_threshold, ...
    'interpretation',['tight-solver replication of the newly found C-accessible ', ...
        'state on the B--A landing interpolation']);
mkdir(outdir);brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,NaN));
u0=(1-lambda)*parent.endpoint_B(:,2)+lambda*parent.endpoint_A(:,2);
v0=(1-lambda)*parent.endpoint_B(:,3)+lambda*parent.endpoint_A(:,3);
initial_state=[parent.endpoint_B(:,1),u0,v0];
moderate=load(parent.raw_files{index},'case_result');moderate=moderate.case_result;
initial_error=physical_state_distance(initial_state,moderate.initial_state,cfg.grid.Lx);
if initial_error>1e-12
    error('run_BA_edge_C_confirmation:InitialStateMismatch', ...
        'Reconstructed candidate initial state differs by %.3e.',initial_error);
end
par=brusselator_make_parameters(cfg,@(t)cfg.confirmation.frozen_b);
fprintf('Tight confirmation of %s at lambda=%.10f for %.0f time units ...\n', ...
    candidate_id,lambda,cfg.confirmation.duration);
timer=tic;
[final_state,S,V,U]=solve_brusselator_1d_forced( ...
    initial_state,par,cfg.confirmation.duration,0);
[classification,history]=brusselator_classify_five_way_trajectory( ...
    S,U,V,parent.library,'late_window',cfg.confirmation.late_window, ...
    'sample_interval',cfg.confirmation.distance_sample_interval, ...
    'median_threshold',cfg.confirmation.median_threshold, ...
    'maximum_threshold',cfg.confirmation.maximum_threshold,'Lx',cfg.grid.Lx);
runtime=toc(timer);c_index=find(strcmp(classification.labels,'C'),1);
gate=strcmp(classification.outcome,'C') && ...
    classification.late_median_distances(c_index)<cfg.confirmation.median_threshold && ...
    classification.late_maximum_distances(c_index)<cfg.confirmation.maximum_threshold;
summary=struct('candidate_case_id',candidate_id,'lambda',lambda, ...
    'moderate_outcome',moderate.classification.outcome, ...
    'tight_outcome',classification.outcome, ...
    'moderate_late_median_C',moderate.classification.late_median_distances(c_index), ...
    'tight_late_median_C',classification.late_median_distances(c_index), ...
    'moderate_late_maximum_C',moderate.classification.late_maximum_distances(c_index), ...
    'tight_late_maximum_C',classification.late_maximum_distances(c_index), ...
    'tight_final_C',classification.final_distances(c_index), ...
    'initial_state_reconstruction_error',initial_error, ...
    'tight_C_confirmation_pass',gate,'runtime_seconds',runtime, ...
    'interpretation',['finite-time tight-solver confirmation of C basin access ', ...
        'on the constructed frozen-system line; not yet physical forcing access']);
writetable(struct2table(summary,'AsArray',true), ...
    fullfile(outdir,'C_confirmation_summary.csv'));
make_figures(outdir,moderate,history,parent.library,cfg);
results=struct('configuration',cfg,'summary',summary,'initial_state',initial_state, ...
    'final_state',final_state,'S',S,'U',U,'V',V, ...
    'classification',classification,'history',history);
save(fullfile(outdir,'C_confirmation_trajectory.mat'),'results','-v7.3');
brusselator_write_metadata(outdir,cfg, ...
    brusselator_run_metadata(cfg,mfilename,runtime));
disp(struct2table(summary,'AsArray',true));
fprintf('Tight C confirmation saved in: %s\n',outdir);
end

function make_figures(outdir,moderate,tight,library,cfg)
fig=figure('Color','w','Position',[100 100 950 560]);ax=axes(fig);hold(ax,'on');
for k=1:numel(library)
    semilogy(ax,tight.sample_times,max(tight.distances(:,k),eps), ...
        'LineWidth',1.25,'DisplayName',library(k).label);
end
yline(ax,cfg.confirmation.median_threshold,'--k','HandleVisibility','off');
xlabel(ax,'frozen b=10 time');ylabel(ax,'physical phase/reflection-aware distance');
title(ax,'Tight-solver confirmation of the lambda=0.25 C outcome');
style_axes(ax);style_legend(legend(ax,'Location','best'));
exportgraphics(fig,fullfile(outdir,'tight_distance_histories.png'),'Resolution',300);
close(fig);

c_index=find(strcmp({library.label},'C'),1);
fig=figure('Color','w','Position',[100 100 900 500]);ax=axes(fig);hold(ax,'on');
semilogy(ax,moderate.history.sample_times, ...
    max(moderate.history.distances(:,c_index),eps),'LineWidth',1.3, ...
    'DisplayName','moderate ode15s');
semilogy(ax,tight.sample_times,max(tight.distances(:,c_index),eps), ...
    '--','LineWidth',1.3,'DisplayName','tight ode15s');
xlabel(ax,'frozen b=10 time');ylabel(ax,'physical distance to C orbit');
title(ax,'Solver comparison for C-basin approach');style_axes(ax);
style_legend(legend(ax,'Location','best'));
exportgraphics(fig,fullfile(outdir,'moderate_vs_tight_C_distance.png'),'Resolution',300);
close(fig);
end

function distance=physical_state_distance(A,B,Lx)
N=size(A,1);dx=Lx/(N-1);weights=dx*ones(N,1);weights([1,end])=0.5*dx;
distance=sqrt(sum(((A(:,2)-B(:,2)).^2+(A(:,3)-B(:,3)).^2).*weights)/ ...
    max(sum((B(:,2).^2+B(:,3).^2).*weights),eps));
end

function style_axes(ax)
set(ax,'Color','w','XColor','k','YColor','k','GridColor',[0.75 0.75 0.75]);
grid(ax,'on');box(ax,'on');ax.Title.Color='k';ax.XLabel.Color='k';ax.YLabel.Color='k';
end

function style_legend(leg)
set(leg,'Color','w','TextColor','k','EdgeColor',[0.25 0.25 0.25], ...
    'Interpreter','none');
end
