function results = run_recurrent_class_validation()
%RUN_RECURRENT_CLASS_VALIDATION Validate the two forcing-recurrent classes.
%   Uses one clean representative of each recurrence-period class, tests
%   fixed-domain persistence under grid/solver/tolerance changes, estimates
%   its period by direct full-trajectory recurrence, and continues every
%   independent forcing preparation with the tight N=400 solver to test
%   convergence toward the same phase/reflection-quotiented orbit set.
%
%   This is an Lx=40 numerical validation. Local attraction is tested by the
%   separate run_recurrent_class_local_stability study.

study_id = 'recurrent_class_validation_v1';
parent_file = fullfile('experiment_outputs', ...
    'unresolved_forcing_long_extension_v1', ...
    'unresolved_forcing_long_extensions.mat');
outdir = fullfile('experiment_outputs', study_id);
progress_file = fullfile(outdir, 'progress_recurrent_class_validation.mat');
if ~isfile(parent_file)
    error('run_recurrent_class_validation:MissingParent', ...
        'Expected long-extension results at %s.', parent_file);
end

loaded = load(parent_file, 'results');
parent = loaded.results;
representatives = representative_specs(parent);
[source_data, source_records, source_templates] = ...
    analyze_sources(representatives);
cases = validation_cases(representatives);
preparations = preparation_specs(parent);

tight = struct('name', 'ode15s', 'output_dt', 0.1, ...
    'RelTol', 1e-8, 'AbsTol', 1e-10, 'MaxStep', 0.1);
cfg = brusselator_default_config(struct( ...
    'experiment_name', study_id, 'model', parent.configuration.model, ...
    'grid', parent.configuration.grid, 'forcing', parent.configuration.forcing, ...
    'initial', parent.configuration.initial, 'solver', tight));
cfg.recurrent_class_validation = struct( ...
    'parent_file', parent_file, 'domain_Lx', 40, ...
    'representatives', representatives, ...
    'validation_duration', 80, 'analysis_start', 40, ...
    'phase_samples', 360, 'direct_recurrence_threshold', 1e-2, ...
    'direct_lag_search_relative_to_guess', [0.35, 2.25], ...
    'maximum_period_cv', 0.02, 'maximum_relative_period_error', 0.05, ...
    'maximum_source_orbit_distance', 0.10, ...
    'same_orbit_threshold', 0.02, 'different_class_threshold', 0.10, ...
    'cross_preparation_solver', tight, ...
    'interpretation', ['fixed-Lx numerical persistence and cross-preparation ', ...
        'orbit agreement; attraction is a separate gate']);

resume = isfolder(outdir) && isfile(progress_file);
if isfolder(outdir) && ~resume
    error('run_recurrent_class_validation:OutputExists', ...
        'Refusing existing directory without a valid checkpoint: %s', outdir);
end
if resume
    checkpoint = load(progress_file, 'cfg', 'records', 'raw_files', ...
        'cross_records', 'cross_files');
    if numel(checkpoint.records) ~= numel(cases) || ...
            numel(checkpoint.cross_records) ~= numel(preparations)
        error('run_recurrent_class_validation:CheckpointMismatch', ...
            'The checkpoint does not match this validation design.');
    end
    cfg = checkpoint.cfg;
    records = checkpoint.records;
    raw_files = checkpoint.raw_files;
    cross_records = checkpoint.cross_records;
    cross_files = checkpoint.cross_files;
    cfg.recurrent_class_validation.direct_lag_search_relative_to_guess = [0.35, 2.25];
    fprintf('Resuming %s from its saved checkpoint.\n', study_id);
else
    mkdir(outdir);
    mkdir(fullfile(outdir, 'raw_numerical_cases'));
    mkdir(fullfile(outdir, 'raw_cross_preparations'));
    records = repmat(empty_validation_record(), numel(cases), 1);
    raw_files = cell(numel(cases),1);
    cross_records = repmat(empty_cross_record(), numel(preparations), 1);
    cross_files = cell(numel(preparations),1);
    brusselator_write_metadata(outdir, cfg, ...
        brusselator_run_metadata(cfg, mfilename, NaN));
end

% Recompute diagnostics from already saved trajectories. This is inexpensive
% relative to the PDE solves and makes a resumed run adopt corrected analysis
% definitions without rerunning or discarding numerical data.
[records, raw_files] = refresh_completed_validation(cases, records, raw_files, ...
    representatives, source_records, source_templates, cfg);

for k = 1:numel(cases)
    spec = cases(k);
    if ~strcmp(records(k).classification, 'unclassified') && ...
            ~isempty(raw_files{k}) && isfile(raw_files{k})
        fprintf('Skipping completed numerical case %d/%d: %s.\n', ...
            k, numel(cases), spec.case_id);
        continue;
    end
    source_index = find(strcmp({representatives.class_id}, spec.class_id), 1);
    source = source_data{source_index};
    source_record = source_records(source_index);
    source_template = source_templates{source_index};
    case_cfg = brusselator_default_config(struct( ...
        'experiment_name', [study_id, '_', spec.case_id], ...
        'model', cfg.model, 'grid', struct('N', spec.N, 'Lx', 40), ...
        'forcing', cfg.forcing, 'initial', cfg.initial, 'solver', spec.solver));
    initial_state = transfer_state(source.final_state, spec.N, 40);
    frozen_par = brusselator_make_parameters(case_cfg, @(t) cfg.forcing.b0);
    fprintf('Numerical validation %d/%d: %s, %s, N=%d ...\n', ...
        k, numel(cases), spec.class_id, spec.solver.name, spec.N);
    timer = tic;
    [final_state, S, V, U] = solve_brusselator_1d_forced( ...
        initial_state, frozen_par, cfg.recurrent_class_validation.validation_duration, 0);
    runtime = toc(timer);
    section = brusselator_periodic_recurrence(S, U, V, ...
        cfg.recurrent_class_validation.analysis_start, ...
        cfg.recurrent_class_validation.direct_recurrence_threshold);
    windowed_direct = brusselator_direct_period_recurrence(S, U, V, ...
        cfg.recurrent_class_validation.analysis_start, source_record.direct_period);
    direct = brusselator_direct_return_test(section.section.states(end,:), ...
        case_cfg, cfg.forcing.b0, source_record.direct_period, ...
        cfg.recurrent_class_validation.direct_recurrence_threshold);
    template = brusselator_build_periodic_template(S, U, V, ...
        direct.direct_period, cfg.recurrent_class_validation.phase_samples);
    source_distance = brusselator_orbit_template_distance(template, source_template);
    record = summarize_validation(spec, section, direct, source_distance, ...
        source_record.direct_period, runtime, cfg);
    records(k) = record;
    case_result = struct('configuration', case_cfg, 'specification', spec, ...
        'initial_state', initial_state, 'final_state', final_state, ...
        'S', S, 'U', U, 'V', V, 'section', section, ...
        'windowed_direct', windowed_direct, 'direct', direct, ...
        'template', template, 'source_orbit_distance', source_distance, ...
        'record', record);
    case_file = fullfile(outdir, 'raw_numerical_cases', [spec.case_id, '.mat']);
    save(case_file, 'case_result', '-v7.3');
    raw_files{k} = case_file;
    write_progress(progress_file, outdir, cfg, records, raw_files, ...
        cross_records, cross_files);
    fprintf('  %s; Pdirect=%.6f, drec=%.3e, dorbit=%.3e (%.1f s).\n', ...
        record.classification, record.direct_period, ...
        record.direct_recurrence_distance, ...
        record.orbit_distance_to_source, runtime);
end

validated_templates = load_validated_templates(cases, records, raw_files);
for k = 1:numel(preparations)
    spec = preparations(k);
    if ~strcmp(cross_records(k).classification, 'unclassified') && ...
            ~isempty(cross_files{k}) && isfile(cross_files{k})
        fprintf('Skipping completed preparation %d/%d: %s.\n', ...
            k, numel(preparations), spec.protocol_id);
        continue;
    end
    saved = load(spec.source_file, 'continuation');
    source = saved.continuation;
    own_template = validated_templates.(spec.class_id);
    other_id = other_class(spec.class_id);
    other_template = validated_templates.(other_id);
    initial_template = brusselator_build_periodic_template( ...
        source.S, source.U, source.V, spec.source_period, ...
        cfg.recurrent_class_validation.phase_samples);
    initial_distance = brusselator_orbit_template_distance( ...
        initial_template, own_template);

    case_cfg = cfg;
    case_cfg.experiment_name = [study_id, '_cross_', spec.protocol_id];
    case_cfg.solver = cfg.recurrent_class_validation.cross_preparation_solver;
    frozen_par = brusselator_make_parameters(case_cfg, @(t) cfg.forcing.b0);
    fprintf('Cross-preparation %d/%d: %s -> %s ...\n', ...
        k, numel(preparations), spec.protocol_id, spec.class_id);
    timer = tic;
    [final_state, S, V, U] = solve_brusselator_1d_forced( ...
        source.final_state, frozen_par, ...
        cfg.recurrent_class_validation.validation_duration, 0);
    runtime = toc(timer);
    section = brusselator_periodic_recurrence(S, U, V, ...
        cfg.recurrent_class_validation.analysis_start, ...
        cfg.recurrent_class_validation.direct_recurrence_threshold);
    windowed_direct = brusselator_direct_period_recurrence(S, U, V, ...
        cfg.recurrent_class_validation.analysis_start, spec.source_period);
    direct = brusselator_direct_return_test(section.section.states(end,:), ...
        case_cfg, cfg.forcing.b0, spec.source_period, ...
        cfg.recurrent_class_validation.direct_recurrence_threshold);
    template = brusselator_build_periodic_template(S, U, V, ...
        direct.direct_period, cfg.recurrent_class_validation.phase_samples);
    own_distance = brusselator_orbit_template_distance(template, own_template);
    other_distance = brusselator_orbit_template_distance(template, other_template);
    record = summarize_cross(spec, section, direct, initial_distance, ...
        own_distance, other_distance, runtime, cfg);
    cross_records(k) = record;
    cross_result = struct('configuration', case_cfg, 'specification', spec, ...
        'initial_state', source.final_state, 'final_state', final_state, ...
        'S', S, 'U', U, 'V', V, 'section', section, ...
        'windowed_direct', windowed_direct, 'direct', direct, ...
        'template', template, 'initial_orbit_distance', initial_distance, ...
        'own_orbit_distance', own_distance, ...
        'other_class_orbit_distance', other_distance, 'record', record);
    case_file = fullfile(outdir, 'raw_cross_preparations', ...
        [spec.protocol_id, '.mat']);
    save(case_file, 'cross_result', '-v7.3');
    cross_files{k} = case_file;
    write_progress(progress_file, outdir, cfg, records, raw_files, ...
        cross_records, cross_files);
    fprintf('  %s; down %.3e -> %.3e, dother=%.3e (%.1f s).\n', ...
        record.classification, record.initial_distance_to_representative, ...
        record.final_distance_to_representative, ...
        record.final_distance_to_other_class, runtime);
end

validation_table = struct2table(records, 'AsArray', true);
cross_table = struct2table(cross_records, 'AsArray', true);
writetable(validation_table, fullfile(outdir, 'numerical_validation_summary.csv'));
writetable(cross_table, fullfile(outdir, 'cross_preparation_summary.csv'));
writetable(struct2table(source_records, 'AsArray', true), ...
    fullfile(outdir, 'source_representative_summary.csv'));
gates = aggregate_gates(records, cross_records);
writetable(struct2table(gates, 'AsArray', true), ...
    fullfile(outdir, 'recurrent_class_validation_gates.csv'));
make_figures(outdir, records, cross_records);
results = struct('configuration', cfg, 'source_records', source_records, ...
    'validation_records', records, 'validation_raw_files', {raw_files}, ...
    'cross_preparation_records', cross_records, ...
    'cross_preparation_files', {cross_files}, 'gates', gates);
save(fullfile(outdir, 'recurrent_class_validation.mat'), 'results', '-v7.3');
brusselator_write_metadata(outdir, cfg, brusselator_run_metadata( ...
    cfg, mfilename, sum([records.runtime_seconds]) + ...
    sum([cross_records.runtime_seconds])));
disp(validation_table);
disp(cross_table);
disp(struct2table(gates, 'AsArray', true));
fprintf('Recurrent-class validation saved in: %s\n', outdir);
end

function [records, raw_files] = refresh_completed_validation(cases, records, ...
        raw_files, representatives, source_records, source_templates, cfg)
for k = 1:numel(cases)
    if isempty(raw_files{k}) || ~isfile(raw_files{k})
        continue;
    end
    loaded = load(raw_files{k}, 'case_result');
    case_result = loaded.case_result;
    source_index = find(strcmp({representatives.class_id}, cases(k).class_id), 1);
    source_record = source_records(source_index);
    windowed_direct = brusselator_direct_period_recurrence( ...
        case_result.S, case_result.U, case_result.V, ...
        cfg.recurrent_class_validation.analysis_start, source_record.direct_period);
    direct = brusselator_direct_return_test( ...
        case_result.section.section.states(end,:), case_result.configuration, ...
        cfg.forcing.b0, source_record.direct_period, ...
        cfg.recurrent_class_validation.direct_recurrence_threshold);
    template = brusselator_build_periodic_template( ...
        case_result.S, case_result.U, case_result.V, direct.direct_period, ...
        cfg.recurrent_class_validation.phase_samples);
    source_distance = brusselator_orbit_template_distance( ...
        template, source_templates{source_index});
    record = summarize_validation(cases(k), case_result.section, direct, ...
        source_distance, source_record.direct_period, ...
        records(k).runtime_seconds, cfg);
    records(k) = record;
    case_result.direct = direct;
    case_result.windowed_direct = windowed_direct;
    case_result.template = template;
    case_result.source_orbit_distance = source_distance;
    case_result.record = record;
    save(raw_files{k}, 'case_result', '-v7.3');
end
end

function specs = representative_specs(parent)
ids = {'amplitude_bmax_12.50', 'symmetric_ramp_012'};
class_ids = {'period_5p0585', 'period_6p5837'};
labels = {'R5', 'R6'};
specs = repmat(struct('class_id', '', 'display_label', '', ...
    'protocol_id', '', 'source_file', '', 'source_period', NaN), 2, 1);
for k = 1:2
    index = find(strcmp({parent.records.protocol_id}, ids{k}), 1);
    if isempty(index)
        error('run_recurrent_class_validation:MissingRepresentative', ...
            'Missing representative protocol %s.', ids{k});
    end
    specs(k) = struct('class_id', class_ids{k}, 'display_label', labels{k}, ...
        'protocol_id', ids{k}, 'source_file', parent.continuation_files{index}, ...
        'source_period', parent.records(index).section_period);
end
end

function [data, records, templates] = analyze_sources(specs)
data = cell(numel(specs),1);
templates = cell(numel(specs),1);
records = repmat(struct('class_id', '', 'protocol_id', '', ...
    'section_period', NaN, 'direct_period', NaN, ...
    'direct_recurrence_distance', NaN, 'reflection_period', NaN, ...
    'reflection_recurrence_distance', NaN), numel(specs), 1);
for k = 1:numel(specs)
    loaded = load(specs(k).source_file, 'continuation');
    data{k} = loaded.continuation;
    source = data{k};
    recurrence_records = source.recurrence.recurrence.records;
    direct_index = find([recurrence_records.direct_median_rel_diff_full_state] < 1e-2, 1);
    if isempty(direct_index)
        [~, direct_index] = min( ...
            [recurrence_records.direct_median_rel_diff_full_state]);
    end
    [~, reflection_index] = min( ...
        [recurrence_records.reflection_median_rel_diff_full_state]);
    direct_period = recurrence_records(direct_index).return_time;
    templates{k} = brusselator_build_periodic_template( ...
        source.S, source.U, source.V, direct_period, 360);
    records(k) = struct('class_id', specs(k).class_id, ...
        'protocol_id', specs(k).protocol_id, ...
        'section_period', specs(k).source_period, ...
        'direct_period', direct_period, ...
        'direct_recurrence_distance', ...
            recurrence_records(direct_index).direct_median_rel_diff_full_state, ...
        'reflection_period', recurrence_records(reflection_index).return_time, ...
        'reflection_recurrence_distance', ...
            recurrence_records(reflection_index).reflection_median_rel_diff_full_state);
end
end

function cases = validation_cases(representatives)
tight = struct('name', 'ode15s', 'output_dt', 0.1, ...
    'RelTol', 1e-8, 'AbsTol', 1e-10, 'MaxStep', 0.1);
explicit = struct('name', 'ode45', 'output_dt', 0.1, ...
    'RelTol', 1e-7, 'AbsTol', 1e-9, 'MaxStep', 0.05);
template = struct('case_id', '', 'class_id', '', 'source_protocol', '', ...
    'factor', '', 'N', NaN, 'solver', tight);
cases = repmat(template, 4 * numel(representatives), 1);
count = 0;
for k = 1:numel(representatives)
    entries = {sprintf('%s_N200_tight', representatives(k).display_label), ...
        'grid', 200, tight; ...
        sprintf('%s_N400_tight', representatives(k).display_label), ...
        'tolerance', 400, tight; ...
        sprintf('%s_N600_tight', representatives(k).display_label), ...
        'grid', 600, tight; ...
        sprintf('%s_N200_ode45', representatives(k).display_label), ...
        'solver', 200, explicit};
    for j = 1:size(entries,1)
        count = count + 1;
        cases(count) = struct('case_id', entries{j,1}, ...
            'class_id', representatives(k).class_id, ...
            'source_protocol', representatives(k).protocol_id, ...
            'factor', entries{j,2}, 'N', entries{j,3}, ...
            'solver', entries{j,4});
    end
end
end

function specs = preparation_specs(parent)
specs = repmat(struct('protocol_id', '', 'source_file', '', ...
    'source_period', NaN, 'class_id', ''), numel(parent.records), 1);
for k = 1:numel(parent.records)
    period = parent.records(k).section_period;
    if period < 5.8
        class_id = 'period_5p0585';
    else
        class_id = 'period_6p5837';
    end
    specs(k) = struct('protocol_id', parent.records(k).protocol_id, ...
        'source_file', parent.continuation_files{k}, ...
        'source_period', period, 'class_id', class_id);
end
end

function initial_state = transfer_state(source_state, target_N, target_Lx)
source_x = source_state(:,1);
target_x = linspace(0, target_Lx, target_N)';
coordinate = (source_x - source_x(1)) / (source_x(end) - source_x(1));
target_coordinate = (target_x - target_x(1)) / ...
    (target_x(end) - target_x(1));
u = interp1(coordinate, source_state(:,2), target_coordinate, 'pchip');
v = interp1(coordinate, source_state(:,3), target_coordinate, 'pchip');
initial_state = [target_x, u, v];
end

function record = empty_validation_record()
record = struct('case_id', '', 'class_id', '', 'source_protocol', '', ...
    'factor', '', 'N', NaN, 'dx', NaN, 'solver_name', '', ...
    'RelTol', NaN, 'AbsTol', NaN, 'MaxStep', NaN, ...
    'section_period', NaN, 'section_period_cv', NaN, ...
    'direct_period', NaN, 'direct_recurrence_distance', NaN, ...
    'reflection_period', NaN, 'reflection_recurrence_distance', NaN, ...
    'relative_direct_period_error', NaN, 'orbit_distance_to_source', NaN, ...
    'orbit_distance_uses_reflection', false, 'runtime_seconds', NaN, ...
    'classification', 'unclassified');
end

function record = summarize_validation(spec, section, direct, source_distance, ...
        source_period, runtime, cfg)
record = empty_validation_record();
record.case_id = spec.case_id;
record.class_id = spec.class_id;
record.source_protocol = spec.source_protocol;
record.factor = spec.factor;
record.N = spec.N;
record.dx = 40 / (spec.N - 1);
record.solver_name = spec.solver.name;
record.RelTol = spec.solver.RelTol;
record.AbsTol = spec.solver.AbsTol;
record.MaxStep = spec.solver.MaxStep;
record.section_period = section.section.period;
record.section_period_cv = section.section.period_cv;
record.direct_period = direct.direct_period;
record.direct_recurrence_distance = direct.direct_distance;
record.reflection_period = direct.reflection_period;
record.reflection_recurrence_distance = direct.reflection_distance;
record.relative_direct_period_error = abs(direct.direct_period - source_period) / source_period;
record.orbit_distance_to_source = source_distance.distance;
record.orbit_distance_uses_reflection = source_distance.uses_reflection;
record.runtime_seconds = runtime;
valid = direct.direct_distance < ...
        cfg.recurrent_class_validation.direct_recurrence_threshold && ...
    section.section.period_cv < cfg.recurrent_class_validation.maximum_period_cv && ...
    record.relative_direct_period_error < ...
        cfg.recurrent_class_validation.maximum_relative_period_error && ...
    source_distance.distance < ...
        cfg.recurrent_class_validation.maximum_source_orbit_distance;
if valid
    record.classification = 'supports_periodic_orbit_persistence';
elseif direct.direct_distance < cfg.recurrent_class_validation.direct_recurrence_threshold
    record.classification = 'recurrent_but_not_same_validated_orbit';
else
    record.classification = 'does_not_support_periodic_persistence';
end
end

function record = empty_cross_record()
record = struct('protocol_id', '', 'class_id', '', 'source_period', NaN, ...
    'direct_period', NaN, 'direct_recurrence_distance', NaN, ...
    'section_period_cv', NaN, 'initial_distance_to_representative', NaN, ...
    'final_distance_to_representative', NaN, ...
    'final_distance_to_other_class', NaN, 'distance_ratio', NaN, ...
    'best_uses_reflection', false, 'runtime_seconds', NaN, ...
    'classification', 'unclassified');
end

function record = summarize_cross(spec, section, direct, initial_distance, ...
        own_distance, other_distance, runtime, cfg)
record = empty_cross_record();
record.protocol_id = spec.protocol_id;
record.class_id = spec.class_id;
record.source_period = spec.source_period;
record.direct_period = direct.direct_period;
record.direct_recurrence_distance = direct.direct_distance;
record.section_period_cv = section.section.period_cv;
record.initial_distance_to_representative = initial_distance.distance;
record.final_distance_to_representative = own_distance.distance;
record.final_distance_to_other_class = other_distance.distance;
record.distance_ratio = own_distance.distance / max(initial_distance.distance, eps);
record.best_uses_reflection = own_distance.uses_reflection;
record.runtime_seconds = runtime;
same = own_distance.distance < cfg.recurrent_class_validation.same_orbit_threshold && ...
    abs(direct.direct_period - spec.source_period) / spec.source_period < ...
        cfg.recurrent_class_validation.maximum_relative_period_error && ...
    direct.direct_distance < cfg.recurrent_class_validation.direct_recurrence_threshold;
separate = other_distance.distance > ...
    cfg.recurrent_class_validation.different_class_threshold;
if same && separate
    record.classification = 'converges_to_representative_orbit_set';
elseif direct.direct_distance < cfg.recurrent_class_validation.direct_recurrence_threshold
    record.classification = 'recurrent_but_distinct_from_representative';
else
    record.classification = 'not_resolved_after_tight_extension';
end
end

function templates = load_validated_templates(cases, records, raw_files)
templates = struct();
class_ids = unique({cases.class_id}, 'stable');
for k = 1:numel(class_ids)
    index = find(strcmp({cases.class_id}, class_ids{k}) & ...
        [cases.N] == 400 & strcmp({cases.factor}, 'tolerance'), 1);
    if isempty(index) || ~strcmp(records(index).classification, ...
            'supports_periodic_orbit_persistence')
        error('run_recurrent_class_validation:MissingValidatedTemplate', ...
            'The tight N=400 representative for %s did not validate.', class_ids{k});
    end
    loaded = load(raw_files{index}, 'case_result');
    templates.(class_ids{k}) = loaded.case_result.template;
end
end

function id = other_class(class_id)
if strcmp(class_id, 'period_5p0585')
    id = 'period_6p5837';
else
    id = 'period_5p0585';
end
end

function gates = aggregate_gates(records, cross_records)
classes = {'period_5p0585', 'period_6p5837'};
gates = repmat(struct('class_id', '', 'number_numerical_cases', NaN, ...
    'number_numerical_pass', NaN, 'periodic_orbit_supported', false, ...
    'number_preparations', NaN, 'number_same_orbit_preparations', NaN, ...
    'cross_preparation_orbit_supported', false, ...
    'separated_from_other_period_class', false, ...
    'attracting_periodic_orbit_supported', false, ...
    'distinct_attractor_supported', false, ...
    'interpretation', ['attraction gates intentionally false until the ', ...
        'separate local-perturbation screen is complete']), 2, 1);
for k = 1:2
    numerical = strcmp({records.class_id}, classes{k});
    prep = strcmp({cross_records.class_id}, classes{k});
    numerical_pass = strcmp({records(numerical).classification}, ...
        'supports_periodic_orbit_persistence');
    prep_pass = strcmp({cross_records(prep).classification}, ...
        'converges_to_representative_orbit_set');
    gates(k).class_id = classes{k};
    gates(k).number_numerical_cases = sum(numerical);
    gates(k).number_numerical_pass = sum(numerical_pass);
    gates(k).periodic_orbit_supported = all(numerical_pass);
    gates(k).number_preparations = sum(prep);
    gates(k).number_same_orbit_preparations = sum(prep_pass);
    gates(k).cross_preparation_orbit_supported = sum(prep_pass) >= 2;
    gates(k).separated_from_other_period_class = all( ...
        [cross_records(prep).final_distance_to_other_class] > 0.1);
end
end

function write_progress(progress_file, outdir, cfg, records, raw_files, ...
        cross_records, cross_files)
writetable(struct2table(records, 'AsArray', true), ...
    fullfile(outdir, 'progress_numerical_summary.csv'));
writetable(struct2table(cross_records, 'AsArray', true), ...
    fullfile(outdir, 'progress_cross_preparation_summary.csv'));
save(progress_file, 'cfg', 'records', 'raw_files', ...
    'cross_records', 'cross_files', '-v7.3');
end

function make_figures(outdir, records, cross_records)
fig = figure('Color', 'w', 'Position', [100 100 900 460]);
classes = categorical({records.class_id});
scatter([records.N], [records.orbit_distance_to_source], 75, double(classes), ...
    'filled');
set(gca, 'YScale', 'log'); xlabel('Spatial grid N');
ylabel('Orbit distance to source preparation');
title('Numerical persistence of recurrent-class representatives');
grid on; box on;
exportgraphics(fig, fullfile(outdir, 'numerical_orbit_persistence.png'), ...
    'Resolution', 300);
close(fig);

fig = figure('Color', 'w', 'Position', [100 100 1050 470]);
values = [[cross_records.initial_distance_to_representative]', ...
    [cross_records.final_distance_to_representative]'];
bar(values); set(gca, 'YScale', 'log', 'XTick', 1:numel(cross_records), ...
    'XTickLabel', {cross_records.protocol_id}, 'XTickLabelRotation', 40);
ylabel('Distance to tight representative orbit');
legend({'before tight extension','after tight extension'}, 'Location','best');
title('Cross-preparation agreement within recurrence-period classes');
grid on; box on;
exportgraphics(fig, fullfile(outdir, 'cross_preparation_convergence.png'), ...
    'Resolution', 300);
close(fig);
end
