clear; clc; close all;

%RUN_HIGH_RESOLUTION_STIFF_CHECK Targeted N=800 solver cross-check.
%   The full explicit-ode45 N=800 sweep is expensive for this diffusive
%   system. This bounded companion study instead uses a tight ode15s solve
%   for the two amplitudes that bracket the observed seed-1 threshold.

study_id = 'high_resolution_ode15s_v1';
base_overrides = struct( ...
    'experiment_name', study_id, ...
    'grid', struct('N', 800), ...
    'initial', struct('seed', 1), ...
    'time', struct('post_forcing', 140), ...
    'solver', struct('name', 'ode15s', 'RelTol', 1e-6, 'AbsTol', 1e-9));
base_cfg = brusselator_default_config(base_overrides);

outdir = fullfile(base_cfg.output.root, study_id);
if isfolder(outdir)
    error('run_high_resolution_stiff_check:OutputExists', ...
        'Refusing to overwrite existing experiment directory: %s', outdir);
end
mkdir(outdir);
mkdir(fullfile(outdir, 'raw_final_states'));
brusselator_write_metadata(outdir, base_cfg, ...
    brusselator_run_metadata(base_cfg, mfilename, NaN));

bmax_list = [11.12, 11.14];
records = repmat(struct( ...
    'N', [], 'seed', [], 'solver_name', '', 'RelTol', [], 'AbsTol', [], ...
    'bmax', [], 'Tfinal', [], 'rel_diff_u', [], 'rel_diff_v', [], ...
    'max_diff_u', [], 'max_diff_v', [], 'class_label', '', ...
    'runtime_seconds', []), numel(bmax_list), 1);

for k = 1:numel(bmax_list)
    cfg = brusselator_default_config(struct( ...
        'experiment_name', study_id, ...
        'grid', base_overrides.grid, ...
        'initial', base_overrides.initial, ...
        'time', base_overrides.time, ...
        'solver', base_overrides.solver, ...
        'forcing', struct('bmax', bmax_list(k))));
    fprintf('N=%d, solver=%s, bmax=%.2f\n', ...
        cfg.grid.N, cfg.solver.name, cfg.forcing.bmax);
    result = brusselator_run_pair(cfg);

    records(k) = struct( ...
        'N', cfg.grid.N, ...
        'seed', cfg.initial.seed, ...
        'solver_name', cfg.solver.name, ...
        'RelTol', cfg.solver.RelTol, ...
        'AbsTol', cfg.solver.AbsTol, ...
        'bmax', cfg.forcing.bmax, ...
        'Tfinal', cfg.time.Tfinal, ...
        'rel_diff_u', result.metrics.rel_diff_u, ...
        'rel_diff_v', result.metrics.rel_diff_v, ...
        'max_diff_u', result.metrics.max_diff_u, ...
        'max_diff_v', result.metrics.max_diff_v, ...
        'class_label', result.class_label, ...
        'runtime_seconds', result.runtime_seconds);

    raw = struct();
    raw.config = cfg;
    raw.ic0 = result.ic0;
    raw.control_final = result.control.ic_final;
    raw.forced_final = result.forced.ic_final;
    raw.metrics = result.metrics;
    raw.class_label = result.class_label;
    raw.runtime_seconds = result.runtime_seconds;
    save(fullfile(outdir, 'raw_final_states', ...
        sprintf('ode15s_N800_bmax_%0.2f.mat', cfg.forcing.bmax)), 'raw');

    progress_table = struct2table(records(1:k), 'AsArray', true);
    writetable(progress_table, fullfile(outdir, 'progress_summary.csv'));
end

summary_table = struct2table(records, 'AsArray', true);
writetable(summary_table, fullfile(outdir, 'high_resolution_summary.csv'));
save(fullfile(outdir, 'high_resolution_summary.mat'), 'summary_table', 'records');
metadata = brusselator_run_metadata(base_cfg, mfilename, sum(summary_table.runtime_seconds));
brusselator_write_metadata(outdir, base_cfg, metadata);

disp(summary_table);
disp(['High-resolution stiff-solver check complete. Results saved in: ', outdir]);
