function checks = validate_ml_BC_boundary_geometry()
%VALIDATE_ML_BC_BOUNDARY_GEOMETRY Audit the frozen plane without modifying it.

cfg=brusselator_ml_boundary_geometry_config();
file=fullfile(cfg.output.root,cfg.experiment_name,'ml_BC_boundary_geometry.mat');
if ~isfile(file)
    error('validate_ml_BC_boundary_geometry:MissingResult', ...
        'Run build_ml_BC_boundary_geometry first.');
end
loaded=load(file,'results'); results=loaded.results;
manifest=results.manifest; states=results.states; summary=results.summary;
roles={manifest.design_role}; n=cfg.ml_boundary.design.master_grid_size;

checks=struct( ...
    'configuration_matches',isequaln(results.configuration,cfg), ...
    'state_count_matches_grid',numel(manifest)==n^2, ...
    'state_arrays_match_manifest',size(states.raw_U,1)==numel(manifest) && ...
        size(states.raw_U,2)==cfg.grid.N && isequal(size(states.raw_U),size(states.raw_V)), ...
    'coordinates_are_unique',size(unique([[manifest.alpha_1]', ...
        [manifest.alpha_2]'],'rows'),1)==numel(manifest), ...
    'initial_seed_count_is_25',sum(strcmp(roles,'initial_seed'))==25, ...
    'fixed_test_count_is_16',sum(strcmp(roles,'fixed_test'))==16, ...
    'acquisition_pool_count_is_248',sum(strcmp(roles,'acquisition_pool'))==248, ...
    'all_simulations_are_unrun',all(strcmp({manifest.simulation_status},'not_run')), ...
    'all_labels_are_empty',all(cellfun(@isempty,{manifest.outcome_label})), ...
    'positivity_gate_passes',min([manifest.minimum_U])>= ...
        cfg.ml_boundary.bounds.minimum_concentration && ...
        min([manifest.minimum_V])>=cfg.ml_boundary.bounds.minimum_concentration, ...
    'coordinate_gate_passes',max([manifest.coordinate_reprojection_error])<1e-10, ...
    'reflection_gate_passes',max([manifest.reflection_invariance_error])< ...
        cfg.ml_boundary.reflection.invariance_tolerance, ...
    'bracket_projection_gate_passes', ...
        min([results.bracket_projection.scaled_retained_fraction])>= ...
        cfg.ml_boundary.basis.minimum_bracket_displacement_retained_fraction, ...
    'exact_edge_excluded',~summary.exact_edge_used_for_construction && ...
        ~any(contains(string({results.source_provenance.path}),'periodic_edge')), ...
    'held_out_region_excluded',~summary.held_out_CA_region_used_for_construction, ...
    'no_outcome_simulations_recorded',summary.simulation_count==0);

values=cell2mat(struct2cell(checks));
if ~all(values)
    names=fieldnames(checks); failed=names(~values);
    error('validate_ml_BC_boundary_geometry:GateFailed', ...
        'Frozen ML geometry failed: %s',strjoin(failed,', '));
end
disp(struct2table(checks,'AsArray',true));
fprintf('All %d frozen-geometry checks passed.\n',numel(values));
end
