function checks = validate_ml_BC_boundary_labeling_setup(cfg)
%VALIDATE_ML_BC_BOUNDARY_LABELING_SETUP Read-only preflight for PDE labeling.

if nargin<1, cfg=brusselator_ml_boundary_labeling_config(); end
if ~isfile(cfg.ml_labeling.geometry_file)
    error('validate_ml_BC_boundary_labeling_setup:MissingGeometry', ...
        'Frozen geometry is missing: %s',cfg.ml_labeling.geometry_file);
end
loaded=load(cfg.ml_labeling.geometry_file,'results'); geometry=loaded.results;
[library,provenance]=brusselator_build_ml_outcome_library(cfg);
selected=strcmp({geometry.manifest.design_role}, ...
    cfg.ml_labeling.selected_design_role);
indices=find(selected); states=geometry.states;

checks=struct( ...
    'geometry_id_matches',strcmp(geometry.summary.geometry_id, ...
        cfg.ml_labeling.expected_geometry_id), ...
    'geometry_grid_matches',geometry.configuration.grid.N==cfg.grid.N && ...
        geometry.configuration.grid.Lx==cfg.grid.Lx, ...
    'selected_count_matches',numel(indices)==cfg.ml_labeling.expected_selected_count, ...
    'selected_states_are_unrun',all(strcmp( ...
        {geometry.manifest(indices).simulation_status},'not_run')), ...
    'selected_labels_are_empty',all(cellfun(@isempty, ...
        {geometry.manifest(indices).outcome_label})), ...
    'selected_states_are_positive',min(min(states.raw_U(indices,:)))>0 && ...
        min(min(states.raw_V(indices,:)))>0, ...
    'library_order_matches',isequal({library.label}, ...
        cfg.ml_labeling.raw_library_order), ...
    'B_C_are_exact',all(strcmp({provenance(2:3).source_kind}, ...
        'exact_newton_periodic_orbit')), ...
    'A_R5_R6_are_validated_stage2',all(strcmp( ...
        {provenance([1,4,5]).source_kind},'validated_stage2_reference')), ...
    'classification_thresholds_unchanged', ...
        cfg.edge_tracking.median_distance_threshold==1e-2 && ...
        cfg.edge_tracking.maximum_distance_threshold==2e-2 && ...
        cfg.edge_tracking.late_window==20, ...
    'adaptive_horizon_is_80_40_400', ...
        cfg.dynamic_edge.classification_initial_duration==80 && ...
        cfg.dynamic_edge.classification_chunk_duration==40 && ...
        cfg.dynamic_edge.classification_maximum_duration==400, ...
    'exact_edge_excluded',~cfg.ml_labeling.exact_edge_orbit_used, ...
    'held_out_region_excluded',~cfg.ml_labeling.held_out_CA_region_used);
values=cell2mat(struct2cell(checks));
if ~all(values)
    names=fieldnames(checks); failed=names(~values);
    error('validate_ml_BC_boundary_labeling_setup:GateFailed', ...
        'Labeling setup failed: %s',strjoin(failed,', '));
end
disp(struct2table(checks,'AsArray',true));
fprintf('All %d adaptive-labeling setup checks passed.\n',numel(values));
end
