function checks = validate_ml_BC_boundary_initial_labels()
%VALIDATE_ML_BC_BOUNDARY_INITIAL_LABELS Audit saved adaptive PDE outcomes.

cfg=brusselator_ml_boundary_labeling_config();
result_file=fullfile(cfg.output.root,cfg.experiment_name, ...
    'ml_BC_boundary_initial_labels.mat');
if ~isfile(result_file)
    error('validate_ml_BC_boundary_initial_labels:MissingResult', ...
        'Missing completed labeling result.');
end
loaded=load(result_file,'results'); results=loaded.results;
geometry_loaded=load(cfg.ml_labeling.geometry_file,'results');
geometry=geometry_loaded.results; records=results.records;
raw_ok=true; state_ok=true; mapping_ok=true; threshold_ok=true;
duration_ok=true; labels_ok=true;
for k=1:numel(records)
    record=records(k);
    if ~isfile(record.raw_file), raw_ok=false; continue; end
    raw=load(record.raw_file,'case_data'); data=raw.case_data;
    expected=[geometry.center.x, ...
        geometry.states.raw_U(record.state_index,:)', ...
        geometry.states.raw_V(record.state_index,:)'];
    state_ok=state_ok && max(abs(data.initial_state(:)-expected(:)))<1e-12;
    labels_ok=labels_ok && strcmp(data.classification.outcome, ...
        record.raw_five_way_outcome) && ...
        isequal(data.classification.labels,cfg.ml_labeling.raw_library_order);
    if strcmp(record.raw_five_way_outcome,'B') || ...
            strcmp(record.raw_five_way_outcome,'C')
        expected_label=record.raw_five_way_outcome;
    elseif ismember(record.raw_five_way_outcome,cfg.ml_labeling.other_raw_outcomes)
        expected_label='other';
    else
        expected_label='U';
    end
    mapping_ok=mapping_ok && strcmp(record.final_label,expected_label);
    if ~strcmp(record.final_label,'U')
        threshold_ok=threshold_ok && sum(data.classification.valid_outcomes)==1;
    else
        duration_ok=duration_ok && ...
            record.tested_duration==cfg.dynamic_edge.classification_maximum_duration;
    end
    duration_ok=duration_ok && record.tested_duration>= ...
        cfg.dynamic_edge.classification_initial_duration && ...
        record.tested_duration<=cfg.dynamic_edge.classification_maximum_duration;
end
reported={records.final_label}; raw_labels={records.raw_five_way_outcome};
summary=results.summary;
checks=struct( ...
    'configuration_matches',isequaln(results.configuration,cfg), ...
    'geometry_id_matches',strcmp(results.geometry_id,geometry.summary.geometry_id), ...
    'case_count_is_25',numel(records)==cfg.ml_labeling.expected_selected_count, ...
    'state_indices_are_unique',numel(unique([records.state_index]))==numel(records), ...
    'all_raw_files_exist',raw_ok,'initial_states_match_geometry',state_ok, ...
    'saved_raw_labels_match',labels_ok,'reported_mapping_is_correct',mapping_ok, ...
    'resolved_labels_pass_unique_threshold',threshold_ok, ...
    'adaptive_durations_are_valid',duration_ok, ...
    'all_reported_labels_are_declared',all(ismember(reported, ...
        cfg.ml_labeling.reported_labels)), ...
    'summary_counts_match',summary.B_count==sum(strcmp(reported,'B')) && ...
        summary.C_count==sum(strcmp(reported,'C')) && ...
        summary.other_count==sum(strcmp(reported,'other')) && ...
        summary.U_count==sum(strcmp(reported,'U')) && ...
        summary.A_raw_count==sum(strcmp(raw_labels,'A')) && ...
        summary.R5_raw_count==sum(strcmp(raw_labels,'R5')) && ...
        summary.R6_raw_count==sum(strcmp(raw_labels,'R6')), ...
    'exact_edge_excluded',~summary.exact_edge_used_for_labeling, ...
    'held_out_region_excluded',~summary.held_out_CA_region_used_for_labeling);
values=cell2mat(struct2cell(checks));
if ~all(values)
    names=fieldnames(checks); failed=names(~values);
    error('validate_ml_BC_boundary_initial_labels:GateFailed', ...
        'Saved labels failed: %s',strjoin(failed,', '));
end
disp(struct2table(checks,'AsArray',true));
fprintf('All %d saved-label checks passed.\n',numel(values));
end
